
export const RAW_DATA: Record<string, string[]> = {
  "Ở nhà": [
    "Tôi vừa 18 tuổi và không biết gì về tình dục, cho đến 1 ngày nhìn thấy Dì và Chú đang làm gì đó trong phòng của họ, cu của tôi đột nhiên căng tức và cương cứng, phải làm sao đây.",
    "Chị gái vô tình ngã vào lòng bạn khi trượt chân trên sàn nhà vừa lau.",
    "Em gái nuôi nhờ bạn xoa bóp vai vì mỏi cổ sau giờ học căng thẳng.",
    "Bạn và mẹ kế cùng lúc mở cửa phòng tắm, thấy bà chỉ quấn độc chiếc khăn mỏng.",
    "Bạn và em gái cùng nằm xem phim, đôi chân nàng vô tình gác lên đùi bạn.",
    "Vô tình thấy chị gái đang soi gương thử bộ bikini mới mua cho chuyến du lịch.",
    "Chị gái bị tuột dây áo lót khi đang nấu ăn, bạn phải giúp nàng cài lại trong sự lúng túng.",
    "Em gái nuôi bị chuột rút trong lúc tắm, bạn phải lao vào bế nàng ra trong tình trạng khỏa thân.",
    "Em gái lén lấy ảnh của bạn để dưới gối, mỗi đêm đều mang ra ngắm nhìn dâm mị.",
    "Chị gái nuôi lén vào phòng bạn lúc nửa đêm, quỳ xuống bú cu bạn với đôi mắt dâm mị.",
    "Nàng em gái lén lấy quần lót của bạn để thủ dâm, bạn bắt quả tang và ép nàng phải dùng miệng mút quy đầu nóng hổi bù đắp.",
    "Bị mẹ kế bắt quả tang đang ngửi đồ lót của bà, bà không mắng mà ép bạn phải nện bà để thỏa mãn cơn vã xác thịt hồi xuân.",
    "Tiếng rên rỉ kìm nén của chị gái từ phòng bên kích thích bạn lẻn vào chăn và bắt đầu hành trình phá nát sự đoan trang của nàng.",
    "Bạn bắt gặp em gái đang dùng dương vật giả, nàng khóc lóc van xin bạn 'giữ bí mật' bằng cách cho bạn nện lồn trinh.",
    "Trong lúc xem phim, cô em gái lén luồn tay vào háng bạn sờ soạn cây cu đang cứng ngắc, đôi mắt nàng dại đi vì dục vọng tội lỗi.",
    "Nàng em gái ngây thơ bị bạn lừa chơi trò 'khám sức khỏe', đôi bàn tay bạn thọc sâu vào hang động khít khao làm nàng phun nước.",
    "Chị gái lén nhìn trộm bạn thủ dâm qua khe cửa, đôi vú nàng ép chặt vào cánh gỗ, dâm thủy chảy ròng ròng xuống bắp đùi.",
    "Trong lúc cả nhà ngủ say, em gái nuôi lén lẻn vào giường bạn, đôi môi nhỏ nhắn mút chặt lấy cây cu gân guốc của bạn trong bóng tối.",
    "Bắt quả tang mẹ kế đang tự sướng bằng cà rốt trong bếp, bạn lấy cây cu nóng hổi của mình thay thế và nện bà đến mức trợn mắt vì sướng.",
    "Cửa phòng em gái không chốt, bạn vô tình thấy nàng đang khỏa thân soi gương, đôi tay đang mân mê núm vú hồng nhạt vì tò mò giới tính.",
    "[HỆ THỐNG]: Cảnh báo: Chỉ số nứng của mẹ kế đang ở mức cực hạn. Hãy thực hiện hành động giải tỏa để nhận 500 điểm kinh nghiệm.",
    "[HỆ THỐNG]: Nhiệm vụ: Khiến mẹ kế chủ động hôn bạn. Phần thưởng: 100 điểm mị lực.",
    "[HỆ THỐNG]: Cảnh báo: Độ hảo cảm của em gái đang tăng vọt. Mở khóa kỹ năng 'Giao tiếp bằng mắt'.",
    "[HỆ THỐNG]: Thông báo: Hãy hoàn thành chuỗi nhiệm vụ 'Gia đình hạnh phúc'. Nhận danh hiệu 'Chủ nhân ngôi nhà'.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp áo lót ren của chị gái một cách dễ dàng.",
  ],
  "Ở nhà thuê": [
    "Vô tình thấy cô bé sinh viên năm nhất đang loay hoay sửa bóng đèn trong phòng.",
    "Cô giáo thực tập phòng đối diện nhờ bạn bê hộ chồng giáo án nặng trịch.",
    "Chiếc khăn tắm của cô nàng streamer bị tuột khi nàng đang mở cửa nhận đồ ship.",
    "Cô bé sinh viên bị kẹt khóa cửa phòng, phải sang phòng bạn ngồi nhờ trong bộ đồ ngủ ngắn.",
    "Dãy trọ cũ kỹ với những bức tường mỏng manh không ngăn được những tiếng động nhạy cảm.",
    "Giúp cô chủ trọ sửa vòi nước, nàng cố tình tì bộ ngực đồ sộ vào lưng bạn, hơi ấm xác thịt lan tỏa khiến cây cu bạn cứng ngắc như thép.",
    "Mưa bão mất điện, cô bé sinh viên phòng bên sợ hãi chạy sang phòng bạn trú ẩn, hai cơ thể quấn chặt lấy nhau giữa bóng tối.",
    "Bé sinh viên năm nhất bị bạn lừa vào phòng, đôi bàn tay bạn thô bạo nhào nặn đôi vú mơn mởn làm nàng khóc lóc trong khoái lạc.",
    "Nữ sinh viên nghèo chấp nhận trả tiền phòng bằng xác thịt, nàng quỳ xuống banh rộng lồn hồng cho bạn tha hồ cày cấy.",
    "Bạn nắc nàng sinh viên ngay trong phòng tắm chung, tiếng rên rỉ bị lấp đầy bởi tiếng nước chảy nhưng vẫn đầy dâm đãng và kích thích.",
    "Chị gái phòng đối diện say rượu gõ nhầm cửa, nàng lao vào ôm hôn bạn, đôi tay tham lam sờ soạng cây cu đang cứng ngắc.",
    "Cô nàng streamer phòng bên mặc áo hai dây không nội y sang nhờ sửa máy tính, núm vú sưng cứng cứ thế cọ vào tay bạn.",
    "Nữ sinh viên tầng trên lén lẻn vào phòng bạn lúc đêm khuya, quỳ xuống bú cu bạn với đôi mắt dâm mị cầu xin được lấp đầy.",
    "Bị bà chủ nhà bắt quả tang đang ngửi đồ lót của nàng, nàng không mắng mà ép bạn phải nện nàng để trả nợ tiền phòng.",
    "Cô nàng streamer phòng bên lén lẻn vào giường bạn, cầu xin bạn nện thật mạnh để tăng cảm hứng livestream dâm dục.",
    "Nhìn trộm nữ sinh phòng bên tự sướng qua lỗ thủng vách tường, nước lồn nàng chảy lênh láng ướt đẫm cả drap giường.",
    "Vô tình va chạm với cô giáo thực tập ở cầu thang, đôi môi nóng hổi của nàng chạm vào môi bạn làm bùng nổ dục vọng.",
    "Bạn nắc cô sinh viên nghèo để trừ tiền trọ, lồn nàng co thắt chặt như muốn nuốt chửng cây cu gân guốc của bạn.",
    "Phòng bên cạnh đang hành lạc, bạn đục lỗ tường và chứng kiến cảnh tượng nhầy nhụa, dương vật bạn cương cứng thách thức.",
    "Tiếng rên rỉ của cặp đôi phòng bên cạnh kích thích bạn và cô bạn trọ cùng lao vào nhau làm tình điên cuồng xuyên đêm.",
    "Cô chủ trọ diện váy ngủ mỏng tang sang thu tiền phòng, nàng cố tình tì bộ ngực đồ sộ vào tay bạn gợi ý 'thanh toán bằng cách khác'.",
    "Bắt quả tang nữ sinh phòng đối diện đang nhìn lén bạn thủ dâm qua khe cửa, bạn lôi nàng vào phòng và bắt nàng phải bú cu cho mình.",
    "Nữ sinh phòng bên chủ động sang gõ cửa lúc nửa đêm chỉ để xin được bạn 'an ủi' thể xác sau khi chia tay bạn trai, hai người quất nhau cả đêm.",
    "[HỆ THỐNG]: Thông báo: Độ thiện cảm của bà chủ nhà đã đạt mức 'Ái Mộ'. Mở khóa nhiệm vụ 'Thanh toán tiền trọ bằng xác thịt'.",
    "[HỆ THỐNG]: Cảnh báo: Nhu cầu xác thịt của chủ thể quá thấp. Bắt buộc thực hiện nhiệm vụ 'Gieo giống' để tránh hình phạt thiến.",
    "[HỆ THỐNG]: Thông báo: Bạn đã thu thập đủ 'Dâm Dịch' của 5 mỹ nhân hàng xóm. Kích hoạt kỹ năng 'Dương Vật Cấp Thần'.",
    "[HỆ THỐNG]: Cảnh báo: Mục tiêu 'Nữ sinh phòng 302' đang trong trạng thái phát tình cực độ. Hãy đến cứu trợ bằng dương vật ngay.",
    "Dị năng 'Dịch Chuyển' giúp bạn lẻn vào giường của bất kỳ mỹ nhân nào trong dãy trọ mỗi đêm mà không để lại bất kỳ dấu vết nào.",
    "Sở hữu dị năng 'Tăng Trưởng Kích Thước', dương vật bạn trở nên vĩ đại khiến mọi cô gái trong nhà thuê đều phải lạy lục van xin.",
    "Dị năng 'Đọc Suy Nghĩ' giúp bạn biết rõ khao khát bị nam giới cưỡng hiếp thầm kín của cô hàng xóm lạnh lùng nhất ngay lúc này."
  ],
  "Ở ghép": [
    "Sống cùng 5 cô gái lạ trong ngôi nhà thuê ở ghép.",
    "Cô bạn cùng phòng nhờ bạn kéo hộ khóa kéo sau lưng chiếc váy dạ hội bó sát.",
    "Vô tình thấy bạn cùng phòng đang quấn khăn tắm bước ra từ phòng vệ sinh.",
    "Cô bạn cùng phòng nhờ bạn sấy tóc hộ, mùi hương dầu gội làm bạn ngây ngất.",
    "Vô tình chạm vào bầu ngực của bạn cùng phòng khi cả hai cùng chen chúc trong bếp.",
    "Bạn và cô bạn cùng phòng cùng nằm trên giường xem phim, không gian trở nên chật hẹp.",
    "Bạn cùng phòng bị đổ cà phê lên váy, phải cởi ra ngay trước mặt bạn để đi giặt.",
    "Bạn cùng phòng bị kẹt trong phòng tắm vì cửa bị hỏng, bạn phải phá cửa vào cứu.",
    "Cô bạn cùng phòng bị trượt chân ngã vào người bạn, cả hai cùng ngã xuống giường.",
    "Cô bạn cùng phòng lén lấy áo sơ mi của bạn mặc để cảm nhận mùi hương của bạn.",
    "Bạn cùng phòng bị kẹt trong phòng tắm vì cửa hỏng, bạn phải phá cửa vào và thấy nàng đang khỏa thân.",
    "Đang ngủ thì cô bạn cùng phòng mộng du leo lên giường ôm chặt lấy bạn như một con gấu bông.",
    "Cả hai cùng uống say sau buổi tiệc, cô bạn cùng phòng chủ động tấn công đôi môi của bạn nồng cháy.",
    "Trò chơi 'thật hay thách' khiến cô bạn cùng phòng phải cởi bỏ toàn bộ nội y ngay trước mắt bạn.",    "[HỆ THỐNG]: Nhiệm vụ: Khiến bạn cùng phòng chủ động ôm bạn từ phía sau. Phần thưởng: 50 điểm tình cảm.",
    "[HỆ THỐNG]: Cảnh báo: Bạn cùng phòng đang cảm thấy cô đơn. Hãy thực hiện hành động an ủi.",
    "[HỆ THỐNG]: Thông báo: Bạn đã đạt mức độ thân thiết 'Tri Kỷ' với bạn cùng phòng.",
    "Dị năng 'Đọc Suy Nghĩ' giúp bạn biết rõ những khao khát thầm kín của bạn cùng phòng.",

  ],
  "Chung cư": [
    "Tôi trở thành quản lý của chung cư toàn nữ sống.",
    "Bạn lén nhìn qua ống nhòm thấy cô gái tòa nhà đối diện đang khỏa thân tắm nắng.",
    "[HỆ THỐNG]: Nhiệm vụ: Trở thành 'Người tình bí mật' của 3 quý bà trong chung cư. Phần thưởng: Thẻ cư dân VIP.",
    "Dị năng 'Thấu Thị Lượng Tử' giúp bạn nhìn xuyên qua mọi bức tường trong chung cư.",
    "Dị năng 'Dịch Chuyển Tức Thời' giúp bạn lẻn vào bất kỳ căn hộ nào chỉ trong chớp mắt.",
  ],
  "Trường cấp 3": [
    "Tôi trở thành hiệu trưởng và thi hành chính sách mới dành riêng cho các nữ sinh.",
    "Chuyến đi cắm trại cấp 3 đầy vú và lồn xinh tươi.",
    "Bắt gặp cô giáo xinh đẹp đang tắm sau khi bơi, tôi chụp ảnh lại và bị cô phát hiện, cô bắt cưởi quần ra cho cô chụp ảnh cu.",
    "Quy tắc mới, các học sinh phải cởi bỏ váy, quần, quần lót rồi mới được vào lớp.",
    "Lớp học dạy và thực hành làm tình an toàn.",
    "[HỆ THỐNG]: Nhiệm vụ: Trở thành 'Nam thần học đường' trong mắt toàn bộ nữ sinh. Phần thưởng: Kỹ năng 'Thuyết phục'.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp đồng phục của mọi nữ sinh để chiêm ngưỡng vùng kín.",
  ],
  "Đại học": [
    "Chinh phục các mĩ nhân ở đại học.",
    "[HỆ THỐNG]: Cảnh báo: Hoa khôi của trường đang bị một đám nam sinh quấy rối. Hãy đến cứu mỹ nhân.",
    "[HỆ THỐNG]: Thông báo: Bạn đã mở khóa quyền truy cập vào hồ sơ cá nhân của mọi sinh viên nữ.",
    "Dị năng 'Đọc Suy Nghĩ' giúp bạn biết rõ những khao khát xác thịt thầm kín của bất kỳ nữ sinh nào.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp quần áo của mọi mỹ nhân trong trường đại học.",
    "Dị năng 'Thao Túng Cảm Xúc' khiến bất kỳ cô gái nào nhìn thấy bạn cũng đều cảm thấy hưng phấn."
  ],
  "Học viện nữ sinh": [
    "Tôi được chọn làm mẫu khỏa thân cho các nữ sinh vẽ.",
    "Lớp học về nam giới của trường nữ sinh.",
    "Bạn bước vào phòng nghệ thuật và thấy một nữ sinh đang khỏa thân làm mẫu cho lớp vẽ.",
    "[HỆ THỐNG]: Nhiệm vụ: Trở thành 'Chủ nhân' thực sự của toàn bộ nữ sinh trong học viện. Phần thưởng: Quyền năng tối thượng.",
    "[HỆ THỐNG]: Cảnh báo: Một nhóm nữ sinh đang có ý định 'thử thách' bản lĩnh đàn ông của bạn.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp đồng phục kín đáo của mọi mỹ nhân học viện.",
    "Dị năng 'Tăng Trưởng Kích Thước' khiến dương vật bạn trở nên vĩ đại, phá nát mọi ranh giới đạo đức."
  ],
  "Bệnh viện": [
    "Bệnh viện chuyên chữa bệnh cho nam giới bằng tình dục.",
    "Bệnh viện chuyên chữa bệnh về sinh lí, tình dục cho nam giới.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp áo blouse của mọi nữ bác sĩ để chiêm ngưỡng vùng kín.",
  ],
  "Phòng làm việc": [
    "Nàng thư ký điên cuồng yêu tôi.",
    "Cô nàng thực tập sinh lén rủ bạn vào phòng kho để 'tâm sự' riêng tư sau giờ làm.",
    "[HỆ THỐNG]: Nhiệm vụ: Khiến nữ giám đốc chủ động mời bạn đi ăn tối. Phần thưởng: 200 điểm mị lực.",
    "[HỆ THỐNG]: Cảnh báo: Nàng thư ký đang có ý định 'quyến rũ' bạn để thăng tiến.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp áo sơ mi của mọi nữ đồng nghiệp.",
    "Dị năng 'Đọc Suy Nghĩ' giúp bạn biết rõ những dục vọng thầm kín của sếp nữ dành cho bạn.",
  ],
  "Phòng gym": [
    "Mỹ nhân yoga lén rủ bạn vào phòng tập vắng vẻ để 'tâm sự' riêng tư sau giờ tập.",
    "[HỆ THỐNG]: Cảnh báo: Nữ huấn luyện viên đang có ý định 'thử thách' thể lực của bạn.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp quần tập spandex của mọi mỹ nhân.",
    "Dị năng 'Cường Hóa Vật Lý' khiến dương vật bạn trở nên cứng ngắc như kim cương.",
  ],
  "Công Ty giải trí": [
    "Tìm kiếm tài năng mới.",
    "1 ngày làm việc của Giám đốc quản lí tài năng.",
    "[HỆ THỐNG]: Cảnh báo: Nàng idol đang có ý định 'quyến rũ' bạn để được ra mắt sớm.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp váy dạ hội của mọi nữ minh tinh.",
    "Dị năng 'Đọc Suy Nghĩ' giúp bạn biết rõ những dục vọng thầm kín của nàng ca sĩ dành cho bạn.",
  ],
  "Trường quay AV": [
    "Buổi chụp ảnh nóng cuồng nhiệt.",
    "Buổi tuyển chọn nữ diễn viên AV mới.",
    "Nàng diễn viên chính lén rủ bạn vào phòng nghỉ vắng vẻ để 'tâm sự' riêng tư.",
    "[HỆ THỐNG]: Cảnh báo: Nàng diễn viên tân binh đang có ý định 'quyến rũ' bạn để được đóng chính.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp đồ lót gợi cảm của mọi nữ diễn viên.",
    "Dị năng 'Tăng Trưởng Kích Thước' khiến dương vật bạn trở nên vĩ đại, phá nát mọi ranh giới.",
  ],
  "Biệt thự": [
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp váy lụa của mọi phu nhân hào môn.",
    "Dị năng 'Tăng Trưởng Kích Thước' khiến dương vật bạn trở nên vĩ đại, phá nát mọi ranh giới."
  ],
  "Penhouse": [
    "Dị năng 'Thấu Thị Lượng Tử' giúp bạn nhìn xuyên qua lớp váy lụa của mọi mỹ nhân Penthouse.",
    "Dị năng 'Tăng Trưởng Kích Thước' khiến dương vật bạn trở nên vĩ đại, phá nát mọi ranh giới."
  ],
  "Trên chuyến xe đường dài": [
    "Ngồi cạnh cô gái đang nứng trên chuyến xe đường dài.",
    "Ngồi cạnh cô gái trên chuyến xe, cả 2 phát hiện cặp đôi phía sau đang lén lút làm tình.",
    "Ngồi cạnh chị gái xinh đẹp trên chuyến xe.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp quần áo của mọi nữ hành khách trên xe.",
    "Dị năng 'Đọc Suy Nghĩ' giúp bạn biết rõ những dục vọng thầm kín của cô nàng sinh viên.",
  ],
  "Tự do": [
    "Chàng shipper may mắn và cô chủ nhà nứng lồn.",
    "Chàng shipper may mắn và cô chủ nhà thả rông cặp vú to.",
    "Chàng tài xế xe công nghệ may mắn và cô khách đi xe nứng lồn.",
    "Gặp được cô nhân viên Cửa hàng tiện lợi dâm đãng thích tư vấn bán bao cao su.",
    "Cứu mĩ nhân ở Bể bơi công cộng.",
    "Làm quen với cô gái khi đi xem phim kinh dị ở rạp chiếu phim, cô gái nhát gan thích xem phim kinh dị.",
    "làm quen với cô tiếp viên xinh đẹp trên Máy bay.",
    "Cứu mĩ nhân ở Bãi biển/Resort.",
    "Lên giường với gái lạ sau khi say.",
    "Cứu mĩ nhân khỏi tay bọn du côn.",
    "Làm gia sư cho cô gái dâm có mẹ trẻ đẹp.",
    "Cứu cô gái nghèo ở Quán Bar/Vũ trường.",
    "Bắt gặp cô gái trẻ chỉ mặc 1 chiếc áo 2 dây đang thủ dâm ở công viên.",
    "Thuê phải cô gia sư trẻ mà dâm đãng.",
    "Đi ăn cùng nhóm bạn thì nhặt được chiếc điều khiển máy rung của cô bạn đánh rơi.",
    "Tôi mở nhà hàng và bắt nữ nhân viên không mặc quần lót.",
    "[HỆ THỐNG]: Hệ thống Cày điểm hảo cảm mĩ nữ.",
    "[HỆ THỐNG]: Hệ thống Điểm danh.",
    "[HỆ THỐNG]: Hệ thống Mỗi tuần có 1 nghề nghiệp mới.",
    "[HỆ THỐNG]: Hệ thống Có 999999 tỷ tiền liếm cẩu, tiêu tiền cho gái để được hoàn trả gấp nhiều lần.",
    "[HỆ THỐNG]: Hệ thống Thần hào.",
  ],
  "Trên tàu điện": [
    "Vô tình chạm tay vào nữ hành khách khi cả hai cùng nắm lấy tay vịn trên tàu.",
    "Nữ nhân viên tàu lén rủ bạn vào khoang nghỉ vắng vẻ để 'tâm sự' riêng tư sau ca làm.",
    "[HỆ THỐNG]: Cảnh báo: Nữ nhân viên tàu đang có ý định 'quyến rũ' bạn để được giúp đỡ.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp quần áo của mọi nữ hành khách trên tàu.",
    "Dị năng 'Đọc Suy Nghĩ' giúp bạn biết rõ những dục vọng thầm kín của cô nàng công sở.",
  ],
};

export const IDENTITIES: string[] = Object.entries(RAW_DATA).flatMap(([context, scenarios]) => 
  scenarios.map(s => `Bối cảnh: ${context} - ${s}`)
);

export const SPECIALIZED_DATA: Record<string, { label: string, action: string }[]> = {};
