export const SYSTEMS_DATA = [
  { title: "Hệ thống Phản Phái Tối Thượng", tag: "Cực ác", color: "text-red-500", desc: "Nhận điểm khi vả mặt nam chính và thu phục nữ chính." },
  { title: "Hệ thống Harem Vạn Giới", tag: "Đào hoa", color: "text-pink-500", desc: "Mở khóa kỹ năng mới sau mỗi lần mở rộng hậu cung." },
  { title: "Hệ thống Thần Cấp Shipper", tag: "Tốc độ", color: "text-yellow-500", desc: "Giao hàng đến vạn giới, nhận thưởng linh thạch vô hạn." },
  { title: "Hệ thống Tu Vi Nhân Bản", tag: "Hack", color: "text-emerald-500", desc: "Tự động sao chép tu vi của bất kỳ ai đứng gần." },
  { title: "Hệ thống Chỉnh Sửa Thực Tại", tag: "Vô hạn", color: "text-cyan-500", desc: "Cho phép thay đổi 1 quy luật vật lý hoặc xã hội mỗi ngày." },
  { title: "Hệ thống Điểm Danh Hằng Ngày", tag: "Phúc lợi", color: "text-amber-400", desc: "Chỉ cần tồn tại là nhận được bảo vật thần thánh." },
  { title: "Hệ thống Thần Y Đô Thị", tag: "Y thuật", color: "text-teal-400", desc: "Nhìn thấu mọi căn bệnh và bí mật cơ thể phụ nữ." },
  { title: "Hệ thống Nghịch Chuyển Vận Mệnh", tag: "Trùng sinh", color: "text-indigo-400", desc: "Dự báo trước các thảm họa và cơ duyên sắp xảy ra." },
  { title: "Hệ thống Tối Thượng Bố Già", tag: "Quyền lực", color: "text-slate-400", desc: "Thâu tóm mọi tập đoàn tài chính chỉ bằng ý nghĩ." },
  { title: "Hệ thống Thôn Phệ Linh Hồn", tag: "Cấm kỵ", color: "text-purple-600", desc: "Hấp thụ năng lượng từ nỗi sợ hãi và dục vọng của kẻ thù." },
  { title: "Hệ thống Nam Thần Toàn Cầu", tag: "Mị lực", color: "text-rose-400", desc: "Khiến mọi phụ nữ phải khao khát khi nhìn thấy bạn." },
  { title: "Hệ thống Shop Vạn Năng", tag: "Giao dịch", color: "text-orange-400", desc: "Mua được mọi thứ từ súng hạt nhân đến tiên đan." },
  { title: "Hệ thống Thao Túng Tâm Trí", tag: "Tâm lý", color: "text-violet-500", desc: "Biến bất kỳ ai thành nô lệ chỉ qua ánh mắt." },
  { title: "Hệ thống Đấu Giá Lượng Tử", tag: "Tiền bạc", color: "text-yellow-600", desc: "Đấu giá và thâu tóm các bảo vật xuyên không gian." },
  { title: "Hệ thống Chiến Thần Bất Tử", tag: "Chiến đấu", color: "text-red-700", desc: "Càng bị thương sức mạnh càng tăng gấp bội lần." },
  { title: "Hệ thống Quản Gia Hào Môn", tag: "Phục tùng", color: "text-blue-400", desc: "Điều khiển toàn bộ mạng lưới người hầu và bí mật gia tộc." },
  { title: "Hệ thống Hack Ma Mạng", tag: "Công nghệ", color: "text-cyan-600", desc: "Nắm giữ mọi thông tin cá nhân và tài khoản vạn giới." },
  { title: "Hệ thống Sưu Tầm Mỹ Nhân Đồ", tag: "Sưu tầm", color: "text-pink-600", desc: "Mỗi mỹ nhân thu phục hóa thành một thẻ bài sức mạnh." },
  { title: "Hệ thống Luật Lệ Công Cộng", tag: "Adult", color: "text-orange-500", desc: "Ban hành các luật lệ xác thịt bắt buộc lên xã hội." },
  { title: "Hệ thống Thần Cấp Kỹ Sư", tag: "Chế tác", color: "text-lime-500", desc: "Nâng cấp vật dụng bình thường thành thần khí." },
  { title: "Hệ thống Chụp Ảnh Định Mệnh", tag: "Bí mật", color: "text-zinc-400", desc: "Chụp ảnh ai đó sẽ hiện ra tội lỗi và điểm yếu của họ." },
  { title: "Hệ thống Thiên Tài Đầu Tư", tag: "Tài chính", color: "text-green-400", desc: "Nhìn thấy tương lai của mọi biểu đồ chứng khoán." },
  { title: "Hệ thống Trấn Giữ Cấm Địa", tag: "Phòng thủ", color: "text-stone-500", desc: "Nhận quà khủng mỗi khi đẩy lùi kẻ xâm nhập." },
  { title: "Hệ thống Chăn Nuôi Thần Thú", tag: "Triệu hồi", color: "text-orange-500", desc: "Tiến hóa các loài vật bình thường thành rồng phượng." },
  { title: "Hệ thống Sát Thủ Bóng Đêm", tag: "Ám sát", color: "text-gray-900", desc: "Nhận kỹ năng tàng hình khi ở trong vùng tối." },
  { title: "Hệ thống Cưỡng Đoạt Khí Vận", tag: "Khí vận", color: "text-yellow-200", desc: "Cướp đi may mắn của con cưng trời đất." },
  { title: "Hệ thống Thần Cấp Đầu Bếp", tag: "Ẩm thực", color: "text-rose-300", desc: "Món ăn có thể tăng tu vi hoặc mê hoặc tâm trí." },
  { title: "Hệ thống Tối Thượng Học Tra", tag: "Nghịch tập", color: "text-blue-200", desc: "Điểm thi càng thấp sức mạnh chiến đấu càng cao." },
  { title: "Hệ thống Thẩm Phán Linh Hồn", tag: "Công lý", color: "text-sky-500", desc: "Trừng phạt kẻ ác để nhận lấy công đức kim thân." },
  { title: "Hệ thống Xây Dựng Tông Môn", tag: "Lãnh đạo", color: "text-indigo-600", desc: "Mở rộng lãnh thổ để nhận tài nguyên vô tận." },
  { title: "Hệ thống Thú Cưng Mỹ Nhân", tag: "Harem", color: "text-fuchsia-400", desc: "Biến các nữ chính thành linh thú đi theo phục vụ." },
  { title: "Hệ thống Ma Vương Thức Tỉnh", tag: "Hắc ám", color: "text-purple-900", desc: "Gây ra nỗi sợ hãi để khôi phục quyền năng tối thượng." },
  { title: "Hệ thống Siêu Cấp Xây Dựng", tag: "Kiến trúc", color: "text-lime-600", desc: "Tạo ra pháo đài bất khả xâm phạm trong tích tắc." },
  { title: "Hệ thống Thần Cấp May Mắn", tag: "May rủi", color: "text-yellow-400", desc: "Mọi lựa chọn ngẫu nhiên đều dẫn đến kết quả tốt nhất." },
  { title: "Hệ thống Thao Túng Thời Gian", tag: "Thời gian", color: "text-indigo-300", desc: "Lưu trữ và tải lại các khoảnh khắc trong quá khứ." },
  { title: "Hệ thống Thần Cấp Đạo Tặc", tag: "Trộm cắp", color: "text-neutral-400", desc: "Trộm lấy kỹ năng, ký ức hoặc thậm chí là trái tim." },
  { title: "Hệ thống Nuôi Dưỡng Nữ Đế", tag: "Sư phụ", color: "text-amber-500", desc: "Đào tạo các cô gái thành những vị vua thống trị." },
  { title: "Hệ thống Thần Cấp Thợ Rèn", tag: "Rèn đúc", color: "text-orange-700", desc: "Đúc nên những thanh kiếm có linh hồn riêng." },
  { title: "Hệ thống Game Hóa Thực Tại", tag: "Gamer", color: "text-cyan-300", desc: "Biến thế giới thành trò chơi với bảng chỉ số và nhiệm vụ." },
  { title: "Hệ thống Triệu Hồi Anh Hùng", tag: "Huyền thoại", color: "text-white", desc: "Gọi lên linh hồn các vị vua quá cố để chiến đấu." },
  { title: "Hệ thống Tình Yêu Tội Lỗi", tag: "Cấm kỵ", color: "text-red-900", desc: "Nhận điểm khi phá vỡ các giới hạn đạo đức xã hội." },
  { title: "Hệ thống Thần Cấp Ngư Dân", tag: "Thủy tộc", color: "text-blue-500", desc: "Câu lên được mọi thứ từ biển cả, kể cả mỹ nhân ngư." },
  { title: "Hệ thống Thao Túng Không Gian", tag: "Không gian", color: "text-sky-300", desc: "Tạo ra các hố đen và cổng dịch chuyển tức thời." },
  { title: "Hệ thống Thần Cấp Nông Dân", tag: "Sự sống", color: "text-green-700", desc: "Trồng linh thảo và thu hoạch tu vi hằng ngày." },
  { title: "Hệ thống Sát Thần Tối Cao", tag: "Diệt thần", color: "text-red-600", desc: "Sát thương tăng 1000% khi đối đầu với thần linh." },
  { title: "Hệ thống Thần Cấp Nhạc Công", tag: "Âm thanh", color: "text-teal-500", desc: "Dùng tiếng đàn để chữa lành hoặc hủy diệt linh hồn." },
  { title: "Hệ thống Thao Túng Giấc Mơ", tag: "Ảo mộng", color: "text-purple-400", desc: "Xâm nhập và điều khiển thực tại trong mơ của đối phương." },
  { title: "Hệ thống Thần Cấp Vệ Sĩ", tag: "Bảo vệ", color: "text-slate-500", desc: "Nhận sức mạnh khi bảo vệ thành công mục tiêu nữ." },
  { title: "Hệ thống Thôn Phệ Thiên Đạo", tag: "Nghịch thiên", color: "text-indigo-900", desc: "Thay thế ý chí thế giới bằng ý chí của chính mình." },
  { title: "Hệ thống Thần Cấp Lái Xe", tag: "Tốc độ", color: "text-orange-300", desc: "Mọi phương tiện đều có thể bay và xuyên không gian." },
  { title: "Hệ thống Thao Túng Kim Tiền", tag: "Tài phiệt", color: "text-emerald-300", desc: "Dùng tiền đè chết người theo đúng nghĩa đen." },
  { title: "Hệ thống Thần Cấp Thầy Giáo", tag: "Tri thức", color: "text-blue-400", desc: "Dạy dỗ các nữ sinh trở thành những thiên tài dị năng." },
  { title: "Hệ thống Đấu Trường Sinh Tử", tag: "Chiến tranh", color: "text-red-800", desc: "Bắt kẻ thù tham gia trò chơi sinh mạng do bạn làm chủ." },
  { title: "Hệ thống Thần Cấp Nhà Văn", tag: "Sáng tạo", color: "text-neutral-500", desc: "Viết ra kịch bản và thực tại sẽ diễn ra y hệt." },
  { title: "Hệ thống Thao Túng Thời Tiết", tag: "Thiên tai", color: "text-sky-600", desc: "Gọi mưa gọi gió, triệu hồi sấm sét trừng phạt." },
  { title: "Hệ thống Thần Cấp Thám Tử", tag: "Trí tuệ", color: "text-cyan-700", desc: "Tái hiện mọi hiện trường vụ án chỉ bằng trực giác." },
  { title: "Hệ thống Sưu Tầm Linh Hồn", tag: "Tử thần", color: "text-gray-800", desc: "Mỗi linh hồn thu thập được sẽ tăng tuổi thọ vô hạn." },
  { title: "Hệ thống Thần Cấp Barber", tag: "Thẩm mỹ", color: "text-pink-300", desc: "Chỉnh sửa diện mạo và gen của bất kỳ ai." },
  { title: "Hệ thống Thao Túng Trọng Lực", tag: "Vật lý", color: "text-slate-700", desc: "Ép đối phương quỳ rạp dưới chân bằng áp suất ngàn cân." },
  { title: "Hệ thống Thần Cấp Phi Công", tag: "Bầu trời", color: "text-white", desc: "Làm chủ bầu trời và các phi thuyền không gian." },
  { title: "Hệ thống Thôn Phệ Dị Năng", tag: "Cướp đoạt", color: "text-violet-700", desc: "Lấy cắp năng lượng của các dị nhân khác khi giao tiếp." },
  { title: "Hệ thống Thần Cấp Luật Sư", tag: "Quy tắc", color: "text-indigo-500", desc: "Dùng kẽ hở luật pháp để thay đổi sự thật thực tại." },
  { title: "Hệ thống Thao Túng Nguyên Tố", tag: "Nguyên tố", color: "text-emerald-400", desc: "Làm chủ 5 đại nguyên tố cơ bản của vũ trụ." },
  { title: "Hệ thống Thần Cấp Họa Sĩ", tag: "Nghệ thuật", color: "text-rose-500", desc: "Vẽ ra mỹ nhân, mỹ nhân sẽ bước ra ngoài đời thực." },
  { title: "Hệ thống Sát Thủ Hào Môn", tag: "Báo thù", color: "text-red-400", desc: "Nhận điểm khi tiêu diệt các gia tộc hãm hại bạn." },
  { title: "Hệ thống Thần Cấp Dược Sĩ", tag: "Luyện dược", color: "text-green-300", desc: "Chế tạo các loại thuốc kích dục và trường sinh." },
  { title: "Hệ thống Thao Túng Bóng Tối", tag: "Hắc ám", color: "text-black", desc: "Điều khiển cái bóng của mọi sinh linh để ám sát." },
  { title: "Hệ thống Thần Cấp Thợ Xăm", tag: "Phù văn", color: "text-purple-500", desc: "Xăm các phù văn sức mạnh hoặc nô lệ lên cơ thể." },
  { title: "Hệ thống Thôn Phệ Huyết Mạch", tag: "Tiến hóa", color: "text-rose-700", desc: "Hấp thụ gen của các chủng tộc mạnh nhất vũ trụ." },
  { title: "Hệ thống Thần Cấp Streamer", tag: "Danh vọng", color: "text-red-500", desc: "Càng nhiều người xem, công lực càng tăng mạnh." },
  { title: "Hệ thống Thao Túng Ánh Sáng", tag: "Thánh khiết", color: "text-yellow-100", desc: "Ban phước hoặc thiêu rụi kẻ địch bằng quang năng." },
  { title: "Hệ thống Thần Cấp Ngủ Ngon", tag: "Lười biếng", color: "text-blue-300", desc: "Càng ngủ lâu, tu vi khi tỉnh dậy càng khủng khiếp." },
  { title: "Hệ thống Sát Thủ Kinh Tế", tag: "Thao túng", color: "text-green-600", desc: "Hủy diệt các quốc gia chỉ bằng các lệnh giao dịch." },
  { title: "Hệ thống Thần Cấp Thợ May", tag: "Trang phục", color: "text-fuchsia-300", desc: "May đồ lót ma pháp có khả năng điều khiển ham muốn." },
  { title: "Hệ thống Thao Túng Côn Trùng", tag: "Dịch bệnh", color: "text-lime-700", desc: "Điều khiển hàng tỷ sinh vật nhỏ bé để do thám." },
  { title: "Hệ thống Thần Cấp Lữ Hành", tag: "Khám phá", color: "text-amber-300", desc: "Nhận quà khi đặt chân đến những vùng đất mới." },
  { title: "Hệ thống Thôn Phệ Nỗi Sợ", tag: "Tâm trí", color: "text-zinc-800", desc: "Biến sự hoảng loạn của đám đông thành sức mạnh." },
  { title: "Hệ thống Thần Cấp Trấn Giữ", tag: "Trấn thủ", color: "text-orange-900", desc: "Bất khả chiến bại khi đứng trên lãnh thổ của mình." },
  { title: "Hệ thống Thao Túng Sự Sống", tag: "Sáng thế", color: "text-emerald-900", desc: "Tạo ra các chủng tộc mới theo ý muốn cá nhân." },
  { title: "Hệ thống Thần Cấp Đồ Chơi", tag: "Adult", color: "text-pink-400", desc: "Biến mọi vật dụng thành sextoy ma pháp cấp thần." },
  { title: "Hệ thống Thôn Phệ Ma Pháp", tag: "Phản phệ", color: "text-indigo-800", desc: "Hấp thụ và phản trả mọi đòn tấn công ma thuật." },
  { title: "Hệ thống Thần Cấp Sư Phụ", tag: "Dẫn dắt", color: "text-yellow-500", desc: "Nhận phản hồi tu vi từ mọi đệ tử trung thành." },
  { title: "Hệ thống Thao Túng Thực Vật", tag: "Thiên nhiên", color: "text-green-500", desc: "Biến rừng già thành quân đoàn chiến tranh xanh." },
  { title: "Hệ thống Thần Cấp Bảo Vệ", tag: "Hộ vệ", color: "text-blue-900", desc: "Bất tử khi đang che chắn cho một ai đó." },
  { title: "Hệ thống Thôn Phệ Linh Thạch", tag: "Phú gia", color: "text-yellow-300", desc: "Ăn linh thạch để thăng cấp tu vi trực tiếp." },
  { title: "Hệ thống Thần Cấp Sát Gái", tag: "Mị lực", color: "text-rose-600", desc: "Phụ nữ sẽ tự động nảy sinh hảo cảm cực cao." },
  { title: "Hệ thống Thao Túng Âm Dương", tag: "Cân bằng", color: "text-neutral-500", desc: "Đảo lộn giới tính và quy luật sinh hóa vạn vật." },
  { title: "Hệ thống Thần Cấp Nhặt Rác", tag: "Cơ duyên", color: "text-stone-400", desc: "Nhặt rác nhặt được cả thần binh và tiên đơn." },
  { title: "Hệ thống Thôn Phệ Hư Không", tag: "Nuốt chửng", color: "text-purple-800", desc: "Nuốt cả một thế giới vào trong không gian riêng." },
  { title: "Hệ thống Thần Cấp Hoàng Đế", tag: "Vương quyền", color: "text-yellow-700", desc: "Vạn dân quỳ lạy, lời nói là thánh chỉ thực tại." },
  { title: "Hệ thống Thao Túng Gen", tag: "Tiến hóa", color: "text-cyan-400", desc: "Thiết kế lại mã nguồn sinh học của chính mình." },
  { title: "Hệ thống Thần Cấp Đao Phủ", tag: "Phán quyết", color: "text-red-900", desc: "Chém đứt linh hồn và sợi dây nhân quả kẻ thù." },
  { title: "Hệ thống Thôn Phệ Linh Thể", tag: "Hồn đạo", color: "text-indigo-400", desc: "Hấp thụ linh hồn các đại năng để lấy tri thức." },
  { title: "Hệ thống Thần Cấp Người Hầu", tag: "Nghịch tập", color: "text-slate-300", desc: "Hầu hạ mỹ nhân càng tốt sức mạnh càng tăng." },
  { title: "Hệ thống Thao Túng Vận May", tag: "Khí vận", color: "text-amber-200", desc: "Làm chủ các biến số ngẫu nhiên của vũ trụ." },
  { title: "Hệ thống Thần Cấp Ẩn Sĩ", tag: "Ẩn danh", color: "text-neutral-700", desc: "Càng ít người biết đến, tu vi càng thâm hậu." },
  { title: "Hệ thống Thôn Phệ Vạn Vật", tag: "Tối thượng", color: "text-orange-600", desc: "Hóa thân thành hố đen nuốt chửng mọi thực tại." },
  { title: "Hệ thống Thần Cấp Chí Tôn", tag: "Vô địch", color: "text-yellow-500", desc: "Bắt đầu game với cấp độ tối đa và mọi kĩ năng." }
];