export const CUSTOM_URBAN_SUPER = [
  { title: "Thực thể hư không hóa hình", tag: "Cấm kỵ", color: "text-purple-500" },
  { title: "Vật thí nghiệm cấp SSS đào tẩu", tag: "Dị biến", color: "text-red-500" },
  { title: "Thần linh sa ngã", tag: "Thần thoại", color: "text-yellow-500" },
  { title: "Kẻ mang mầm bệnh dị năng", tag: "Nguy hiểm", color: "text-emerald-500" },
  { title: "Hacker ma mạng", tag: "Công nghệ", color: "text-cyan-500" },
  { title: "Thợ săn thần linh", tag: "Sát thần", color: "text-orange-500" },
  { title: "Người máy có linh hồn", tag: "Cơ khí", color: "text-slate-400" },
  { title: "Pháp sư đô thị bí ẩn", tag: "Ma thuật", color: "text-violet-400" },
  { title: "Kẻ đi xuyên gương", tag: "Không gian", color: "text-blue-300" },
  { title: "Người điều khiển thời gian", tag: "Thời gian", color: "text-indigo-600" },
  { title: "Dị nhân hệ hỏa cuồng bạo", tag: "Hủy diệt", color: "text-red-600" },
  { title: "Thực thể ký sinh mỹ nhân", tag: "Chiếm hữu", color: "text-rose-500" },
  { title: "Kẻ thu thập linh hồn phố đêm", tag: "Bóng tối", color: "text-neutral-700" },
  { title: "Chiến binh nano tương lai", tag: "Vũ khí", color: "text-cyan-300" },
  { title: "Người cá sống trong hồ bơi", tag: "Thủy tộc", color: "text-sky-400" },
  { title: "Thánh tử của giáo phái dị năng", tag: "Tôn giáo", color: "text-amber-500" },
  { title: "Bóng ma trong máy chủ", tag: "Kỹ thuật", color: "text-green-400" },
  { title: "Kẻ tạo ra ảo mộng dâm dục", tag: "Ảo giác", color: "text-pink-500" },
  { title: "Thợ rèn phù văn hiện đại", tag: "Luyện khí", color: "text-yellow-400" },
  { title: "Ma cà rồng hào môn", tag: "Huyết tộc", color: "text-rose-700" },
  { title: "Người sói bảo vệ hộp đêm", tag: "Dã tính", color: "text-orange-700" },
  { title: "Thực thể ánh sáng thuần khiết", tag: "Thánh khiết", color: "text-white" },
  { title: "Kẻ buôn bán dị năng", tag: "Thương nhân", color: "text-yellow-600" },
  { title: "Người điều khiển giấc mơ", tag: "Tâm trí", color: "text-purple-300" },
  { title: "Dị nhân lôi hệ tốc độ cao", tag: "Sấm sét", color: "text-yellow-300" },
  { title: "Thực thể âm nhạc chết chóc", tag: "Âm thanh", color: "text-teal-400" },
  { title: "Kẻ sở hữu mắt thần", tag: "Nhìn thấu", color: "text-cyan-600" },
  { title: "Người biến hình vạn năng", tag: "Ngụy trang", color: "text-zinc-500" },
  { title: "Thần chết thực tập", tag: "Diệt vong", color: "text-black" },
  { title: "Kẻ canh giữ cổng địa ngục", tag: "Trấn thủ", color: "text-red-900" },
  { title: "Người bay lượn trên cao ốc", tag: "Tự do", color: "text-sky-300" },
  { title: "Thực thể trọng lực tàn nhẫn", tag: "Vật lý", color: "text-slate-600" },
  { title: "Kẻ điều khiển bầy côn trùng", tag: "Dịch bệnh", color: "text-lime-600" },
  { title: "Người khổng lồ đô thị", tag: "Sức mạnh", color: "text-orange-400" },
  { title: "Thực thể nano cộng sinh", tag: "Cyborg", color: "text-cyan-200" },
  { title: "Phù thủy hiện đại (Urban Witch)", tag: "Bí thuật", color: "text-indigo-400" },
  { title: "Kẻ mở cổng không gian trái phép", tag: "Vượt biên", color: "text-sky-500" },
  { title: "Người có khả năng ngưng đọng thực tại", tag: "Tuyệt đối", color: "text-zinc-100" },
  { title: "Thực thể ký sinh bóng tối", tag: "Ám ảnh", color: "text-neutral-900" },
  { title: "Kẻ ăn cắp ký ức hào môn", tag: "Tâm lý", color: "text-violet-600" },
  { title: "Dị nhân điều khiển kim loại", tag: "Cơ khí", color: "text-slate-500" },
  { title: "Người rồng thức tỉnh trong phố", tag: "Long tộc", color: "text-rose-600" },
  { title: "Thực thể ánh sáng hủy diệt", tag: "Phát quang", color: "text-yellow-200" },
  { title: "Kẻ triệu hồi ác quỷ đô thị", tag: "Tà thuật", color: "text-red-700" },
  { title: "Người có khả năng tàng hình vĩnh cửu", tag: "Vô hình", color: "text-neutral-400" },
  { title: "Thực thể âm thanh vỡ nát", tag: "Sóng âm", color: "text-teal-500" },
  { title: "Kẻ điều khiển thực vật dị biến", tag: "Thiên nhiên", color: "text-green-600" },
  { title: "Người sở hữu hơi thở băng giá", tag: "Hàn băng", color: "text-blue-100" },
  { title: "Thực thể dâm dục cổ xưa (Incubus)", tag: "Dâm mị", color: "text-pink-500" },
  { title: "Kẻ nắm giữ quy luật cái chết", tag: "Tử thần", color: "text-gray-800" },
  { title: "Dị nhân có khả năng đọc suy nghĩ", tag: "Thấu thị", color: "text-cyan-300" },
  { title: "Thực thể tan biến trong mưa", tag: "Thủy thể", color: "text-sky-600" },
  { title: "Kẻ điều khiển rối linh hồn", tag: "Thao túng", color: "text-purple-800" },
  { title: "Dị nhân hấp thụ nỗi sợ", tag: "Cực đoan", color: "text-red-900" },
  { title: "Người có đôi cánh thủy tinh", tag: "Hoa lệ", color: "text-white" },
  { title: "Thực thể mang năng lượng hạt nhân", tag: "Hủy diệt", color: "text-yellow-600" },
  { title: "Kẻ trộm năng lực dị nhân", tag: "Gian xảo", color: "text-amber-500" },
  { title: "Người điều khiển tơ nhện ma pháp", tag: "Trói buộc", color: "text-rose-400" },
  { title: "Thực thể bóng tối nghìn năm", tag: "Cổ xưa", color: "text-stone-900" },
  { title: "Dị nhân tạo ra trọng lực đen", tag: "Vật lý", color: "text-indigo-900" },
  { title: "Người sở hữu tiếng thét sấm sét", tag: "Âm thanh", color: "text-yellow-400" },
  { title: "Thực thể cộng sinh ma quỷ", tag: "Hỗn hợp", color: "text-red-700" },
  { title: "Kẻ nắm giữ bản đồ đa vũ trụ", tag: "Tối thượng", color: "text-cyan-400" },
  { title: "Dị nhân điều khiển mực vạn năng", tag: "Nghệ thuật", color: "text-black" },
  { title: "Người rồng cuồng bạo", tag: "Dã tính", color: "text-orange-800" },
  { title: "Thực thể ánh sáng chữa lành", tag: "Thần y", color: "text-emerald-400" },
  { title: "Kẻ điều khiển bầy dơi huyết tộc", tag: "Huyết tháp", color: "text-rose-900" },
  { title: "Dị nhân có làn da kim cương", tag: "Phòng thủ", color: "text-blue-200" },
  { title: "Người tạo ra các vùng không gian ảo", tag: "Ảo ảnh", color: "text-violet-500" },
  { title: "Thực thể tan chảy trong bóng tối", tag: "Ẩn danh", color: "text-neutral-900" },
  { title: "Kẻ điều khiển các giấc mơ ác mộng", tag: "Tâm lý", color: "text-purple-700" },
  { title: "Dị nhân hệ mộc xanh tươi", tag: "Sự sống", color: "text-green-500" },
  { title: "Người có khả năng phân thân vô hạn", tag: "Số lượng", color: "text-cyan-500" },
  { title: "Thực thể mang linh hồn máy móc", tag: "AI_Core", color: "text-slate-500" },
  { title: "Kẻ săn lùng các dị vật", tag: "Sưu tầm", color: "text-amber-700" },
  { title: "Dị nhân điều khiển các dòng điện", tag: "Năng lượng", color: "text-yellow-300" },
  { title: "Người sở hữu đôi mắt âm dương", tag: "Tâm linh", color: "text-indigo-500" },
  { title: "Thực thể bão tố cuồng phong", tag: "Nguyên tố", color: "text-sky-500" },
  { title: "Kẻ tạo ra các vụ nổ linh hồn", tag: "Tàn nhẫn", color: "text-red-600" },
  { title: "Dị nhân có khả năng bay lượn", tag: "Không trung", color: "text-blue-400" },
  { title: "Người điều khiển các chất độc", tag: "Ám sát", color: "text-lime-700" },
  { title: "Thực thể mang sức mạnh cổ thần", tag: "Vô hạn", color: "text-yellow-700" },
  { title: "Kẻ nắm giữ mật mã thức tỉnh", tag: "Sứ mệnh", color: "text-emerald-600" },
  { title: "Dị nhân hệ thổ kiên cố", tag: "Phòng ngự", color: "text-stone-600" },
  { title: "Người tạo ra các sợi dây ma pháp", tag: "Trói buộc", color: "text-indigo-400" },
  { title: "Thực thể tan biến trong ánh sáng", tag: "Thánh khiết", color: "text-amber-100" },
  { title: "Kẻ điều khiển các loài quái thú", tag: "Triệu hồi", color: "text-orange-600" },
  { title: "Dị nhân có khả năng đóng băng", tag: "Lạnh lẽo", color: "text-cyan-100" },
  { title: "Người sở hữu trái tim máy", tag: "Vô cảm", color: "text-slate-700" },
  { title: "Thực thể bóng đêm vĩnh hằng", tag: "Diệt vong", color: "text-black" },
  { title: "Kẻ nắm giữ chìa khóa vạn giới", tag: "Tối thượng", color: "text-purple-900" },
  { title: "Dị nhân có đôi mắt laser", tag: "Công phá", color: "text-red-500" },
  { title: "Người điều khiển các tia hạt", tag: "Vật lý", color: "text-indigo-300" },
  { title: "Thực thể mang năng lượng mặt trời", tag: "Rực rỡ", color: "text-orange-500" },
  { title: "Kẻ điều khiển các mảng thực tại", tag: "Vạn năng", color: "text-fuchsia-600" },
  { title: "Dị nhân hệ không khí mỏng manh", tag: "Tự do", color: "text-sky-200" },
  { title: "Người tạo ra các vụ nổ ánh sáng", tag: "Chói lòa", color: "text-yellow-200" },
  { title: "Thực thể mang linh hồn rồng thần", tag: "Long kỵ", color: "text-red-400" },
  { title: "Kẻ nắm giữ quy luật vạn vật", tag: "Chúa tể", color: "text-emerald-900" },
  { title: "Thiên sứ sa ngã đen tối", tag: "Ánh sáng", color: "text-slate-800" },
  { title: "Thực thể nham thạch nóng bỏng", tag: "Hỏa diệm", color: "text-red-500" },
  { title: "Kẻ điều khiển bầy rắn ma pháp", tag: "Độc đạo", color: "text-lime-600" },
  { title: "Thực thể mang năng lượng sao băng", tag: "Rực rỡ", color: "text-blue-100" },
  { title: "Người sở hữu đôi mắt nhìn thấu", tag: "Trí tuệ", color: "text-cyan-400" },
  { title: "Kẻ nắm giữ bản đồ vạn giới ngầm", tag: "Mạo hiểm", color: "text-orange-500" },
  { title: "Thực thể mang linh hồn đại dương", tag: "Thủy vương", color: "text-blue-700" },
  { title: "Người sở hữu đôi tai Elf nhọn", tag: "Thanh cao", color: "text-green-300" },
  { title: "Kẻ triệu hồi quái vật vực thẳm", tag: "Hủy diệt", color: "text-black" },
  { title: "Thực thể tan chảy trong lửa", tag: "Vĩnh hằng", color: "text-red-400" },
  { title: "Người sở hữu làn da ngọc thạch", tag: "Phòng thủ", color: "text-emerald-100" },
  { title: "Kẻ săn lùng các mảnh vỡ hư không", tag: "Cấm thuật", color: "text-purple-800" },
  { title: "Thực thể tan biến trong mây", tag: "Tự do", color: "text-blue-100" },
  { title: "Người sở hữu đôi cánh thiên thần", tag: "Thánh khiết", color: "text-amber-100" },
  { title: "Kẻ điều khiển các mảng bóng tối", tag: "Hắc ám", color: "text-black" },
  { title: "Thực thể mang linh hồn vĩnh cửu", tag: "Bất tử", color: "text-indigo-800" },
  { title: "Người sở hữu đôi cánh dơi", tag: "Bóng tối", color: "text-slate-900" },
  { title: "Kẻ nắm giữ chìa khóa thiên đình", tag: "Tối thượng", color: "text-yellow-700" },
  { title: "Thực thể mang năng lượng tinh tú", tag: "Hoa lệ", color: "text-white" },
  { title: "Người biến hình thành quái thú", tag: "Dã tính", color: "text-orange-900" },
  { title: "Kẻ điều khiển bầy ong linh năng", tag: "Dịch bệnh", color: "text-yellow-600" },
  { title: "Thực thể mang sức mạnh bão lốc", tag: "Hủy diệt", color: "text-sky-600" },
  { title: "Người sở hữu tiếng nói của rồng", tag: "Long ngữ", color: "text-orange-300" },
  { title: "Kẻ nắm giữ bí mật rồng thần", tag: "Sứ mệnh", color: "text-red-500" },
  { title: "Thực thể tan chảy trong mưa", tag: "Thủy thể", color: "text-sky-600" },
  { title: "Kẻ điều khiển các mảng thực tại ảo", tag: "Digital", color: "text-cyan-700" },
  { title: "Dị nhân mang dòng máu rồng", tag: "Huyết thống", color: "text-rose-700" },
  { title: "Thực thể mang sức mạnh khởi nguyên", tag: "Sáng thế", color: "text-emerald-900" },
  { title: "Kẻ nắm giữ bản đồ đa vũ trụ vĩ đại", tag: "Tối thượng", color: "text-indigo-800" },
  { title: "Dị nhân điều khiển các tia hạt", tag: "Vật lý", color: "text-indigo-300" },
  { title: "Thực thể mang linh hồn của rừng", tag: "Sự sống", color: "text-green-500" },
  { title: "Kẻ săn lùng các mỹ nhân vạn tộc", tag: "Harem", color: "text-pink-500" },
  { title: "Người sở hữu đôi mắt laser đỏ", tag: "Công phá", color: "text-red-500" },
  { title: "Dị nhân hệ không khí mỏng manh", tag: "Tự do", color: "text-sky-200" },
  { title: "Thực thể mang năng lượng sấm sét", tag: "Công phá", color: "text-yellow-400" },
  { title: "Kẻ điều phối các trận đấu ngầm S", tag: "Cá cược", color: "text-orange-600" },
  { title: "Dị nhân có khả năng đọc suy nghĩ S", tag: "Thấu thị", color: "text-cyan-300" },
  { title: "Thực thể bóng đêm vĩnh hằng S", tag: "Diệt vong", color: "text-black" },
  { title: "Người tạo ra các ảo ảnh mê hoặc", tag: "Dâm mị", color: "text-pink-500" },
  { title: "Dị nhân hệ thổ kiên cố S", tag: "Phòng ngự", color: "text-stone-600" },
  { title: "Thực thể ánh sáng hủy diệt S", tag: "Phát quang", color: "text-yellow-200" },
  { title: "Kẻ điều khiển các chất độc đô thị S", tag: "Ám sát", color: "text-lime-600" },
  { title: "Dị nhân lôi hệ tốc độ cao S", tag: "Sấm sét", color: "text-yellow-300" },
  { title: "Thực thể mang năng lượng mặt trời S", tag: "Rực rỡ", color: "text-orange-500" },
  { title: "Kẻ nắm giữ mật mã hạt nhân S", tag: "Hủy diệt", color: "text-orange-900" },
  { title: "Dị nhân hệ mộc xanh tươi S", tag: "Sự sống", color: "text-green-500" },
  { title: "Thực thể mang linh hồn rồng thần S", tag: "Long kỵ", color: "text-red-400" },
  { title: "Kẻ mở cổng không gian trái phép S", tag: "Vượt biên", color: "text-sky-400" },
  { title: "Dị nhân điều khiển các dòng điện S", tag: "Năng lượng", color: "text-yellow-300" },
  { title: "Thực thể tan chảy trong bóng tối S", tag: "Ẩn danh", color: "text-neutral-900" },
  { title: "Kẻ nắm giữ quy luật cái chết S", tag: "Tử thần", color: "text-gray-800" },
  { title: "Dị nhân sở hữu hơi thở băng giá S", tag: "Hàn băng", color: "text-blue-100" },
  { title: "Thực thể bão tố cuồng phong S", tag: "Nguyên tố", color: "text-sky-500" },
  { title: "Kẻ điều khiển bầy côn trùng S", tag: "Dịch bệnh", color: "text-lime-600" },
  { title: "Dị nhân có làn da kim cương S", tag: "Phòng thủ", color: "text-blue-200" },
  { title: "Thực thể trọng lực tàn nhẫn S", tag: "Vật lý", color: "text-slate-600" },
  { title: "Kẻ tạo ra các ảo mộng dâm dục S", tag: "Ảo giác", color: "text-pink-500" },
  { title: "Dị nhân có đôi mắt laser S", tag: "Công phá", color: "text-red-500" },
  { title: "Thực thể mang sức mạnh cổ thần S", tag: "Vô hạn", color: "text-yellow-700" },
  { title: "Kẻ nắm giữ chìa khóa vạn giới S", tag: "Tối thượng", color: "text-purple-900" },
  { title: "Dị nhân điều khiển mực vạn năng S", tag: "Nghệ thuật", color: "text-black" },
  { title: "Thực thể ánh sáng thuần khiết S", tag: "Thánh khiết", color: "text-white" },
  { title: "Kẻ buôn bán dị năng S", tag: "Thương nhân", color: "text-yellow-600" },
  { title: "Dị nhân điều khiển thời gian S", tag: "Thời gian", color: "text-indigo-600" },
  { title: "Thực thể âm nhạc chết chóc S", tag: "Âm thanh", color: "text-teal-400" },
  { title: "Kẻ sở hữu mắt thần S", tag: "Nhìn thấu", color: "text-cyan-600" },
  { title: "Dị nhân biến hình vạn năng S", tag: "Ngụy trang", color: "text-zinc-500" },
  { title: "Thực thể hư không hóa hình S", tag: "Cấm kỵ", color: "text-purple-500" },
  { title: "Kẻ mang mầm bệnh dị năng S", tag: "Nguy hiểm", color: "text-emerald-500" },
  { title: "Dị nhân hacker ma mạng S", tag: "Công nghệ", color: "text-cyan-500" },
  { title: "Thực thể người máy có linh hồn S", tag: "Cơ khí", color: "text-slate-400" },
  { title: "Kẻ đi xuyên gương S", tag: "Không gian", color: "text-blue-300" },
  { title: "Dị nhân hệ hỏa cuồng bạo S", tag: "Hủy diệt", color: "text-red-600" },
  { title: "Thực thể ký sinh mỹ nhân S", tag: "Chiếm hữu", color: "text-rose-500" },
  { title: "Kẻ thu thập linh hồn phố đêm S", tag: "Bóng tối", color: "text-neutral-700" },
  { title: "Dị nhân chiến binh nano S", tag: "Vũ khí", color: "text-cyan-300" },
  { title: "Thực thể người cá sống hồ bơi S", tag: "Thủy tộc", color: "text-sky-400" },
  { title: "Kẻ tạo ra ảo mộng dâm dục SSS", tag: "Ảo giác", color: "text-pink-500" },
  { title: "Vị vua cuối cùng của Dị Biến", tag: "Vĩnh hằng", color: "text-yellow-500" }
];