export const CUSTOM_CULTIVATION = [
  { title: "Lão tổ đoạt xá phế vật", tag: "Trùng sinh", color: "text-red-400" },
  { title: "Kiếm linh hóa hình", tag: "Yêu tộc", color: "text-cyan-300" },
  { title: "Tán tiên mất đi tu vi", tag: "Ẩn dật", color: "text-neutral-400" },
  { title: "Đứa con của Thiên Đạo", tag: "Khí vận", color: "text-yellow-400" },
  { title: "Ma tôn chuyển thế", tag: "Ma đạo", color: "text-purple-500" },
  { title: "Dục tu lang thang", tag: "Song tu", color: "text-pink-400" },
  { title: "Đan thần thất lạc", tag: "Luyện dược", color: "text-emerald-500" },
  { title: "Kiếm tu nhất niệm trảm thiên", tag: "Kiếm đạo", color: "text-white" },
  { title: "Tạp dịch mang hệ thống", tag: "Nghịch tập", color: "text-blue-400" },
  { title: "Yêu đế thức tỉnh", tag: "Thống trị", color: "text-orange-500" },
  { title: "Trận pháp sư thiên tài", tag: "Mưu lược", color: "text-cyan-500" },
  { title: "Phù sư bách biến", tag: "Hỗ trợ", color: "text-yellow-300" },
  { title: "Tu sĩ khổ hạnh", tag: "Nhẫn nhục", color: "text-stone-500" },
  { title: "Thánh tử thánh địa sa đọa", tag: "Phản phái", color: "text-red-600" },
  { title: "Linh thú sư vạn dặm", tag: "Triệu hồi", color: "text-green-500" },
  { title: "Kẻ canh giữ tàng thư các", tag: "Tri thức", color: "text-amber-600" },
  { title: "Chưởng môn trẻ nhất lịch sử", tag: "Lãnh đạo", color: "text-indigo-500" },
  { title: "Tu sĩ cầm kỳ thi họa", tag: "Văn nhã", color: "text-rose-300" },
  { title: "Ma tu dâm đãng", tag: "Tà ác", color: "text-fuchsia-600" },
  { title: "Phật tu nhập ma", tag: "Nghịch lý", color: "text-slate-600" },
  { title: "Kẻ đi tìm đại đạo trường sinh", tag: "Lý tưởng", color: "text-cyan-200" },
  { title: "Thiên kiêu bị phế bỏ", tag: "Báo thù", color: "text-red-700" },
  { title: "Tán tu may mắn cực hạn", tag: "Khí vận", color: "text-yellow-200" },
  { title: "Dược đồng của tiên tử", tag: "Harem", color: "text-pink-300" },
  { title: "Vương tử của linh triều", tag: "Vương quyền", color: "text-yellow-600" },
  { title: "Kẻ đào ngũ của thần quân", tag: "Tự do", color: "text-teal-300" },
  { title: "Linh hồn xuyên không", tag: "Bí ẩn", color: "text-indigo-300" },
  { title: "Thần tướng hạ giới", tag: "Chiến tranh", color: "text-red-500" },
  { title: "Kẻ canh giữ long mạch", tag: "Trấn thủ", color: "text-amber-400" },
  { title: "Tu sĩ âm dương đạo", tag: "Cân bằng", color: "text-zinc-400" },
  { title: "Ma nữ hóa thân nam", tag: "Giả dạng", color: "text-pink-600" },
  { title: "Kẻ lấy cắp khí vận", tag: "Phản phái", color: "text-rose-500" },
  { title: "Luyện khí sư điên cuồng", tag: "Chế tác", color: "text-orange-400" },
  { title: "Yêu linh chuyển thế làm người", tag: "Dị tộc", color: "text-green-300" },
  { title: "Tu sĩ mù nhìn thấu thiên cơ", tag: "Tiên tri", color: "text-sky-200" },
  { title: "Đứa trẻ bị bỏ rơi trong ma động", tag: "Nghịch thiên", color: "text-purple-700" },
  { title: "Kiếm thánh què chân", tag: "Ẩn tàng", color: "text-neutral-500" },
  { title: "Kẻ buôn bán linh đan lậu", tag: "Thương nhân", color: "text-yellow-500" },
  { title: "Hậu duệ rồng cuối cùng", tag: "Huyết mạch", color: "text-red-500" },
  { title: "Tu sĩ tu luyện công pháp dâm dục", tag: "Hợp hoan", color: "text-fuchsia-400" },
  { title: "Kẻ canh giữ cổng địa ngục tiên giới", tag: "Trấn thủ", color: "text-indigo-900" },
  { title: "Tán tu sở hữu không gian linh điền", tag: "Tài nguyên", color: "text-emerald-300" },
  { title: "Ma tôn bị phong ấn trong nhẫn", tag: "Sư phụ", color: "text-slate-400" },
  { title: "Thần y tu tiên cứu vãn hồng trần", tag: "Y thuật", color: "text-teal-300" },
  { title: "Kẻ đi tìm mảnh vỡ thiên giới", tag: "Sứ mệnh", color: "text-yellow-100" },
  { title: "Tu sĩ phàm nhân nghịch tập", tag: "Ý chí", color: "text-stone-300" },
  { title: "Đứa con của ác ma và thiên thần", tag: "Hỗn huyết", color: "text-neutral-100" },
  { title: "Lão quái vật thích giả làm heo ăn hổ", tag: "Vô sỉ", color: "text-amber-500" },
  { title: "Tu sĩ điều khiển rối linh hồn", tag: "Tà thuật", color: "text-gray-600" },
  { title: "Kẻ nắm giữ mật mã trường sinh", tag: "Tối thượng", color: "text-yellow-600" },
  { title: "Thần thú hóa hình làm tiểu thư sinh", tag: "Yêu tộc", color: "text-orange-200" },
  { title: "Tu sĩ tu luyện Thái Âm công pháp", tag: "Âm nhu", color: "text-blue-300" },
  { title: "Kiếm tu mang huyết mạch phượng hoàng", tag: "Niết bàn", color: "text-orange-500" },
  { title: "Trận pháp sư dùng máu làm trận", tag: "Huyết trận", color: "text-red-800" },
  { title: "Tử tu chuyên luyện thi cốt", tag: "Tà môn", color: "text-neutral-700" },
  { title: "Lôi tu nghịch thiên độ kiếp", tag: "Cuồng bạo", color: "text-yellow-400" },
  { title: "Tu sĩ mang linh hồn kiếm tiên", tag: "Kiếm hồn", color: "text-white" },
  { title: "Yêu tộc hoàng tử bị trục xuất", tag: "Lưu vong", color: "text-green-600" },
  { title: "Tu sĩ điều khiển vạn quỷ", tag: "Quỷ đạo", color: "text-zinc-900" },
  { title: "Đan sư dùng cơ thể luyện thuốc", tag: "Điên cuồng", color: "text-emerald-600" },
  { title: "Tu sĩ sở hữu không gian tàng bảo", tag: "Phú gia", color: "text-yellow-500" },
  { title: "Kiếm khách mang sẹo lớn trên mặt", tag: "Lạnh lùng", color: "text-slate-500" },
  { title: "Tu sĩ tu luyện đạo của gió", tag: "Tự do", color: "text-sky-300" },
  { title: "Ma nữ sở hữu đôi mắt mị hoặc", tag: "Dâm mị", color: "text-pink-500" },
  { title: "Tu sĩ nhặt được mảnh vỡ thần giới", tag: "Bảo vật", color: "text-cyan-400" },
  { title: "Hắc thủ đứng sau vạn vật", tag: "Thao túng", color: "text-black" },
  { title: "Tu sĩ có thể giao tiếp với đá", tag: "Kỳ dị", color: "text-stone-400" },
  { title: "Yêu hồ chín đuôi hóa hình", tag: "Quyến rũ", color: "text-rose-400" },
  { title: "Tu sĩ dùng nhạc làm vũ khí", tag: "Nghệ sĩ", color: "text-indigo-400" },
  { title: "Kiếm tu tu luyện đạo của bóng tối", tag: "Hắc ám", color: "text-neutral-800" },
  { title: "Tu sĩ nhặt được bút thần vẽ thực", tag: "Họa thánh", color: "text-blue-500" },
  { title: "Yêu đế chuyển sinh làm mèo nhỏ", tag: "Đáng yêu", color: "text-orange-300" },
  { title: "Tu sĩ tu luyện đạo của lửa vĩnh hằng", tag: "Hỏa thần", color: "text-red-500" },
  { title: "Tán tu sở hữu kỹ năng ăn cắp linh lực", tag: "Gian tà", color: "text-teal-700" },
  { title: "Tu sĩ mù mang đôi tai thần", tag: "Thính nhạy", color: "text-stone-300" },
  { title: "Kiếm tu mang theo thanh kiếm gỉ sét", tag: "Ẩn tàng", color: "text-neutral-400" },
  { title: "Tu sĩ sở hữu trái tim của rồng", tag: "Long huyết", color: "text-red-600" },
  { title: "Ma tu tu luyện đạo của sự đau đớn", tag: "Cuồng nhiết", color: "text-rose-800" },
  { title: "Tu sĩ có khả năng quay ngược thời gian", tag: "Thời không", color: "text-indigo-500" },
  { title: "Yêu tộc chiến thần bị phong ấn", tag: "Dũng mãnh", color: "text-orange-700" },
  { title: "Tu sĩ dùng kim châm cứu nhân độ thế", tag: "Thần y", color: "text-emerald-300" },
  { title: "Kiếm tu tu luyện đạo của sự tĩnh lặng", tag: "Vô ngã", color: "text-white" },
  { title: "Tu sĩ nhặt được hộp Pandora tiên giới", tag: "Nguy hiểm", color: "text-red-700" },
  { title: "Ma nữ mang theo đóa hoa bỉ ngạn", tag: "Tử vong", color: "text-rose-900" },
  { title: "Tu sĩ tu luyện đạo của sấm sét tím", tag: "Hủy diệt", color: "text-purple-600" },
  { title: "Yêu linh nhát gan mang sức mạnh lớn", tag: "Mâu thuẫn", color: "text-green-200" },
  { title: "Tu sĩ sở hữu kỹ năng thôi miên vạn vật", tag: "Thao túng", color: "text-violet-500" },
  { title: "Kiếm tu mang theo linh hồn của người yêu", tag: "Tình si", color: "text-pink-200" },
  { title: "Tu sĩ nhặt được chiếc nhẫn ma quái", tag: "Bị nguyền", color: "text-stone-900" },
  { title: "Tán tu sở hữu kỹ năng biến hình", tag: "Ngụy trang", color: "text-cyan-600" },
  { title: "Tu sĩ tu luyện đạo của sự hỗn độn", tag: "Vô định", color: "text-neutral-500" },
  { title: "Yêu tộc nữ vương bị phản bội", tag: "Báo thù", color: "text-red-400" },
  { title: "Tu sĩ dùng tơ nhện trói buộc linh hồn", tag: "Giam cầm", color: "text-indigo-700" },
  { title: "Kiếm tu tu luyện đạo của sự tan biến", tag: "Hư không", color: "text-slate-300" },
  { title: "Tu sĩ nhặt được bản đồ vạn giới", tag: "Khám phá", color: "text-yellow-600" },
  { title: "Ma tôn bị biến thành trẻ nhỏ", tag: "Trùng sinh", color: "text-purple-300" },
  { title: "Tu sĩ tu luyện đạo của nước tinh khiết", tag: "Thủy thần", color: "text-sky-400" },
  { title: "Yêu linh sở hữu kỹ năng gieo mầm dâm", tag: "Kích dục", color: "text-pink-600" },
  { title: "Tu sĩ mang theo gánh nặng của gia tộc", tag: "Trách nhiệm", color: "text-amber-700" },
  { title: "Kiếm tu tu luyện đạo của sự rực rỡ", tag: "Quang thần", color: "text-yellow-200" },
  { title: "Tu sĩ nhặt được trái tim của thần hợi", tag: "Sáng thế", color: "text-emerald-900" },
  { title: "Thực thể hư không tu hành", tag: "Cấm kỵ", color: "text-purple-400" },
  { title: "Kiếm khách sở hữu thanh gươm gãy", tag: "Ẩn danh", color: "text-neutral-400" },
  { title: "Phù sư chuyên vẽ bùa yêu", tag: "Dục vọng", color: "text-pink-500" },
  { title: "Trận pháp sư tạo mê cung sắc dục", tag: "Ảo mộng", color: "text-rose-400" },
  { title: "Linh thú sư thu phục mỹ nhân ngư", tag: "Dị chủng", color: "text-sky-400" },
  { title: "Tu sĩ mù sở hữu thiên nhãn", tag: "Nhìn thấu", color: "text-white" },
  { title: "Ma tu tu luyện bằng sự oán hận", tag: "Báo thù", color: "text-red-900" },
  { title: "Y sư chuyên trị bệnh tâm linh", tag: "Bí mật", color: "text-indigo-300" },
  { title: "Tu sĩ nhặt được viên đá thời gian", tag: "Cơ duyên", color: "text-cyan-500" },
  { title: "Kẻ lãng du tìm kiếm thánh địa", tag: "Khám phá", color: "text-yellow-500" },
  { title: "Đan sư luyện ra đan dược biến hình", tag: "Kỳ ảo", color: "text-emerald-400" },
  { title: "Tu sĩ tu luyện đạo của âm thanh", tag: "Nghệ sĩ", color: "text-teal-400" },
  { title: "Kiếm tu sở hữu kiếm khí vô hình", tag: "Sát thủ", color: "text-zinc-500" },
  { title: "Ma nữ mang dòng máu thần linh", tag: "Nghịch lý", color: "text-amber-400" },
  { title: "Tu sĩ nhặt được bộ giáp nano cổ", tag: "Cyborg", color: "text-slate-400" },
  { title: "Trận pháp sư điều khiển trọng lực", tag: "Vật lý", color: "text-blue-800" },
  { title: "Tu sĩ tu luyện đạo của cái chết", tag: "Tử thần", color: "text-black" },
  { title: "Yêu tộc nữ vương bị xích chân", tag: "Nô lệ", color: "text-red-700" },
  { title: "Tu sĩ nhặt được chiếc nhẫn ma quái S", tag: "Bị nguyền", color: "text-stone-800" },
  { title: "Ma tu sở hữu kỹ năng thôi miên S", tag: "Thao túng", color: "text-purple-700" },
  { title: "Tu sĩ tu luyện đạo của gió S", tag: "Tự do", color: "text-sky-200" },
  { title: "Kiếm tu mang theo linh hồn người yêu S", tag: "Tình si", color: "text-pink-100" },
  { title: "Tu sĩ nhặt được trái tim thần hợi S", tag: "Sáng thế", color: "text-emerald-800" },
  { title: "Phù sư bách biến S", tag: "Hỗ trợ", color: "text-yellow-200" },
  { title: "Tu sĩ khổ hạnh S", tag: "Nhẫn nhục", color: "text-stone-400" },
  { title: "Linh thú sư vạn dặm S", tag: "Triệu hồi", color: "text-green-600" },
  { title: "Kẻ canh giữ tàng thư các S", tag: "Tri thức", color: "text-amber-500" },
  { title: "Chưởng môn trẻ nhất S", tag: "Lãnh đạo", color: "text-indigo-400" },
  { title: "Tu sĩ cầm kỳ thi họa S", tag: "Văn nhã", color: "text-rose-200" },
  { title: "Ma tu dâm đãng S", tag: "Tà ác", color: "text-fuchsia-500" },
  { title: "Phật tu nhập ma S", tag: "Nghịch lý", color: "text-slate-500" },
  { title: "Thiên kiêu bị phế bỏ S", tag: "Báo thù", color: "text-red-600" },
  { title: "Tán tu may mắn cực hạn S", tag: "Khí vận", color: "text-yellow-100" },
  { title: "Vương tử của linh triều S", tag: "Vương quyền", color: "text-yellow-500" },
  { title: "Kẻ đào ngũ của thần quân S", tag: "Tự do", color: "text-teal-200" },
  { title: "Linh hồn xuyên không S", tag: "Bí ẩn", color: "text-indigo-200" },
  { title: "Thần tướng hạ giới S", tag: "Chiến tranh", color: "text-red-400" },
  { title: "Kẻ canh giữ long mạch S", tag: "Trấn thủ", color: "text-amber-300" },
  { title: "Tu sĩ âm dương đạo S", tag: "Cân bằng", color: "text-zinc-300" },
  { title: "Ma nữ hóa thân nam S", tag: "Giả dạng", color: "text-pink-500" },
  { title: "Kẻ lấy cắp khí vận S", tag: "Phản phái", color: "text-rose-400" },
  { title: "Luyện khí sư điên cuồng S", tag: "Chế tác", color: "text-orange-300" },
  { title: "Yêu linh chuyển thế làm người S", tag: "Dị tộc", color: "text-green-200" },
  { title: "Tu sĩ mù nhìn thấu thiên cơ S", tag: "Tiên tri", color: "text-sky-100" },
  { title: "Đứa trẻ bị bỏ rơi ma động S", tag: "Nghịch thiên", color: "text-purple-600" },
  { title: "Kiếm thánh què chân S", tag: "Ẩn tàng", color: "text-neutral-400" },
  { title: "Kẻ buôn bán linh đan lậu S", tag: "Thương nhân", color: "text-yellow-400" },
  { title: "Hậu duệ rồng cuối cùng S", tag: "Huyết mạch", color: "text-red-400" },
  { title: "Tu sĩ tu luyện dâm dục S", tag: "Hợp hoan", color: "text-fuchsia-300" },
  { title: "Tán tu sở hữu linh điền S", tag: "Tài nguyên", color: "text-emerald-200" },
  { title: "Ma tôn phong ấn trong nhẫn S", tag: "Sư phụ", color: "text-slate-300" },
  { title: "Thần y tu tiên cứu hồng trần S", tag: "Y thuật", color: "text-teal-200" },
  { title: "Kẻ đi tìm mảnh vỡ thiên giới S", tag: "Sứ mệnh", color: "text-yellow-50" },
  { title: "Tu sĩ phàm nhân nghịch tập S", tag: "Ý chí", color: "text-stone-200" },
  { title: "Đứa con ác ma thiên thần S", tag: "Hỗn huyết", color: "text-neutral-50" },
  { title: "Lão quái vật giả heo ăn hổ S", tag: "Vô sỉ", color: "text-amber-400" },
  { title: "Tu sĩ điều khiển rối linh hồn S", tag: "Tà thuật", color: "text-gray-500" },
  { title: "Kẻ nắm giữ mật mã trường sinh S", tag: "Tối thượng", color: "text-yellow-500" },
  { title: "Thần thú hóa tiểu thư sinh S", tag: "Yêu tộc", color: "text-orange-100" },
  { title: "Vị vua cuối cùng của Tu Tiên", tag: "Vĩnh hằng", color: "text-yellow-500" }
];