export const CUSTOM_FANTASY_MULTI = [
  { title: "Bán nhân tộc bị ruồng bỏ", tag: "Huyết thống", color: "text-neutral-500" },
  { title: "Long nhân cuối cùng", tag: "Tuyệt chủng", color: "text-red-400" },
  { title: "Thực thể tà thần hạ giới", tag: "Cực hạn", color: "text-rose-600" },
  { title: "Kẻ buôn linh hồn vạn tộc", tag: "Gian xảo", color: "text-indigo-600" },
  { title: "Hoàng tử Elf sa đọa", tag: "Kiêu kỳ", color: "text-green-400" },
  { title: "Chiến binh Orc trí tuệ", tag: "Nghịch lý", color: "text-orange-700" },
  { title: "Nữ vương bộ tộc Thú bị thuần hóa", tag: "Chinh phục", color: "text-pink-500" },
  { title: "Thiên sứ sa ngã đen tối", tag: "Ánh sáng", color: "text-slate-400" },
  { title: "Ma vương thức tỉnh trong xác người", tag: "Trùng sinh", color: "text-red-800" },
  { title: "Người lùn chế tạo thần binh", tag: "Kỹ nghệ", color: "text-amber-700" },
  { title: "Hồ ly tinh chín đuôi", tag: "Mê hoặc", color: "text-rose-400" },
  { title: "Ma cà rồng quý tộc", tag: "Huyết tộc", color: "text-red-600" },
  { title: "Người cá cai trị đại dương", tag: "Thủy tộc", color: "text-sky-500" },
  { title: "Thực thể hư không đói khát", tag: "Nuốt chửng", color: "text-purple-900" },
  { title: "Long kỵ sĩ của đế chế quỷ", tag: "Chiến tranh", color: "text-orange-600" },
  { title: "Thánh tử vạn tộc mang hệ thống", tag: "Nghịch tập", color: "text-cyan-400" },
  { title: "Kẻ canh giữ long mạch", tag: "Trấn thủ", color: "text-yellow-500" },
  { title: "Nhân sư (Sphinx) biết tuốt", tag: "Trí tuệ", color: "text-amber-400" },
  { title: "Cương thi tu tiên hiện đại", tag: "Dị chủng", color: "text-zinc-500" },
  { title: "Thực thể cây cổ thụ hóa hình", tag: "Thiên nhiên", color: "text-emerald-700" },
  { title: "Kẻ mang huyết mạch Sáng Thế", tag: "Thần thánh", color: "text-yellow-200" },
  { title: "Bóng ma trong gương", tag: "Ảo giác", color: "text-blue-200" },
  { title: "Kẻ điều khiển bầy côn trùng", tag: "Dịch bệnh", color: "text-lime-700" },
  { title: "Người khổng lồ tí hon", tag: "Sức mạnh", color: "text-orange-400" },
  { title: "Tinh linh ánh sáng dâm đãng", tag: "Harem", color: "text-white" },
  { title: "Kẻ buôn nô lệ vạn tộc", tag: "Tàn nhẫn", color: "text-neutral-800" },
  { title: "Thầy cúng của bộ lạc rồng", tag: "Tôn giáo", color: "text-red-500" },
  { title: "Đao phủ của vương quốc Elf", tag: "Sát khí", color: "text-green-700" },
  { title: "Kẻ đào ngũ của liên minh thánh", tag: "Tự do", color: "text-sky-300" },
  { title: "Linh hồn chuyển sinh vào quỷ", tag: "Bí ẩn", color: "text-purple-400" },
  { title: "Thực thể mang năng lượng rồng", tag: "Long kỵ", color: "text-orange-300" },
  { title: "Tiên nữ bị giam cầm trong kiếm", tag: "Kiếm linh", color: "text-cyan-100" },
  { title: "Orc chúa tể sa mạc", tag: "Cường bạo", color: "text-red-900" },
  { title: "Tộc nhân Lùn phát minh súng ống", tag: "Kỹ thuật", color: "text-amber-500" },
  { title: "Bóng đen cai trị cõi chết", tag: "Lich", color: "text-indigo-800" },
  { title: "Người thằn lằn sa lầy", tag: "Đầm lầy", color: "text-green-800" },
  { title: "Tinh linh gió lãng du", tag: "Tự do", color: "text-sky-200" },
  { title: "Kẻ ăn cắp phép thuật vạn tộc", tag: "Ma đạo", color: "text-purple-500" },
  { title: "Bán quỷ mang trái tim người", tag: "Nội tâm", color: "text-rose-300" },
  { title: "Sát thủ tộc Mèo bóng đêm", tag: "Nhanh nhẹn", color: "text-zinc-800" },
  { title: "Người gác cổng vương quốc đá", tag: "Golems", color: "text-stone-600" },
  { title: "Thiên thần bị gãy cánh", tag: "Thương đau", color: "text-white" },
  { title: "Kẻ triệu hồi quái vật vực thẳm", tag: "Hủy diệt", color: "text-black" },
  { title: "Người lữ hành xuyên lục địa", tag: "Khám phá", color: "text-yellow-600" },
  { title: "Thực thể điều khiển lôi đình", tag: "Sấm sét", color: "text-yellow-400" },
  { title: "Nữ vương bộ tộc Nhện quyến rũ", tag: "Độc tố", color: "text-purple-600" },
  { title: "Kẻ săn lùng huyết mạch thần", tag: "Tham vọng", color: "text-red-700" },
  { title: "Người có khả năng biến hình vạn vật", tag: "Ngụy trang", color: "text-neutral-400" },
  { title: "Thực thể mang sức mạnh bão tố", tag: "Nguyên tố", color: "text-cyan-500" },
  { title: "Vua của những mạo hiểm giả", tag: "Huyền thoại", color: "text-amber-400" },
  { title: "Kẻ nắm giữ bản đồ vạn giới", tag: "Tối thượng", color: "text-indigo-700" },
  { title: "Thực thể nham thạch nóng bỏng", tag: "Hỏa diệm", color: "text-red-500" },
  { title: "Người sở hữu đôi cánh dơi", tag: "Bóng tối", color: "text-slate-900" },
  { title: "Yêu linh nhặt được đá khởi nguyên", tag: "May mắn", color: "text-emerald-300" },
  { title: "Bán nhân tộc mang linh hồn Elf", tag: "Thanh khiết", color: "text-green-200" },
  { title: "Kẻ điều khiển bầy rắn ma pháp", tag: "Độc đạo", color: "text-lime-600" },
  { title: "Thực thể mang năng lượng sao băng", tag: "Rực rỡ", color: "text-yellow-200" },
  { title: "Người sở hữu trái tim của băng", tag: "Lạnh lẽo", color: "text-sky-100" },
  { title: "Kẻ săn lùng các dị vật vạn tộc", tag: "Sưu tầm", color: "text-amber-500" },
  { title: "Yêu tộc nữ chiến binh dũng cảm", tag: "Chiến binh", color: "text-orange-500" },
  { title: "Thực thể mang linh hồn của thần", tag: "Vô hạn", color: "text-white" },
  { title: "Kẻ điều khiển các mảng thực tại", tag: "Chúa tể", color: "text-purple-900" },
  { title: "Người sở hữu đôi mắt âm dương", tag: "Tâm linh", color: "text-indigo-500" },
  { title: "Bán quỷ mang theo đóa hoa hồng", tag: "Dâm mị", color: "text-pink-500" },
  { title: "Thực thể tan biến trong mây", tag: "Tự do", color: "text-blue-100" },
  { title: "Kẻ nắm giữ bí mật rồng thần", tag: "Sứ mệnh", color: "text-red-600" },
  { title: "Yêu tộc hoàng tử bị lưu vong", tag: "Vương quyền", color: "text-yellow-600" },
  { title: "Thực thể mang sức mạnh bão lốc", tag: "Hủy diệt", color: "text-sky-600" },
  { title: "Kẻ điều khiển bầy chim ma pháp", tag: "Thông tin", color: "text-cyan-500" },
  { title: "Người sở hữu làn da ngọc thạch", tag: "Phòng thủ", color: "text-emerald-100" },
  { title: "Bán nhân tộc mang linh hồn thú", tag: "Dã tính", color: "text-orange-700" },
  { title: "Thực thể mang năng lượng mặt trăng", tag: "Bí ẩn", color: "text-indigo-200" },
  { title: "Kẻ săn lùng các mảnh vỡ hư không", tag: "Cấm thuật", color: "text-purple-800" },
  { title: "Yêu tộc nữ vương bị xích chân", tag: "Nô lệ", color: "text-red-700" },
  { title: "Thực thể tan chảy trong lửa", tag: "Vĩnh hằng", color: "text-red-400" },
  { title: "Người sở hữu đôi tai Elf nhọn", tag: "Thanh cao", color: "text-green-300" },
  { title: "Kẻ điều khiển bầy cá đại dương", tag: "Thủy thần", color: "text-blue-500" },
  { title: "Bán quỷ mang theo thanh ma kiếm", tag: "Sát khí", color: "text-neutral-900" },
  { title: "Thực thể mang linh hồn của rừng", tag: "Sự sống", color: "text-green-600" },
  { title: "Kẻ nắm giữ chìa khóa thiên đình", tag: "Tối thượng", color: "text-yellow-700" },
  { title: "Yêu tộc chiến thần mang sẹo lớn", tag: "Dũng mãnh", color: "text-orange-900" },
  { title: "Thực thể mang năng lượng sấm sét", tag: "Công phá", color: "text-yellow-400" },
  { title: "Người sở hữu trái tim máy móc", tag: "Cyborg", color: "text-slate-500" },
  { title: "Kẻ điều khiển bầy nhện hắc ám", tag: "Giam cầm", color: "text-purple-700" },
  { title: "Bán nhân tộc mang linh hồn rồng", tag: "Long huyết", color: "text-red-500" },
  { title: "Thực thể tan biến trong bụi trần", tag: "Ẩn danh", color: "text-stone-400" },
  { title: "Kẻ săn lùng các mỹ nhân vạn tộc", tag: "Harem", color: "text-pink-600" },
  { title: "Yêu tộc nữ phù thủy dâm đãng", tag: "Kích dục", color: "text-rose-500" },
  { title: "Thực thể mang sức mạnh khởi nguyên", tag: "Sáng thế", color: "text-emerald-900" },
  { title: "Người sở hữu đôi cánh thiên thần", tag: "Thánh khiết", color: "text-amber-100" },
  { title: "Kẻ nắm giữ bản đồ vạn giới ngầm", tag: "Mạo hiểm", color: "text-orange-500" },
  { title: "Bán quỷ mang theo linh hồn người", tag: "Mâu thuẫn", color: "text-blue-400" },
  { title: "Thực thể mang linh hồn vĩnh cửu", tag: "Bất tử", color: "text-indigo-800" },
  { title: "Kẻ điều khiển các mảng bóng tối", tag: "Hắc ám", color: "text-black" },
  { title: "Yêu tộc hoàng tử nhút nhát", tag: "Tiềm năng", color: "text-green-100" },
  { title: "Thực thể mang năng lượng tinh tú", tag: "Hoa lệ", color: "text-white" },
  { title: "Kẻ nắm giữ quy luật cái chết", tag: "Tử thần", color: "text-red-900" },
  { title: "Người sở hữu đôi mắt nhìn thấu", tag: "Trí tuệ", color: "text-cyan-400" },
  { title: "Bán nhân tộc mang sức mạnh rồng", tag: "Long kỵ", color: "text-red-400" },
  { title: "Thực thể mang linh hồn đại dương", tag: "Thủy vương", color: "text-blue-700" },
  { title: "Kẻ nắm giữ chìa khóa vạn giới", tag: "Chúa tể", color: "text-emerald-900" },
  { title: "Yêu tộc thủ lĩnh bộ lạc lửa", tag: "Hỏa hệ", color: "text-orange-500" },
  { title: "Thực thể mang linh hồn của đá", tag: "Kiên cố", color: "text-stone-500" },
  { title: "Người sở hữu đôi tai thú xù", tag: "Đáng yêu", color: "text-orange-200" },
  { title: "Bán nhân tộc mang linh hồn tiên", tag: "Thoát tục", color: "text-cyan-200" },
  { title: "Kẻ săn lùng huyết mạch Long Vương", tag: "Tham vọng", color: "text-red-800" },
  { title: "Thực thể mang năng lượng mây", tag: "Tự do", color: "text-blue-100" },
  { title: "Người sở hữu trái tim của gió", tag: "Bay bổng", color: "text-sky-300" },
  { title: "Bán nhân tộc mang linh hồn quỷ", tag: "Nghịch lý", color: "text-indigo-800" },
  { title: "Kẻ điều khiển bầy rắn ma pháp S", tag: "Độc đạo", color: "text-lime-500" },
  { title: "Thực thể mang năng lượng mặt trời S", tag: "Rực rỡ", color: "text-yellow-400" },
  { title: "Người sở hữu đôi mắt âm dương S", tag: "Tâm linh", color: "text-indigo-400" },
  { title: "Bán nhân tộc mang linh hồn rồng S", tag: "Long huyết", color: "text-red-400" },
  { title: "Kẻ nắm giữ bản đồ vạn giới S", tag: "Tối thượng", color: "text-indigo-700" },
  { title: "Thực thể mang sức mạnh khởi nguyên S", tag: "Sáng thế", color: "text-emerald-800" },
  { title: "Người sở hữu đôi cánh thiên thần S", tag: "Thánh khiết", color: "text-amber-50" },
  { title: "Bán nhân tộc mang sức mạnh rồng S", tag: "Long kỵ", color: "text-red-300" },
  { title: "Kẻ điều khiển bầy nhện hắc ám S", tag: "Giam cầm", color: "text-purple-600" },
  { title: "Thực thể mang linh hồn vĩnh cửu S", tag: "Bất tử", color: "text-indigo-600" },
  { title: "Người sở hữu trái tim máy móc S", tag: "Cyborg", color: "text-slate-400" },
  { title: "Bán nhân tộc mang linh hồn thú S", tag: "Dã tính", color: "text-orange-600" },
  { title: "Kẻ điều khiển bầy dơi huyết tộc S", tag: "Huyết tháp", color: "text-rose-800" },
  { title: "Thực thể mang năng lượng sấm sét S", tag: "Công phá", color: "text-yellow-300" },
  { title: "Người sở hữu đôi mắt nhìn thấu S", tag: "Trí tuệ", color: "text-cyan-300" },
  { title: "Bán nhân tộc mang sức mạnh Elf S", tag: "Thanh cao", color: "text-green-100" },
  { title: "Kẻ nắm giữ bí mật rồng thần S", tag: "Sứ mệnh", color: "text-red-400" },
  { title: "Thực thể mang sức mạnh bão lốc S", tag: "Hủy diệt", color: "text-sky-500" },
  { title: "Người sở hữu đôi tai Elf nhọn S", tag: "Thanh khiết", color: "text-green-50" },
  { title: "Bán nhân tộc mang linh hồn rồng SS", tag: "Long tộc", color: "text-red-200" },
  { title: "Kẻ nắm giữ chìa khóa vạn giới SS", tag: "Chúa tể", color: "text-emerald-700" },
  { title: "Vị vua cuối cùng của Vạn Tộc", tag: "Vĩnh hằng", color: "text-yellow-500" }
];