export const ABILITIES_DATA = [
  { title: "Không Gian - Thuấn Di", tag: "Di chuyển", color: "text-blue-400", desc: "Dịch chuyển tức thời đến địa điểm trong tầm mắt." },
  { title: "Thời Gian - Ngưng Đọng", tag: "Thời gian", color: "text-indigo-500", desc: "Dừng thời gian toàn thế giới trong 5 giây." },
  { title: "Tâm Linh - Thôi Miên", tag: "Thao túng", color: "text-purple-400", desc: "Ra lệnh cho đối phương thực hiện mọi hành vi." },
  { title: "Hỏa Hệ - Viêm Đế", tag: "Hủy diệt", color: "text-red-500", desc: "Điều khiển ngọn lửa xanh thiêu rụi cả linh hồn." },
  { title: "Lôi Hệ - Thiên Phạt", tag: "Sấm sét", color: "text-yellow-400", desc: "Triệu hồi sét đánh từ trời cao trừng phạt kẻ địch." },
  { title: "Dục Vọng - Hào Quang Dâm Dục", tag: "Adult", color: "text-pink-500", desc: "Khiến phụ nữ trong bán kính 100m phát tình cực độ." },
  { title: "Thấu Thị - Ma Nhãn", tag: "Nhìn thấu", color: "text-cyan-400", desc: "Nhìn xuyên vật cản và cả suy nghĩ thầm kín." },
  { title: "Trọng Lực - Hắc Ám", tag: "Vật lý", color: "text-slate-600", desc: "Ép đối phương quỳ rạp dưới chân bằng áp suất." },
  { title: "Thủy Hệ - Hải Vương", tag: "Mềm mại", color: "text-sky-400", desc: "Điều khiển nước và mọi loại chất lỏng sinh học." },
  { title: "Mộc Hệ - Phục Hồi", tag: "Sự sống", color: "text-green-500", desc: "Chữa lành mọi vết thương và hồi phục sinh lực." },
  { title: "Hư Không - Nuốt Chửng", tag: "Bóng tối", color: "text-neutral-900", desc: "Tạo ra hố đen nhỏ nuốt chửng mọi đòn tấn công." },
  { title: "Kim Loại - Vạn Năng", tag: "Cơ khí", color: "text-zinc-400", desc: "Biến cơ thể thành hợp kim hoặc tạo vũ khí." },
  { title: "Âm Thanh - Mê Hoặc", tag: "Sóng âm", color: "text-teal-400", desc: "Dùng giọng nói điều khiển nhịp tim và cảm xúc." },
  { title: "Băng Hệ - Tuyệt Diệt", tag: "Lạnh lẽo", color: "text-blue-100", desc: "Đóng băng vạn vật trong tích tắc." },
  { title: "Biến Hình - Vạn Tộc", tag: "Ngụy trang", color: "text-emerald-400", desc: "Hóa thân thành bất kỳ ai, mô phỏng cả gen." },
  { title: "Tử Vong - Lời Nguyền", tag: "Tối thượng", color: "text-rose-900", desc: "Chỉ định mục tiêu sẽ chết trong vòng 24 giờ." },
  { title: "Ánh Sáng - Thánh Khiết", tag: "Thần thánh", color: "text-yellow-100", desc: "Tỏa hào quang làm mù mắt và ban phước." },
  { title: "Sức Mạnh - Thần Lực", tag: "Vật lý", color: "text-orange-600", desc: "Sức mạnh tay không nhấc bổng cả tòa nhà." },
  { title: "Ảo Ảnh - Mê Cung", tag: "Tâm trí", color: "text-fuchsia-400", desc: "Giam cầm đối phương vào thế giới ảo mộng." },
  { title: "Dòng Máu - Rồng Thần", tag: "Huyết mạch", color: "text-red-400", desc: "Biến hình bán rồng, tăng 1000% chỉ số chiến đấu." },
  { title: "Gió Hệ - Phong Thần", tag: "Tự do", color: "text-sky-200", desc: "Bay lượn và tạo ra các cơn cuồng phong hủy diệt." },
  { title: "Đất Hệ - Nham Thạch", tag: "Kiên cố", color: "text-stone-600", desc: "Điều khiển mặt đất, tạo ra các vụ phun trào núi lửa." },
  { title: "Điện Từ - Ma Mạng", tag: "Công nghệ", color: "text-cyan-600", desc: "Thâm nhập và điều khiển mọi thiết bị điện tử." },
  { title: "Máu Hệ - Huyết Tộc", tag: "Cấm kỵ", color: "text-red-800", desc: "Điều khiển dòng máu của đối phương từ bên trong." },
  { title: "Giấc Mơ - Kẻ Ăn Mộng", tag: "Tâm linh", color: "text-violet-300", desc: "Xâm nhập giấc mơ để lấy cắp ký ức hoặc ám sát." },
  { title: "Chất Độc - Vạn Độc", tag: "Ám sát", color: "text-lime-500", desc: "Tạo ra các loại độc khí và dịch lỏng chết người." },
  { title: "Áp Suất - Chân Không", tag: "Vật lý", color: "text-slate-400", desc: "Rút cạn không khí trong một vùng không gian." },
  { title: "Phát Quang - Laser", tag: "Tia sáng", color: "text-yellow-300", desc: "Bắn ra các tia năng lượng xuyên thủng mọi vật chất." },
  { title: "Tơ Nhện - Trói Buộc", tag: "Khống chế", color: "text-purple-700", desc: "Tạo ra các sợi dây vô hình cực kỳ bền chắc." },
  { title: "Tốc Độ - Thần Tốc", tag: "Phản xạ", color: "text-amber-400", desc: "Di chuyển nhanh đến mức thời gian dường như đứng yên." },
  { title: "Hấp Thụ - Ma Năng", tag: "Phòng thủ", color: "text-blue-700", desc: "Hút cạn linh lực của kẻ thù khi bị tấn công." },
  { title: "Phân Thân - Vạn Ảnh", tag: "Số lượng", color: "text-neutral-500", desc: "Tạo ra hàng ngàn bản sao có sức mạnh tương đương." },
  { title: "Trí Tuệ - Siêu Máy Tính", tag: "Não bộ", color: "text-indigo-600", desc: "Tính toán hàng tỷ biến số chiến đấu trong 1 giây." },
  { title: "Dịch Chuyển - Cổng Trời", tag: "Không gian", color: "text-sky-500", desc: "Mở cổng kết nối giữa các hành tinh và vạn giới." },
  { title: "Sợi Xích - Minh Giới", tag: "Linh hồn", color: "text-gray-700", desc: "Triệu hồi xích sắt từ địa ngục kéo linh hồn kẻ địch." },
  { title: "Nham Thạch - Lửa Ngầm", tag: "Hỏa hệ", color: "text-orange-800", desc: "Biến mặt đất thành biển lửa nóng chảy." },
  { title: "Sóng Thần - Đại Dương", tag: "Thủy hệ", color: "text-blue-500", desc: "Triệu hồi lượng nước khổng lồ nhấn chìm thành phố." },
  { title: "Rừng Già - Thụ Ma", tag: "Mộc hệ", color: "text-green-800", desc: "Điều khiển thực vật tấn công và giam cầm mục tiêu." },
  { title: "Kim Cương - Bất Hoại", tag: "Phòng ngự", color: "text-cyan-100", desc: "Hóa cứng cơ thể thành kim cương vĩnh cửu." },
  { title: "Từ Trường - Đẩy Lùi", tag: "Lực lượng", color: "text-slate-500", desc: "Tạo ra lá chắn đẩy văng mọi vật thể tiếp cận." },
  { title: "Cảm Xúc - Thao Túng", tag: "Tâm lý", color: "text-rose-400", desc: "Khiến kẻ thù rơi vào trạng thái điên loạn hoặc si mê." },
  { title: "Khí Định - Vô Hình", tag: "Tàng hình", color: "text-neutral-300", desc: "Xóa tan mọi sự hiện diện vật lý và ma pháp." },
  { title: "Thiên Thạch - Tận Thế", tag: "Thần cấp", color: "text-red-900", desc: "Triệu hồi đá lửa từ vũ trụ rơi xuống mặt đất." },
  { title: "Sợi Tơ - Nhân Quả", tag: "Quy luật", color: "text-amber-500", desc: "Cắt đứt hoặc kết nối vận mệnh của hai người." },
  { title: "Bão Tố - Cuồng Phong", tag: "Nguyên tố", color: "text-blue-300", desc: "Tạo ra cơn lốc xoáy khổng lồ quét sạch vạn vật." },
  { title: "Phản Chiếu - Gương Thần", tag: "Phản đòn", color: "text-white", desc: "Phản lại 100% sát thương nhận vào cho đối thủ." },
  { title: "Hơi Thở - Băng Giá", tag: "Hàn băng", color: "text-cyan-200", desc: "Mọi lời nói thoát ra đều hóa thành băng tuyết." },
  { title: "Đôi Cánh - Thiên Thần", tag: "Thánh đức", color: "text-yellow-50", desc: "Sở hữu đôi cánh rực rỡ và quyền năng bay lượn." },
  { title: "Móng Vuốt - Thú Tính", tag: "Dã tính", color: "text-orange-500", desc: "Tăng cường bản năng săn mồi và sức mạnh cận chiến." },
  { title: "Mắt Thần - Thấu Thị", tag: "Trí tuệ", color: "text-emerald-300", desc: "Nhìn thấu cấu tạo nguyên tử của mọi vật chất." },
  { title: "Lửa Đen - Amaterasu", tag: "Ma đạo", color: "text-black", desc: "Ngọn lửa đen không bao giờ tắt cho đến khi cháy hết." },
  { title: "Hút Máu - Huyết Nguyệt", tag: "Huyết tộc", color: "text-red-700", desc: "Càng giết nhiều người, tu vi càng thăng tiến." },
  { title: "Cổng Quỷ - Địa Ngục", tag: "Triệu hồi", color: "text-purple-900", desc: "Gọi lên đội quân ác quỷ từ vực thẳm sâu nhất." },
  { title: "Mùi Hương - Mê Độc", tag: "Dâm mị", color: "text-pink-300", desc: "Tỏa ra mùi hương khiến đối phương mất đi lý trí xác thịt." },
  { title: "Siêu Năng - Telekinesis", tag: "Tâm lực", color: "text-indigo-400", desc: "Di chuyển vạn vật bằng ý nghĩ từ khoảng cách xa." },
  { title: "Năng Lượng - Hạt Nhân", tag: "Hủy diệt", color: "text-yellow-600", desc: "Tích tụ năng lượng nổ bùng như một quả bom nguyên tử." },
  { title: "Thực Tại - Ảo Ảnh", tag: "Quy luật", color: "text-violet-500", desc: "Biến những gì không có thật thành có thật và ngược lại." },
  { title: "Hệ Thống - Scan", tag: "Thông tin", color: "text-green-400", desc: "Hiện bảng chỉ số sức mạnh của bất kỳ ai trên đầu họ." },
  { title: "Mưa Axit - Ăn Mòn", tag: "Nguyên tố", color: "text-lime-600", desc: "Triệu hồi cơn mưa có khả năng làm tan chảy sắt thép." },
  { title: "Vàng Ròng - Midas", tag: "Tiền bạc", color: "text-yellow-500", desc: "Chạm tay vào vật gì, vật đó hóa thành vàng nguyên chất." },
  { title: "Vết Cắn - Thuần Hóa", tag: "Chiếm hữu", color: "text-rose-600", desc: "Kẻ bị cắn sẽ trở thành nô lệ trung thành vĩnh viễn." },
  { title: "Xương Cốt - Triệu Hồi", tag: "Hồn đạo", color: "text-stone-400", desc: "Gọi lên quân đoàn xương trắng từ lòng đất." },
  { title: "Thủy Tinh - Sắc Lẹm", tag: "Cơ khí", color: "text-blue-200", desc: "Điều khiển hàng triệu mảnh thủy tinh li ti cắt nát địch." },
  { title: "Bàn Tay - Khổng Lồ", tag: "Sức mạnh", color: "text-orange-700", desc: "Tạo ra đôi bàn tay năng lượng to bằng tòa nhà." },
  { title: "Hồi Phục - Niết Bàn", tag: "Bất tử", color: "text-red-300", desc: "Tự động hồi sinh từ đống tro tàn sau khi tử trận." },
  { title: "Tiếng Thét - Banshee", tag: "Âm thanh", color: "text-slate-300", desc: "Tiếng hét làm vỡ vụn linh hồn và màng nhĩ kẻ thù." },
  { title: "Tơ Hồng - Định Mệnh", tag: "Tâm linh", color: "text-pink-600", desc: "Buộc chặt tâm trí hai người lại với nhau mãi mãi." },
  { title: "Trái Tim - Máy Móc", tag: "Cyborg", color: "text-slate-800", desc: "Biến cơ thể thành cỗ máy chiến tranh vô cảm." },
  { title: "Ma Pháp - Cấm Giới", tag: "Phong ấn", color: "text-indigo-800", desc: "Vô hiệu hóa mọi dị năng trong bán kính 1km." },
  { title: "Bóng Đêm - Chiếm Hữu", tag: "Hắc ám", color: "text-neutral-800", desc: "Hóa thân thành cái bóng và xâm nhập vào người khác." },
  { title: "Dòng Chảy - Thời Gian", tag: "Quy luật", color: "text-blue-900", desc: "Tua nhanh hoặc làm chậm thời gian của một mục tiêu." },
  { title: "Vảy Rồng - Hộ Thể", tag: "Phòng ngự", color: "text-amber-700", desc: "Lớp vảy cứng hơn cả kim cương bao bọc làn da." },
  { title: "Ngọn Lửa - Vĩnh Hằng", tag: "Hỏa hệ", color: "text-red-500", desc: "Lửa cháy không cần oxy và không thể bị dập tắt." },
  { title: "Lưỡi Hái - Tử Thần", tag: "Tối thượng", color: "text-gray-900", desc: "Triệu hồi vũ khí có thể trảm đứt mọi linh hồn." },
  { title: "Thiên Sứ - Cánh Đen", tag: "Sa ngã", color: "text-purple-800", desc: "Sức mạnh từ nỗi đau và sự hận thù của thiên đình." },
  { title: "Thủy Thể - Tan Chảy", tag: "Thủy hệ", color: "text-sky-300", desc: "Biến cơ thể thành nước để đi xuyên mọi khe hở." },
  { title: "Kim Kình - Chấn Động", tag: "Sức mạnh", color: "text-yellow-700", desc: "Mỗi cú đấm tạo ra trận động đất cấp 10." },
  { title: "Mê Cung - Không Gian", tag: "Giam cầm", color: "text-indigo-500", desc: "Nhốt kẻ thù vào một vòng lặp không gian vô tận." },
  { title: "Hơi Thở - Rồng Thần", tag: "Long tộc", color: "text-orange-400", desc: "Thổi ra luồng năng lượng nguyên tố cực đại." },
  { title: "Bùa Chú - Phù Văn", tag: "Ma thuật", color: "text-purple-500", desc: "Dùng các ký tự cổ để lập trận hoặc nguyền rủa." },
  { title: "Sao Băng - Rực Rỡ", tag: "Quang năng", color: "text-yellow-200", desc: "Triệu hồi các hạt ánh sáng nổ tung rực rỡ." },
  { title: "Độc Tố - Tê Liệt", tag: "Khống chế", color: "text-lime-400", desc: "Làm tê liệt hệ thần kinh đối phương trong 1 giây chạm." },
  { title: "Vạn Vật - Giao Tiếp", tag: "Tri thức", color: "text-emerald-500", desc: "Nói chuyện được với đá, cây và cả linh hồn." },
  { title: "Dâm Thủy - Trào Dâng", tag: "Adult", color: "text-pink-400", desc: "Điều khiển nước lồn để trói buộc và làm nhục đối phương." },
  { title: "Bàn Tay - Thần Y", tag: "Chữa lành", color: "text-teal-300", desc: "Cải tử hoàn sinh chỉ bằng một cái chạm tay nhẹ." },
  { title: "Trọng Lực - Bay Lượn", tag: "Tự do", color: "text-blue-100", desc: "Xóa bỏ trọng lực bản thân để bay như chim đại bàng." },
  { title: "Âm Dương - Đảo Ngược", tag: "Quy luật", color: "text-zinc-500", desc: "Hoán đổi vị trí, giới tính hoặc sức mạnh hai bên." },
  { title: "Bóng Ma - Xuyên Thấu", tag: "Ẩn danh", color: "text-neutral-400", desc: "Đi xuyên qua tường và mọi vật thể rắn chắc." },
  { title: "Hạt Nhân - Lửa Xanh", tag: "Hủy diệt", color: "text-cyan-500", desc: "Năng lượng hạt nhân tinh thuần tỏa ra từ đôi mắt." },
  { title: "Tiên Khí - Thoát Tục", tag: "Thần thánh", color: "text-white", desc: "Khí chất áp đảo làm mọi kẻ thù phải quỳ lạy." },
  { title: "Huyết Thạch - Định Ước", tag: "Chiếm hữu", color: "text-red-600", desc: "Dùng máu để ký kết khế ước nô lệ vĩnh viễn." },
  { title: "Sấm Sét - Tốc Độ", tag: "Lôi hệ", color: "text-yellow-400", desc: "Di chuyển và tấn công với vận tốc ánh sáng." },
  { title: "Cây Gậy - Vạn Năng", tag: "Biến hóa", color: "text-amber-600", desc: "Biến đổi vật chất này thành vật chất khác dễ dàng." },
  { title: "Tiếng Hát - Siren", tag: "Mê hoặc", color: "text-blue-400", desc: "Khiến toàn bộ quân địch tự giết lẫn nhau vì tiếng hát." },
  { title: "Hố Đen - Nuốt Chửng", tag: "Hư không", color: "text-black", desc: "Tạo ra một điểm không trọng lượng hút sạch vạn vật." },
  { title: "Cánh Hoa - Sát Thủ", tag: "Mộc hệ", color: "text-rose-400", desc: "Điều khiển cánh hoa sắc bén như dao cạo để ám sát." },
  { title: "Ký Ức - Sửa Đổi", tag: "Tâm trí", color: "text-violet-600", desc: "Thay đổi quá khứ và ký ức của một người vĩnh viễn." },
  { title: "Trái Tim - Rồng Thiêng", tag: "Huyết mạch", color: "text-red-500", desc: "Sức sống vô hạn, không bao giờ biết mệt mỏi." },
  { title: "Chìa Khóa - Vạn Giới", tag: "Tối thượng", color: "text-yellow-700", desc: "Mở ra cánh cửa đến bất kỳ chiều không gian nào." },
  { title: "Sáng Thế - Khởi Nguyên", tag: "Chúa tể", color: "text-emerald-900", desc: "Quyền năng tối cao tạo ra và hủy diệt toàn bộ vũ trụ." }
];