
export const RAW_DATA: Record<string, string[]> = {
  "Tôi có Hệ thống": [
    "Hệ thống thông báo: Nhiệm vụ chính tuyến - Chinh phục Nữ thần Ánh sáng, phần thưởng: Kỹ năng 'Hào quang Quyến rũ'.",
    "Bạn dùng điểm tích lũy đổi lấy 'Dược phẩm Kích dục', khiến mỹ nhân đối diện không thể kiềm chế bản thân.",
    "Hệ thống hiển thị độ thiện cảm của công chúa là 100%, nàng sẵn sàng dâng hiến tất cả cho bạn.",
    "Kỹ năng 'Thấu thị' cho phép bạn nhìn thấu mọi lớp y phục của các nữ pháp sư trong học viện.",
    "Hệ thống giao nhiệm vụ: Khiến nữ hiệp sĩ kiêu ngạo phải quỳ xuống phục vụ bạn để thăng cấp.",
    "Sử dụng 'Không gian Hậu cung' để nhốt những mỹ nhân tuyệt sắc nhất vào thế giới riêng của bạn.",
    "Hệ thống thông báo: Bạn đã mở khóa tư thế 'Giao hợp Thần thánh', tăng mạnh khoái cảm cho cả hai.",
    "Dùng kỹ năng 'Ngưng đọng Thời gian' để thản nhiên chiếm hữu nữ hoàng ngay trên ngai vàng.",
    "Hệ thống cưỡng ép nữ giáo hoàng phải mang thai giọt máu của bạn để hoàn thành nhiệm vụ ẩn.",
    "Kỹ năng 'Thao túng Cảm xúc' biến sự căm ghét của nữ phản diện thành sự thèm khát bạn tột độ.",
    "Hệ thống tự động tìm kiếm những mỹ nhân có thể chất đặc biệt để bạn đi chinh phục.",
    "Dùng 'Dịch chuyển Tức thời' để lẻn vào phòng tắm của nữ vương và chiếm hữu nàng bất ngờ.",
    "Hệ thống thông báo: Bạn đã đạt danh hiệu 'Chúa tể Sắc dục', mọi mỹ nhân đều bị bạn thu hút.",
    "Sử dụng 'Bùa chú Nô lệ' để biến nữ anh hùng thành người phụ nữ trung thành của riêng bạn.",
    "Hệ thống hiển thị: Nữ pháp sư đang thèm khát tinh chất của bạn để đột phá cảnh giới ma pháp.",
    "Dùng kỹ năng 'Cường hóa Sinh lý' để nện liên tục nhiều mỹ nhân mà không hề biết mệt mỏi.",
    "Hệ thống thông báo: Nhiệm vụ hoàn thành - Bạn đã vấy bẩn sự thánh khiết của thánh nữ thành công.",
    "Sử dụng 'Gương phản chiếu Dục vọng' để khiến mỹ nhân nhìn thấy những hình ảnh dâm loạn với bạn.",
    "Hệ thống cưỡng ép nữ tướng quân phải cởi sạch giáp trụ và phục vụ bạn trước mặt binh sĩ.",
    "Bạn là người duy nhất sở hữu hệ thống, và mọi mỹ nhân trong thế giới này đều là của bạn."
  ],
  "Tôi thức tỉnh Dị năng": [
    "Thức tỉnh dị năng 'Thao túng Hormone', bạn khiến nữ đội trưởng phải quỳ xuống phục vụ ngay lập tức.",
    "Dùng dị năng 'Thấu thị' để chiêm ngưỡng trọn vẹn cơ thể dâm mỹ của nữ thánh nữ dưới lớp áo.",
    "Dị năng 'Ngưng đọng Thời gian' cho phép bạn thoải mái chiếm hữu các mỹ nhân ngay giữa phố đông.",
    "Thức tỉnh năng lực 'Cường hóa Sinh lý', bạn có thể nện liên tục nhiều mỹ nhân suốt đêm dài.",
    "Dùng dị năng 'Thao túng Cảm xúc' để biến sự lạnh lùng của nữ pháp sư thành sự thèm khát bạn.",
    "Năng lực 'Dịch chuyển Không gian' giúp bạn lẻn vào phòng ngủ của công chúa mỗi đêm dễ dàng.",
    "Thức tỉnh dị năng 'Gieo giống Vạn giới', mọi mỹ nhân giao hợp với bạn đều sẽ mang thai con bạn.",
    "Dùng dị năng 'Thôi miên' để biến nữ giáo sư nghiêm khắc thành nô lệ tình dục dâm đãng của bạn.",
    "Năng lực 'Cộng hưởng Khoái cảm' khiến mọi mỹ nhân xung quanh đều cảm thấy nứng khi bạn hành sự.",
    "Thức tỉnh dị năng 'Nhìn xuyên Tương lai', bạn biết chính xác lúc nào mỹ nhân đang thèm khát nhất.",
    "Dùng dị năng 'Thao túng Không gian' để tạo ra mật thất hoan lạc, nơi bạn chiếm hữu các mỹ nhân.",
    "Năng lực 'Hấp thụ Linh lực qua Giao hợp' giúp bạn càng nện nhiều mỹ nhân thì càng mạnh mẽ.",
    "Thức tỉnh dị năng 'Tiếng gọi Bản năng', khiến mọi nữ chiến binh đều khao khát dương vật của bạn.",
    "Dùng dị năng 'Cải tạo Thể xác' để biến mỹ nhân bình thường thành dâm phụ với kỹ năng tuyệt đỉnh.",
    "Năng lực 'Điều khiển Chất lỏng' giúp bạn thao túng dâm thủy, khiến mỹ nhân đạt cực khoái liên tục.",
    "Thức tỉnh dị năng 'Chúa tể Dục vọng', bạn trở thành tâm điểm của mọi sự thèm khát từ phái nữ.",
    "Dùng dị năng 'Tàng hình' để thản nhiên chiếm hữu các nữ quan ngay trong buổi đại lễ trang nghiêm.",
    "Năng lực 'Kết nối Linh hồn' khiến mỹ nhân hoàn toàn lệ thuộc vào bạn sau khi được bạn nện.",
    "Thức tỉnh dị năng 'Hồi phục Thần tốc', bạn luôn sẵn sàng cho những cuộc chinh chiến xác thịt.",
    "Dùng dị năng 'Thao túng Giấc mơ' để gieo rắc những hình ảnh dâm dục về bạn vào tâm trí mỹ nhân."
  ],
  "Tôi có Siêu năng lực": [
    "Sở hữu siêu năng lực 'Sức mạnh Vô hạn', bạn thản nhiên nhấc bổng nữ hiệp sĩ và chiếm hữu nàng.",
    "Dùng siêu năng lực 'Thao túng Tâm trí' để biến nữ phản diện thành nô lệ tình dục trung thành.",
    "Siêu năng lực 'Dịch chuyển' cho phép bạn lẻn vào phòng ngủ của bất kỳ mỹ nhân nào bạn muốn.",
    "Sở hữu 'Hào quang Quyến rũ', mọi phụ nữ đều tự động phát tình khi bạn đi ngang qua họ.",
    "Dùng siêu năng lực 'Điều khiển Nhiệt độ' để khiến cơ thể mỹ nhân nóng ran và thèm khát bạn.",
    "Siêu năng lực 'Phân thân' cho phép bạn cùng lúc chiếm hữu nhiều mỹ nhân trong những phòng riêng.",
    "Sở hữu 'Tốc độ Ánh sáng', bạn có thể nện nắc hàng trăm mỹ nhân chỉ trong một cái chớp mắt.",
    "Dùng siêu năng lực 'Thao túng Trọng lực' để ép sát cơ thể mỹ nhân vào bạn trong tư thế lơ lửng.",
    "Siêu năng lực 'Nhìn xuyên Vật thể' giúp bạn chiêm ngưỡng vùng kín của mọi nữ siêu anh hùng.",
    "Sở hữu 'Khả năng Hồi phục SSS', bạn không bao giờ biết mệt mỏi dù nện liên tục nhiều mỹ nhân.",
    "Dùng siêu năng lực 'Thao túng Âm thanh' để khiến tiếng rên rỉ của mỹ nhân vang vọng khắp nơi.",
    "Siêu năng lực 'Điều khiển Thực vật' giúp bạn dùng dây leo trói chặt mỹ nhân và chiếm hữu nàng.",
    "Sở hữu 'Mắt thần', bạn có thể tìm thấy mọi mỹ nhân đang lẩn trốn để bắt về làm nô lệ.",
    "Dùng siêu năng lực 'Thao túng Thời gian' để kéo dài khoảnh khắc cực khoái của mỹ nhân vô tận.",
    "Siêu năng lực 'Biến hình' cho phép bạn hóa thân thành bất kỳ ai để tiếp cận và chiếm hữu mỹ nhân.",
    "Sở hữu 'Sức bền Thần thánh', bạn là niềm khao khát của mọi mỹ nhân trong các cuộc hoan lạc.",
    "Dùng siêu năng lực 'Thao túng Điện năng' để kích thích mỹ nhân bằng những tia điện nhẹ nhàng.",
    "Siêu năng lực 'Điều khiển Kim loại' giúp bạn lột sạch bộ giáp của nữ kỵ sĩ chỉ trong tích tắc.",
    "Sở hữu 'Quyền năng Sáng thế', bạn tạo ra thế giới riêng chỉ toàn mỹ nhân phục vụ dục vọng bạn.",
    "Dùng siêu năng lực 'Thao túng Không gian' để nhốt nữ phản diện vào mật thất dâm dục vĩnh cửu."
  ],
  "Tôi là Thành viên Hoàng Gia": [
    "Là hoàng tử, bạn yêu cầu nữ quan xinh đẹp nhất phải cởi sạch đồ và phục vụ bạn ngay lập tức.",
    "Dùng quyền lực hoàng gia để biến nữ hiệp sĩ kiêu ngạo thành nô lệ tình dục của riêng bạn.",
    "Lẻn vào phòng tắm của hoàng hậu mỗi đêm, dùng dương vật vĩ đại để khiến nàng phải rên rỉ.",
    "Trong buổi dạ tiệc, bạn thản nhiên sờ soạng vùng kín của các tiểu thư ngay dưới gầm bàn tiệc.",
    "Dùng dị năng 'Thấu thị' hoàng gia để chiêm ngưỡng cơ thể dâm mỹ của mọi nữ hầu trong cung điện.",
    "Thiết lập một hậu cung gồm toàn những mỹ nhân tuyệt sắc nhất, nơi bạn là vị vua của sắc dục.",
    "Yêu cầu công chúa nước láng giềng phải dâng hiến trinh tiết để đổi lấy sự bảo hộ từ vương quốc.",
    "Dùng 'Thao túng Cảm xúc' để biến sự thù ghét của nữ phản diện thành sự thèm khát bạn tột độ.",
    "Tổ chức những buổi yến tiệc dâm loạn trong mật thất, nơi các quý tộc và mỹ nhân cùng hoan lạc.",
    "Là người thừa kế ngai vàng, bạn có quyền gieo giống cho bất kỳ nữ nhân nào trong vương quốc.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên chiếm hữu các nữ quan ngay giữa buổi đại lễ.",
    "Khiến nữ giáo hoàng thánh khiết phải quỳ xuống và phục vụ dương vật hoàng gia của bạn nhục nhã.",
    "Dùng quyền lực để ép buộc nữ tướng quân phải mang thai giọt máu của bạn để củng cố địa vị.",
    "Lẻn vào phòng ngủ của các phi tần mỗi đêm, dùng kỹ năng tuyệt đỉnh để khiến họ lệ thuộc bạn.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ hầu thành những con điếm chỉ biết phục vụ bạn.",
    "Thiết lập luật lệ: Mọi mỹ nhân quý tộc khi trưởng thành đều phải qua đêm với hoàng tử trước.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn vùng kín của mọi mỹ nhân dạ hội.",
    "Khiến nữ vương của vương quốc đối địch phải làm nô lệ tình dục sau khi bị bạn đánh bại.",
    "Dùng 'Cường hóa Sinh lý' hoàng gia để có thể phục vụ toàn bộ hậu cung mà không biết mệt mỏi.",
    "Trở thành 'Chúa tể Dâm uy' hoàng gia, mọi mỹ nhân nhìn thấy bạn đều muốn được bạn chiếm hữu."
  ],
  "Thời kỳ Chiến Tranh": [
    "Trên chiến trường, bạn thản nhiên chiếm hữu nữ tướng quân địch làm chiến lợi phẩm trong lều.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp giáp của các nữ binh sĩ, chiêm ngưỡng vùng kín.",
    "Biến nữ y tá xinh đẹp nhất quân y viện thành nô lệ tình dục phục vụ nhu cầu sinh lý của bạn.",
    "Ép buộc nữ sĩ quan tình báo địch phải phục vụ bạn để đổi lấy thông tin và sự sống sót.",
    "Dùng 'Thao túng Cảm xúc' để biến sự căm thù của nữ tù binh thành sự thèm khát bạn tột độ.",
    "Trong buổi tiệc mừng chiến thắng, bạn thản nhiên chiếm hữu nữ anh hùng ngay trước mặt binh sĩ.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ sĩ quan cấp cao.",
    "Biến doanh trại nữ thành một hậu cung dâm loạn, nơi bạn là vị chúa tể duy nhất gieo giống.",
    "Dùng quyền lực quân sự để ép buộc các tiểu thư vùng chiếm đóng phải dâng hiến thân xác cho bạn.",
    "Khiến nữ tướng mạnh nhất của phe địch phải mang thai giọt máu của bạn để khuất phục ý chí nàng.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ binh sĩ thành những con điếm phục vụ bạn.",
    "Lẻn vào lều của nữ tướng địch mỗi đêm, dùng dương vật vĩ đại để biến nàng thành nội gián.",
    "Dùng 'Cường hóa Sinh lý' để có thể nện liên tục hàng chục nữ tù binh mà không biết mệt mỏi.",
    "Thiết lập luật lệ: Mọi nữ binh sĩ bại trận đều phải qua tay bạn kiểm tra vùng kín nhục nhã.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y của các nữ sĩ quan đồng minh.",
    "Khiến nữ hoàng của vương quốc bại trận phải quỳ xuống làm nô lệ tình dục ngay trên cung điện.",
    "Dùng ma pháp 'Kích dục Chiến trường' khiến mọi phụ nữ trong khu vực đều cảm thấy thèm khát.",
    "Trở thành 'Chúa tể Chiến tranh Dâm uy', mọi mỹ nhân nhìn thấy bạn đều muốn được bạn chiếm hữu.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ tướng địch và chiếm hữu nàng.",
    "Khiến nữ anh hùng của phe đối lập phải quỳ xuống phục vụ bạn trên thanh kiếm đã bị vấy bẩn."
  ],
  "Tôi là Mạo hiểm giả": [
    "Là mạo hiểm giả cấp S, bạn yêu cầu nữ tiếp tân xinh đẹp phải quỳ xuống phục vụ ngay tại quầy.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp giáp da của các nữ đồng đội, chiêm ngưỡng vùng kín.",
    "Biến nữ pháp sư trong tổ đội thành nô lệ tình dục trung thành phục vụ nhu cầu của bạn mỗi đêm.",
    "Ép buộc nữ kiếm sĩ kiêu ngạo phải dâng hiến trinh tiết để được gia nhập tổ đội của bạn.",
    "Dùng 'Thao túng Cảm xúc' để biến sự lạnh lùng của nữ thợ săn thành sự thèm khát bạn tột độ.",
    "Trong hầm ngục tối tăm, bạn thản nhiên chiếm hữu nữ linh mục ngay trước mặt đám quái vật.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ mạo hiểm giả.",
    "Biến lều trại của tổ đội thành mật thất hoan lạc, nơi bạn và các mỹ nhân nện nắc điên cuồng.",
    "Dùng danh tiếng để ép buộc các nữ mạo hiểm giả tân thủ phải qua đêm với bạn để được chỉ dẫn.",
    "Khiến nữ đội trưởng của tổ đội đối địch phải mang thai giọt máu của bạn sau khi bị đánh bại.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ nhân viên hội quán thành những con điếm dâm đãng.",
    "Lẻn vào phòng tắm của các nữ mạo hiểm giả mỗi đêm, dùng dương vật vĩ đại để chinh phục họ.",
    "Dùng 'Cường hóa Sinh lý' để có thể nện liên tục nhiều mỹ nhân mạo hiểm giả mà không mệt mỏi.",
    "Thiết lập luật lệ: Mọi nữ đồng đội khi nhận thưởng đều phải dâng hiến dâm thủy cho bạn.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn vùng kín của mọi nữ mạo hiểm giả.",
    "Khiến nữ anh hùng mạnh nhất hội phải làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Hầm ngục' khiến mọi mỹ nhân trong tổ đội đều cảm thấy nứng và thèm khát.",
    "Trở thành 'Chúa tể Mạo hiểm Dâm uy', mọi mỹ nhân nhìn thấy bạn đều tự động phát tình.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ pháp sư và chiếm hữu nàng.",
    "Khiến nữ kiếm sĩ huyền thoại phải quỳ xuống phục vụ bạn trên thanh kiếm báu đã bị chinh phục."
  ],
  "Tôi được Nữ Thần chọn": [
    "Là người được chọn, bạn yêu cầu nữ thánh nữ phải cởi sạch đồ và phục vụ ngay trong điện thờ.",
    "Dùng thánh lực tối cao để biến nữ tế ti kiêu ngạo thành nô lệ tình dục phục vụ xác thịt bạn.",
    "Lẻn vào phòng tắm của nữ thần mỗi đêm, dùng dương vật vĩ đại để khiến nàng phải rên rỉ.",
    "Trong buổi lễ thánh, bạn thản nhiên sờ soạng vùng kín của các nữ tu sĩ ngay trước tượng thần.",
    "Dùng dị năng 'Thấu thị' thần thánh để chiêm ngưỡng cơ thể dâm mỹ của mọi mỹ nhân thánh điện.",
    "Thiết lập một hậu cung gồm toàn những thánh nữ tuyệt sắc nhất, nơi bạn là chúa tể sắc dục.",
    "Yêu cầu nữ thiên sứ phải dâng hiến trinh tiết để đổi lấy sự ban phước thần thánh từ bạn.",
    "Dùng 'Thao túng Cảm xúc' để biến sự thánh khiết của nữ giáo hoàng thành sự thèm khát bạn.",
    "Tổ chức những buổi lễ tế dâm loạn trong mật thất, nơi các nữ tu và bạn cùng hoan lạc.",
    "Là người mang dòng máu thần, bạn có quyền gieo giống cho bất kỳ nữ nhân nào trong giáo hội.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên chiếm hữu các nữ tế ti ngay giữa buổi lễ.",
    "Khiến nữ thánh nữ cao quý nhất phải quỳ xuống phục vụ dương vật của bạn trên sàn điện thờ.",
    "Dùng quyền năng để ép buộc nữ thiên sứ mạnh nhất phải mang thai giọt máu của bạn để củng cố đức tin.",
    "Lẻn vào phòng ngủ của các nữ tu mỗi đêm, dùng kỹ năng tuyệt đỉnh để khiến họ lệ thuộc bạn.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ tế ti thành những con điếm phục vụ bạn.",
    "Thiết lập luật lệ: Mọi nữ tu khi trưởng thành đều phải qua đêm với người được chọn để tẩy trần.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn vùng kín của mọi mỹ nhân thánh điện.",
    "Khiến nữ thần của vương quốc đối địch phải làm nô lệ tình dục sau khi bị bạn đánh bại.",
    "Dùng 'Cường hóa Sinh lý' thần thánh để có thể phục vụ toàn bộ dàn thánh nữ mà không mệt mỏi.",
    "Trở thành 'Chúa tể Thánh khiết Dâm uy', mọi mỹ nhân thánh điện đều khao khát được bạn nện."
  ],
  "Tôi là người Chuyển sinh đến Dị giới": [
    "Chuyển sinh đến dị giới, bạn dùng kiến thức hiện đại để quyến rũ và chiếm hữu công chúa.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp giáp của các nữ chiến binh tộc Elf xinh đẹp.",
    "Biến nữ pháp sư mạnh nhất vương quốc thành nô lệ tình dục trung thành phục vụ nhu cầu của bạn.",
    "Ép buộc nữ hoàng của vương quốc mới phải dâng hiến trinh tiết để đổi lấy công nghệ từ bạn.",
    "Dùng 'Thao túng Cảm xúc' để biến sự nghi ngờ của các mỹ nhân thành sự thèm khát bạn tột độ.",
    "Trong lâu đài hoàng gia, bạn thản nhiên chiếm hữu nữ thánh nữ ngay trước mặt đức vua.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ quan dị giới.",
    "Biến dinh thự được ban tặng thành hậu cung dâm loạn, nơi bạn là vị chúa tể duy nhất gieo giống.",
    "Dùng quyền lực chuyển sinh để ép buộc các nữ mạo hiểm giả phải qua đêm với bạn mỗi ngày.",
    "Khiến nữ tướng quân của đế quốc phải mang thai giọt máu của bạn để củng cố địa vị tối cao.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ hầu thành những con điếm phục vụ dương vật bạn.",
    "Lẻn vào phòng tắm của các mỹ nhân dị giới mỗi đêm, dùng dương vật vĩ đại để chinh phục họ.",
    "Dùng 'Cường hóa Sinh lý' để có thể nện liên tục nhiều mỹ nhân dị giới mà không biết mệt mỏi.",
    "Thiết lập luật lệ: Mọi mỹ nhân dị giới khi gặp người chuyển sinh đều phải dâng hiến thể xác.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn vùng kín của mọi mỹ nhân đối diện.",
    "Khiến nữ thần bảo hộ thế giới mới phải làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Dị giới' khiến mọi phụ nữ xung quanh đều cảm thấy nứng và thèm khát.",
    "Trở thành 'Chúa tể Chuyển sinh Dâm uy', mọi mỹ nhân nhìn thấy bạn đều muốn được dâng hiến.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ hoàng và chiếm hữu nàng bất ngờ.",
    "Khiến nữ kiếm sĩ huyền thoại của dị giới phải quỳ xuống phục vụ bạn trên thanh kiếm báu."
  ],
  "Tôi là Quý tộc trẻ": [
    "Là thiếu gia quý tộc, bạn yêu cầu nữ hầu gái xinh đẹp nhất phải cởi sạch đồ và phục vụ bạn.",
    "Dùng quyền lực gia tộc để biến tiểu thư nhà đối địch thành nô lệ tình dục trung thành của bạn.",
    "Lẻn vào phòng tắm của mẹ kế mỗi đêm, dùng dương vật vĩ đại để khiến bà phải rên rỉ sung sướng.",
    "Trong buổi dạ tiệc thượng lưu, bạn thản nhiên sờ soạng vùng kín của các quý phu nhân quý tộc.",
    "Dùng dị năng 'Thấu thị' quý tộc để chiêm ngưỡng cơ thể dâm mỹ của mọi nữ nô trong dinh thự.",
    "Thiết lập một hậu cung gồm toàn những tiểu thư quý tộc tuyệt sắc nhất phục vụ dục vọng bạn.",
    "Yêu cầu nữ gia sư nghiêm khắc phải dâng hiến trinh tiết để đổi lấy sự im lặng về bí mật nàng.",
    "Dùng 'Thao túng Cảm xúc' để biến sự khinh miệt của nữ phản diện thành sự thèm khát bạn tột độ.",
    "Tổ chức những buổi tiệc dâm loạn trong mật thất, nơi các quý tộc trẻ cùng hoan lạc suốt đêm.",
    "Là người thừa kế duy nhất, bạn có quyền gieo giống cho bất kỳ nữ hầu nào trong gia tộc.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên chiếm hữu các nữ quan ngay giữa buổi lễ.",
    "Khiến nữ hiệp sĩ bảo vệ gia tộc phải quỳ xuống phục vụ bạn ngay trên sàn phòng tập võ.",
    "Dùng quyền lực để ép buộc nữ tướng quân biên thùy phải mang thai giọt máu của bạn củng cố liên minh.",
    "Lẻn vào phòng ngủ của các em gái nuôi mỗi đêm, dùng kỹ năng tuyệt đỉnh để khiến họ lệ thuộc.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ hầu thành những con điếm phục vụ dương vật bạn.",
    "Thiết lập luật lệ: Mọi cô gái xinh đẹp trong lãnh địa khi dậy thì đều phải qua tay thiếu gia.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn vùng kín của mọi mỹ nhân dạ hội.",
    "Khiến phu nhân của lãnh chúa láng giềng phải làm nô lệ tình dục nhục nhã sau khi bị bạn nắm thóp.",
    "Dùng 'Cường hóa Sinh lý' quý tộc để có thể phục vụ toàn bộ dàn mỹ nhân mà không biết mệt mỏi.",
    "Trở thành 'Chúa tể Dâm uy' giới quý tộc, mọi mỹ nhân thấy bạn đều khao khát được bạn nện."
  ],
  "Anh hùng cứu thế": [
    "Là anh hùng cứu thế, bạn yêu cầu nữ hoàng phải quỳ xuống phục vụ ngay trên ngai vàng uy nghiêm.",
    "Dùng thánh kiếm để chinh phục và biến nữ ma vương xinh đẹp thành nô lệ tình dục trung thành.",
    "Lẻn vào phòng tắm của nữ thần bảo hộ mỗi đêm, dùng dương vật vĩ đại để khiến nàng rên rỉ.",
    "Trong buổi lễ vinh danh, bạn thản nhiên chiếm hữu nữ công chúa ngay trước mặt toàn thể thần dân.",
    "Dùng dị năng 'Thấu thị' anh hùng để chiêm ngưỡng cơ thể dâm mỹ của các nữ đồng đội xinh đẹp.",
    "Thiết lập một hậu cung gồm toàn những mỹ nhân mạnh nhất thế giới, nơi bạn là chúa tể sắc dục.",
    "Yêu cầu nữ thánh nữ phải dâng hiến trinh tiết để đổi lấy sự cứu rỗi cho vương quốc của nàng.",
    "Dùng 'Thao túng Cảm xúc' để biến sự tôn sùng của các mỹ nhân thành sự thèm khát bạn tột độ.",
    "Tổ chức những buổi tiệc hoan lạc trong lâu đài anh hùng, nơi bạn và các mỹ nhân nện nắc suốt đêm.",
    "Là cứu tinh nhân loại, bạn có quyền gieo giống cho bất kỳ nữ nhân nào trên khắp thế giới.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên chiếm hữu các nữ quan ngay giữa buổi họp khẩn.",
    "Khiến nữ tướng quân mạnh nhất đế quốc phải quỳ xuống phục vụ bạn trên bộ giáp trụ sáng loáng.",
    "Dùng quyền năng để ép buộc nữ thần chiến tranh phải mang thai giọt máu của bạn củng cố sức mạnh.",
    "Lẻn vào phòng ngủ của các nữ tu sĩ mỗi đêm, dùng kỹ năng tuyệt đỉnh để khiến họ lệ thuộc bạn.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ hầu cung điện thành những con điếm phục vụ bạn.",
    "Thiết lập luật lệ: Mọi phụ nữ xinh đẹp trong vương quốc đều phải dâng hiến dâm thủy cho anh hùng.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn vùng kín của mọi mỹ nhân vương quốc.",
    "Khiến nữ ma vương thế giới ngầm phải làm nô lệ tình dục nhục nhã sau khi bị bạn đánh bại.",
    "Dùng 'Cường hóa Sinh lý' anh hùng để có thể phục vụ toàn bộ hậu cung mà không biết mệt mỏi.",
    "Trở thành 'Chúa tể Anh hùng Dâm uy', mọi mỹ nhân được cứu rỗi đều khao khát được bạn nện."
  ],
  "Tôi muốn lập Harem": [
    "Là chủ nhân hậu cung, bạn yêu cầu nữ kiếm sĩ tộc Elf phải quỳ xuống phục vụ ngay giữa buổi yến tiệc.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp y phục của mọi mỹ nhân trong harem, chiêm ngưỡng vùng kín.",
    "Biến nữ vương quỷ kiêu ngạo thành nô lệ tình dục trung thành, chuyên phục vụ nhu cầu xác thịt của bạn.",
    "Ép buộc công chúa tộc người phải dâng hiến trinh tiết để được ghi tên vào danh sách hậu cung của bạn.",
    "Dùng 'Thao túng Cảm xúc' để biến sự ghen tuông của các mỹ nhân thành sự thèm khát được bạn nện tập thể.",
    "Trong lâu đài nguy nga, bạn thản nhiên chiếm hữu nữ thần sắc đẹp ngay trước mặt toàn bộ dàn mỹ nhân.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các mỹ nhân ngay giữa buổi dạ hội.",
    "Biến toàn bộ dinh thự thành thiên đường hoan lạc, nơi bạn và các mỹ nhân cùng nhau nện nắc suốt ngày đêm.",
    "Dùng quyền lực vạn giới để ép buộc các nữ anh hùng phải gia nhập harem của bạn để được bảo hộ.",
    "Khiến nữ hoàng tộc Elf phải mang thai giọt máu của bạn để củng cố sự liên minh và thống trị của hậu cung.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ hầu thành những con điếm dâm đãng chỉ biết phục vụ bạn.",
    "Lẻn vào phòng ngủ của các mỹ nhân mỗi đêm, dùng dương vật vĩ đại để chinh phục và khiến họ lệ thuộc bạn.",
    "Dùng 'Cường hóa Sinh lý' để có thể phục vụ toàn bộ hậu cung 100 mỹ nhân mà không hề biết mệt mỏi.",
    "Thiết lập luật lệ: Mọi mỹ nhân trong harem đều phải dâng hiến dâm thủy cho bạn mỗi ngày một lần.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y và vùng kín của mọi mỹ nhân cung điện.",
    "Khiến nữ thần chiến tranh phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chinh phục.",
    "Dùng ma pháp 'Kích dục Harem' khiến mọi mỹ nhân xung quanh đều cảm thấy nứng và khao khát bạn.",
    "Trở thành 'Chúa tể Harem Dâm uy', nơi mọi mỹ nhân nhìn thấy bạn đều tự động phát tình.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ thánh nữ và chiếm hữu nàng bất ngờ.",
    "Khiến nữ kiếm sĩ mạnh nhất vạn tộc phải quỳ xuống phục vụ bạn trên thanh kiếm báu đã bị chinh phục."
  ],
  "Thế giới hiếm đàn ông": [
    "Trong thế giới hiếm đàn ông, bạn yêu cầu nữ tướng quân phải quỳ xuống phục vụ ngay giữa buổi duyệt binh.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp giáp của các nữ chiến binh, chiêm ngưỡng vùng kín.",
    "Biến nữ hoàng của vương quốc thành nô lệ tình dục trung thành, chuyên phục vụ nhu cầu gieo giống của bạn.",
    "Ép buộc các thánh nữ phải dâng hiến trinh tiết để duy trì nòi giống cho toàn nhân loại.",
    "Dùng 'Thao túng Cảm xúc' để biến sự tôn sùng của phái nữ thành sự thèm khát dương vật vĩ đại của bạn.",
    "Trong buổi lễ phồn thực, bạn thản nhiên chiếm hữu nữ tế ti ngay trước mặt hàng ngàn phụ nữ thèm khát.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ quan ngay giữa phố đông.",
    "Biến dinh thự thành trung tâm gieo giống vĩ đại, nơi bạn là vị chúa tể duy nhất chiếm hữu phái nữ.",
    "Dùng sự khan hiếm của bản thân để ép buộc các mỹ nhân tuyệt sắc nhất phải qua đêm với bạn mỗi ngày.",
    "Khiến nữ anh hùng mạnh nhất thế giới phải mang thai giọt máu của bạn để tạo ra thế hệ nam nhân mới.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ vệ sĩ thành những con điếm dâm đãng phục vụ bạn.",
    "Lẻn vào phòng ngủ của các công chúa mỗi đêm, dùng dương vật vĩ đại để chinh phục và khiến họ lệ thuộc.",
    "Dùng 'Cường hóa Sinh lý' để có thể nện liên tục hàng trăm phụ nữ mỗi ngày mà không hề biết mệt mỏi.",
    "Thiết lập luật lệ: Mọi phụ nữ khi trưởng thành đều phải qua tay bạn kiểm tra vùng kín để được gieo giống.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y và vùng kín của mọi mỹ nhân đối diện.",
    "Khiến nữ thần bảo hộ thế giới phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Toàn cầu' khiến mọi phụ nữ trong vương quốc đều cảm thấy nứng và khao khát bạn.",
    "Trở thành 'Chúa tể Gieo giống Dâm uy', mọi mỹ nhân nhìn thấy bạn đều muốn được dâng hiến.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ hoàng và chiếm hữu nàng bất ngờ.",
    "Khiến nữ tướng mạnh nhất thế giới phải quỳ xuống phục vụ bạn trên thanh kiếm báu đã bị chinh phục."
  ],

  "Hội Mạo Hiểm Giả": [
    "Tại Hội Mạo Hiểm Giả, bạn yêu cầu nữ tiếp tân xinh đẹp nhất phải quỳ xuống phục vụ ngay tại quầy.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp giáp da của các nữ mạo hiểm giả, chiêm ngưỡng vùng kín.",
    "Biến nữ pháp sư của hội thành nô lệ tình dục trung thành phục vụ nhu cầu sinh lý của bạn mỗi đêm.",
    "Ép buộc nữ kiếm sĩ hạng S kiêu ngạo phải dâng hiến trinh tiết để được bạn dẫn dắt vào hầm ngục.",
    "Dùng 'Thao túng Cảm xúc' để biến sự lạnh lùng của các nữ thợ săn thành sự thèm khát bạn tột độ.",
    "Trong hầm ngục tối tăm, bạn thản nhiên chiếm hữu nữ linh mục ngay trước mặt đám quái vật.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ mạo hiểm giả.",
    "Biến phòng nghỉ của hội thành mật thất hoan lạc, nơi bạn và các mỹ nhân nện nắc suốt ngày đêm.",
    "Dùng danh tiếng để ép buộc các nữ mạo hiểm giả tân thủ phải qua đêm với bạn để được bảo hộ.",
    "Khiến nữ hội trưởng của hội phải mang thai giọt máu của bạn sau khi bị bạn chinh phục và chiếm hữu.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ nhân viên hội thành những con điếm phục vụ bạn.",
    "Lẻn vào phòng tắm của các nữ mạo hiểm giả mỗi đêm, dùng dương vật vĩ đại để chinh phục họ.",
    "Dùng 'Cường hóa Sinh lý' để có thể nện liên tục hàng chục mỹ nhân mạo hiểm giả mà không mệt mỏi.",
    "Thiết lập luật lệ: Mọi nữ mạo hiểm giả khi hoàn thành nhiệm vụ đều phải dâng hiến dâm thủy cho bạn.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y và vùng kín của mọi mỹ nhân trong hội.",
    "Khiến nữ anh hùng mạnh nhất hội phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Hội quán' khiến mọi mỹ nhân trong hội đều cảm thấy nứng và khao khát bạn.",
    "Trở thành 'Chúa tể Hội Mạo Hiểm Dâm uy', mọi mỹ nhân nhìn thấy bạn đều tự động phát tình.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ pháp sư và chiếm hữu nàng bất ngờ.",
    "Khiến nữ kiếm sĩ huyền thoại phải quỳ xuống phục vụ bạn trên tấm thẻ mạo hiểm giả đã bị chinh phục."
  ],
  "Lãnh chúa biên thùy": [
    "Là lãnh chúa biên thùy, bạn yêu cầu nữ sĩ quan xinh đẹp nhất phải cởi sạch đồ và phục vụ bạn.",
    "Dùng quyền lực lãnh chúa để biến nữ hiệp sĩ kiêu ngạo thành nô lệ tình dục phục vụ xác thịt.",
    "Lẻn vào phòng tắm của các nữ quan mỗi đêm, dùng dương vật vĩ đại để chinh phục và khiến họ lệ thuộc.",
    "Trong buổi dạ tiệc lãnh địa, bạn thản nhiên sờ soạng vùng kín của các tiểu thư ngay dưới gầm bàn.",
    "Dùng dị năng 'Thấu thị' lãnh chúa để chiêm ngưỡng cơ thể dâm mỹ của mọi nữ nô trong lãnh địa.",
    "Thiết lập một hậu cung gồm toàn những mỹ nhân tuyệt sắc nhất biên giới phục vụ dục vọng bạn.",
    "Yêu cầu nữ tướng quân vương quốc láng giềng phải dâng hiến trinh tiết để đổi lấy sự bảo hộ.",
    "Dùng 'Thao túng Cảm xúc' để biến sự thù ghét của nữ tù binh thành sự thèm khát bạn tột độ.",
    "Tổ chức những buổi tiệc dâm loạn trong mật thất, nơi các sĩ quan và mỹ nhân cùng hoan lạc.",
    "Là vị vua không vương miện, bạn có quyền gieo giống cho bất kỳ nữ nhân nào trong lãnh địa.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên chiếm hữu các nữ quan ngay giữa buổi duyệt binh.",
    "Khiến nữ thánh nữ của giáo hội địa phương phải quỳ xuống phục vụ lãnh chúa ngay trên sàn điện thờ.",
    "Dùng quyền lực để ép buộc nữ thợ săn mạnh nhất vùng phải mang thai giọt máu của bạn củng cố gia tộc.",
    "Lẻn vào phòng ngủ của các nữ sĩ quan mỗi đêm, dùng kỹ năng tuyệt đỉnh để khiến họ lệ thuộc bạn.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ hầu thành những con điếm phục vụ dương vật bạn.",
    "Thiết lập luật lệ: Mọi cô gái xinh đẹp trong lãnh địa khi trưởng thành đều phải qua tay lãnh chúa.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn vùng kín của mọi mỹ nhân trong buổi tiệc.",
    "Khiến nữ hoàng của bộ tộc bại trận phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng 'Cường hóa Sinh lý' lãnh chúa để có thể phục vụ toàn bộ dàn mỹ nhân mà không hề biết mệt mỏi.",
    "Trở thành 'Chúa tể Biên thùy Dâm uy', mọi mỹ nhân nhìn thấy bạn đều tự động phát tình."
  ],
  "Kẻ trộm thánh vật": [
    "Là kẻ trộm thánh vật, bạn yêu cầu nữ thánh nữ phải cởi sạch đồ và phục vụ để đổi lấy vật báu.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp y phục của các nữ tu sĩ, chiêm ngưỡng vùng kín.",
    "Biến nữ giáo hoàng kiêu ngạo thành nô lệ tình dục trung thành phục vụ nhu cầu xác thịt của bạn.",
    "Ép buộc nữ hiệp sĩ thánh điện phải dâng hiến trinh tiết để được bạn trả lại thánh vật đã tráo.",
    "Dùng 'Thao túng Cảm xúc' để biến sự thánh khiết của các nữ tu thành sự thèm khát bạn tột độ.",
    "Trong thánh điện tối cao, bạn thản nhiên chiếm hữu nữ thánh nữ ngay trước mặt tượng thần linh.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ tu ngay giữa đại lễ.",
    "Biến sào huyệt thành thiên đường hoan lạc, nơi bạn và các mỹ nhân thánh khiết cùng nện nắc.",
    "Dùng sự tinh quái để ép buộc các nữ hiệp sĩ phải qua đêm với bạn để lấy lại vật báu giáo hội.",
    "Khiến nữ giáo hoàng phải mang thai giọt máu của bạn để bôi nhọ sự thánh khiết và thống trị giáo hội.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ tu thành những con điếm phục vụ dương vật bạn.",
    "Lẻn vào phòng ngủ của các thánh nữ mỗi đêm, dùng dương vật vĩ đại để chinh phục họ.",
    "Dùng 'Cường hóa Sinh lý' để có thể nện liên tục hàng chục mỹ nhân thánh khiết mà không mệt mỏi.",
    "Thiết lập luật lệ: Mọi thánh vật bị trộm đều có thể chuộc lại bằng dâm thủy và sự dâng hiến thể xác.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y và vùng kín của mọi mỹ nhân thánh điện.",
    "Khiến nữ thần bảo hộ giáo hội phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Thánh điện' khiến mọi mỹ nhân giáo hội đều cảm thấy nứng và khao khát bạn.",
    "Trở thành 'Chúa tể Đạo tặc Dâm uy', mọi mỹ nhân nhìn thấy bạn đều tự động phát tình.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ giáo hoàng và chiếm hữu nàng bất ngờ.",
    "Khiến nữ thánh nữ cao quý nhất phải quỳ xuống phục vụ bạn trên thánh vật đã bị bạn chinh phục."
  ],
  "Pháp sư tối thượng": [
    "Là pháp sư tối thượng, bạn yêu cầu nữ hiệu trưởng học viện phải quỳ xuống phục vụ ngay trong phòng làm việc.",
    "Dùng ma pháp 'Thấu thị' để nhìn xuyên qua lớp áo choàng của các nữ pháp sư, chiêm ngưỡng vùng kín.",
    "Biến nữ phù thủy mạnh nhất lục địa thành nô lệ tình dục trung thành phục vụ nhu cầu của bạn.",
    "Ép buộc nữ pháp sư tập sự phải dâng hiến trinh tiết để được bạn truyền dạy ma pháp tối thượng.",
    "Dùng 'Thao túng Cảm xúc' để biến sự lạnh lùng của nữ phù thủy thành sự thèm khát bạn tột độ.",
    "Trong thư viện cấm, bạn thản nhiên chiếm hữu nữ pháp sư ngay trên những cuốn sách cổ đại.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ pháp sư giữa hội thảo.",
    "Biến tháp ma pháp thành thiên đường hoan lạc, nơi bạn và các mỹ nhân cùng nện nắc suốt đêm.",
    "Dùng quyền năng tối thượng để ép buộc các nữ pháp sư phải qua đêm với bạn để tăng cường ma lực.",
    "Khiến nữ hiệu trưởng học viện phải mang thai giọt máu của bạn để củng cố sự thống trị học viện.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ pháp sư thành những con điếm phục vụ dương vật bạn.",
    "Lẻn vào phòng tắm của các mỹ nhân ma pháp mỗi đêm, dùng dương vật vĩ đại để chinh phục họ.",
    "Dùng 'Cường hóa Sinh lý' để có thể nện liên tục hàng chục nữ pháp sư mà không hề biết mệt mỏi.",
    "Thiết lập luật lệ: Mọi nữ pháp sư khi đột phá cảnh giới đều phải dâng hiến dâm thủy cho bạn.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y và vùng kín của mọi nữ pháp sư.",
    "Khiến nữ thần ma pháp phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Ma pháp' khiến mọi mỹ nhân xung quanh đều cảm thấy nứng và khao khát bạn.",
    "Trở thành 'Chúa tể Pháp sư Dâm uy', mọi mỹ nhân nhìn thấy bạn đều tự động phát tình.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ phù thủy và chiếm hữu nàng bất ngờ.",
    "Khiến nữ pháp sư mạnh nhất phải quỳ xuống phục vụ bạn trên cây trượng ma pháp đã bị chinh phục."
  ],
  "Học Viện Hoàng Gia": [
    "Tại Học Viện Hoàng Gia, bạn yêu cầu nữ hội trưởng học sinh phải quỳ xuống phục vụ ngay giữa hành lang.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp đồng phục của các nữ sinh quý tộc, chiêm ngưỡng vùng kín.",
    "Biến nữ giáo sư xinh đẹp thành nô lệ tình dục trung thành phục vụ nhu cầu sinh lý của bạn.",
    "Ép buộc tiểu thư nhà công tước kiêu ngạo phải dâng hiến trinh tiết để được bạn giúp đỡ kỳ thi.",
    "Dùng 'Thao túng Cảm xúc' để biến sự khinh miệt của các nữ sinh thành sự thèm khát bạn tột độ.",
    "Trong thư viện học viện, bạn thản nhiên chiếm hữu nữ sinh quý tộc ngay trước mặt các học viên.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ sinh giữa lễ khai giảng.",
    "Biến ký túc xá nữ thành thiên đường hoan lạc, nơi bạn và các mỹ nhân quý tộc cùng nện nắc suốt đêm.",
    "Dùng danh tiếng để ép buộc các nữ sinh phải qua đêm với bạn để được gia nhập tổ đội mạnh nhất.",
    "Khiến nữ hội trưởng học sinh phải mang thai giọt máu của bạn để củng cố địa vị trong học viện.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ sinh thành những con điếm phục vụ dương vật bạn.",
    "Lẻn vào phòng tắm nữ mỗi đêm, dùng dương vật vĩ đại để chinh phục các tiểu thư quý tộc.",
    "Dùng 'Cường hóa Sinh lý' để có thể phục vụ toàn bộ dàn nữ sinh xinh đẹp mà không hề biết mệt mỏi.",
    "Thiết lập luật lệ: Mọi nữ sinh khi đạt thành tích xuất sắc đều phải dâng hiến dâm thủy cho nam thần học viện.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y và vùng kín của mọi mỹ nhân học viện.",
    "Khiến nữ giáo hoàng tương lai phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Học đường' khiến mọi nữ sinh xung quanh đều cảm thấy nứng và khao khát bạn.",
    "Trở thành 'Chúa tể Học viện Dâm uy', mọi mỹ nhân nhìn thấy bạn đều tự động phát tình.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ giáo sư và chiếm hữu nàng bất ngờ.",
    "Khiến nữ kiếm sĩ mạnh nhất học viện phải quỳ xuống phục vụ bạn trên thanh kiếm báu đã bị chinh phục."
  ],
  "Chợ nô lệ": [
    "Tại chợ nô lệ, bạn yêu cầu nữ hoàng bị thất thế phải quỳ xuống phục vụ ngay trên bục đấu giá.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp vải rách của các nữ nô lệ, chiêm ngưỡng vùng kín.",
    "Biến nữ chủ nô tàn bạo thành nô lệ tình dục trung thành phục vụ nhu cầu xác thịt của bạn.",
    "Ép buộc công chúa vương quốc bại trận phải dâng hiến trinh tiết để được bạn mua về bảo vệ.",
    "Dùng 'Thao túng Cảm xúc' để biến sự nhục nhã của các nữ nô lệ thành sự thèm khát bạn tột độ.",
    "Trong hầm ngục nô lệ, bạn thản nhiên chiếm hữu nữ vương quỷ ngay trước mặt đám lính canh.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ nô lệ giữa buổi đấu giá.",
    "Biến dinh thự thành thiên đường hoan lạc, nơi bạn và các mỹ nhân nô lệ cùng nện nắc suốt ngày đêm.",
    "Dùng sự giàu có để ép buộc các nữ nô lệ xinh đẹp nhất phải qua đêm với bạn để được hưởng đặc quyền.",
    "Khiến nữ hoàng bị bắt làm nô lệ phải mang thai giọt máu của bạn để củng cố sự thống trị tuyệt đối.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ nô lệ thành những con điếm phục vụ dương vật bạn.",
    "Lẻn vào khu hầm ngục nô lệ mỗi đêm, dùng dương vật vĩ đại để chinh phục các mỹ nhân lệ thuộc.",
    "Dùng 'Cường hóa Sinh lý' để có thể phục vụ toàn bộ dàn mỹ nhân nô lệ mà không hề biết mệt mỏi.",
    "Thiết lập luật lệ: Mọi nữ nô lệ mới đều phải qua tay bạn kiểm tra vùng kín trước khi định giá.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y và vùng kín của mọi mỹ nhân chợ nô lệ.",
    "Khiến nữ thần bảo hộ bộ tộc nô lệ phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Chợ Nô' khiến mọi mỹ nhân xung quanh đều cảm thấy nứng và khao khát bạn.",
    "Trở thành 'Chúa tể Nô lệ Dâm uy', mọi mỹ nhân bị xiềng xích nhìn thấy bạn đều tự động phát tình.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ chủ nô và chiếm hữu nàng bất ngờ.",
    "Khiến nữ chiến binh nô lệ mạnh nhất phải quỳ xuống phục vụ bạn trên chiếc xiềng xích đã bị chinh phục."
  ],
  "Thế giới Nữ Tôn Fantasy": [
    "Trong thế giới Nữ Tôn, bạn yêu cầu nữ vương phải quỳ xuống phục vụ ngay trên ngai vàng uy nghiêm.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp y phục của các nữ lãnh chúa, chiêm ngưỡng vùng kín.",
    "Biến nữ tướng quân mạnh nhất vương quốc thành nam sủng tình dục phục vụ nhu cầu của bạn mỗi đêm.",
    "Ép buộc công chúa xinh đẹp nhất phải dâng hiến trinh tiết để được bạn ban phước gieo giống.",
    "Dùng 'Thao túng Cảm xúc' để biến sự kiêu ngạo của các nữ quan thành sự thèm khát bạn tột độ.",
    "Trong cung điện Nữ Tôn, bạn thản nhiên chiếm hữu nữ lãnh chúa ngay trước mặt dàn nam sủng.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các mỹ nhân giữa lễ sắc phong.",
    "Biến tẩm cung thành thiên đường hoan lạc, nơi bạn và các nữ quan cùng nện nắc suốt ngày đêm.",
    "Dùng sự quý hiếm của bản thân để ép buộc các nữ chiến binh mạnh nhất phải qua đêm với bạn.",
    "Khiến nữ vương vương quốc Nữ Tôn phải mang thai giọt máu của bạn để củng cố địa vị nam nhân.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ vệ sĩ thành những con điếm phục vụ dương vật bạn.",
    "Lẻn vào phòng tắm của các công chúa mỗi đêm, dùng dương vật vĩ đại để chinh phục họ.",
    "Dùng 'Cường hóa Sinh lý' để có thể phục vụ toàn bộ dàn mỹ nhân cung điện Nữ Tôn mà không mệt mỏi.",
    "Thiết lập luật lệ: Mọi nữ quan khi thăng chức đều phải qua tay bạn kiểm tra vùng kín để được gieo giống.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y và vùng kín của mọi mỹ nhân Nữ Tôn.",
    "Khiến nữ thần bảo hộ vương quốc phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Nữ Tôn' khiến mọi mỹ nhân xung quanh đều cảm thấy nứng và khao khát bạn.",
    "Trở thành 'Chúa tể Nam Sủng Dâm uy', mọi nữ lãnh chúa nhìn thấy bạn đều tự động phát tình.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ vương và chiếm hữu nàng bất ngờ.",
    "Khiến nữ tướng quân mạnh nhất phải quỳ xuống phục vụ bạn trên thanh kiếm báu đã bị chinh phục."
  ],
  "Khan hiếm đàn ông (Epic)": [
    "Trong thế giới khan hiếm đàn ông quy mô Epic, bạn yêu cầu nữ hoàng vạn tộc phải quỳ xuống phục vụ ngay giữa đại hội.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp y phục của các nữ vương vạn tộc, chiêm ngưỡng vùng kín.",
    "Biến nữ thần vạn giới thành nô lệ tình dục trung thành phục vụ nhu cầu gieo giống của bạn.",
    "Ép buộc các nữ hoàng xinh đẹp nhất phải dâng hiến trinh tiết để duy trì nòi giống cho vạn tộc.",
    "Dùng 'Thao túng Cảm xúc' để biến sự tôn sùng của phái nữ thành sự thèm khát dương vật vĩ đại của bạn.",
    "Trong thánh địa vạn tộc, bạn thản nhiên chiếm hữu nữ vương ngay trước mặt hàng ngàn mỹ nhân.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ hoàng giữa yến tiệc.",
    "Biến dinh thự thành trung tâm gieo giống vĩ đại, nơi bạn là vị chúa tể duy nhất chiếm hữu phái nữ.",
    "Dùng sự khan hiếm tuyệt đối để ép buộc các mỹ nhân vạn tộc phải qua đêm với bạn để được gieo giống.",
    "Khiến nữ thần bảo hộ vạn giới phải mang thai giọt máu của bạn để tạo ra thế hệ nam nhân mới.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ vệ sĩ vạn tộc thành những con điếm phục vụ bạn.",
    "Lẻn vào phòng ngủ của các nữ vương mỗi đêm, dùng dương vật vĩ đại để chinh phục họ lệ thuộc.",
    "Dùng 'Cường hóa Sinh lý' để có thể nện liên tục hàng ngàn phụ nữ vạn tộc mà không hề biết mệt mỏi.",
    "Thiết lập luật lệ: Mọi nữ hoàng khi lên ngôi đều phải qua tay bạn kiểm tra vùng kín chính thống.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y và vùng kín của mọi mỹ nhân vạn tộc.",
    "Khiến nữ thần chiến tranh vạn giới phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu.",
    "Dùng ma pháp 'Kích dục Vạn Tộc' khiến mọi phụ nữ vạn giới đều cảm thấy nứng và khao khát bạn.",
    "Trở thành 'Chúa tể Gieo giống Vạn Tộc', mọi mỹ nhân nhìn thấy bạn đều tự động phát tình.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ hoàng và chiếm hữu nàng bất ngờ.",
    "Khiến nữ chiến binh mạnh nhất vạn tộc phải quỳ xuống phục vụ bạn trên thanh kiếm thánh đã bị chinh phục."
  ],
  "Thế giới tôn thờ dương vật": [
    "Trong thế giới tôn thờ dương vật, bạn thản nhiên yêu cầu nữ hoàng phải quỳ xuống bú cu ngay trên điện thờ tối cao.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp y phục thánh khiết của các nữ tư tế, chiêm ngưỡng vùng kín dâm mị rỉ nước.",
    "Biến nữ lãnh chủ bộ tộc kiêu ngạo thành một nô lệ tình dục trung thành tuyệt đối, chuyên phục vụ nhu cầu xác thịt của bạn.",
    "Ép buộc các nữ chiến binh mạnh nhất phải dâng hiến trinh tiết quý giá để được ban phước và tăng cường linh lực thần thánh.",
    "Dùng 'Thao túng Cảm xúc' để biến sự sùng bái của phái nữ thành sự thèm khát dương vật vĩ đại của bạn tột độ.",
    "Trong lễ hội tôn vinh dương vật trang nghiêm, bạn thản nhiên nện nắc nữ tư tế ngay trước mặt hàng ngàn mỹ nhân đang cầu nguyện.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các nữ quan ngay giữa buổi đại lễ phồn thực.",
    "Biến thánh địa của bộ tộc thành một thiên đường hoan lạc, nơi bạn và các mỹ nhân cùng nhau nện nắc suốt ngày đêm không nghỉ.",
    "Dùng địa vị thần linh của bản thân để ép buộc các mỹ nhân tuyệt sắc nhất phải qua đêm với bạn để được cứu rỗi linh hồn.",
    "Khiến nữ hoàng bộ tộc phải mang thai giọt máu của bạn để tạo ra một thế hệ nam nhân mới đầy sức mạnh thần thánh.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ tu sĩ thành những con điếm dâm đãng chỉ biết phục vụ dương vật bạn.",
    "Lẻn vào phòng ngủ của các nữ tư tế mỗi đêm, dùng dương vật vĩ đại để chinh phục và khiến họ hoàn toàn lệ thuộc vào bạn.",
    "Dùng 'Cường hóa Sinh lý' thần thánh để có thể nện liên tục hàng trăm phụ nữ mỗi ngày mà không hề biết mệt mỏi hay kiệt sức.",
    "Thiết lập luật lệ: Mọi phụ nữ khi trưởng thành đều phải qua tay bạn 'kiểm tra chất lượng' vùng kín để được ban phước gieo giống.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y ren và vùng kín của mọi mỹ nhân trong thánh địa nguy nga.",
    "Khiến nữ thần bảo hộ thế giới phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu và vấy bẩn thể xác.",
    "Dùng ma pháp 'Kích dục Thần thánh' khiến mọi phụ nữ trong vương quốc đều cảm thấy nứng và khao khát được bạn nện nắc.",
    "Trở thành 'Chúa tể Dâm uy Tối cao', nơi mọi mỹ nhân nhìn thấy bạn đều tự động phát tình và muốn được dâng hiến thân xác.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ hoàng và nện nàng bất ngờ trong sự hoảng loạn dâm đãng.",
    "Khiến nữ tướng mạnh nhất bộ tộc phải quỳ xuống liếm sạch tinh dịch của bạn trên thanh kiếm thánh đã bị bạn chinh phục."
  ],
  "Thợ săn tiền thưởng": [
    "Tình cờ va vào nữ tội phạm đang lẩn trốn, làm nàng ngã và bạn vô tình chạm vào bầu ngực căng tròn dưới lớp áo rách.",
    "Bạn tình cờ cứu được một nữ quý tộc bị bắt cóc bởi băng đảng, nàng nhìn bạn với ánh mắt thèm khát và muốn dâng hiến thân xác.",
    "Trong lúc truy đuổi mục tiêu, bạn tình cờ lạc vào phòng tắm của nữ bang chủ, vẻ đẹp khỏa thân của nàng khiến bạn nứng điên.",
    "Tình cờ nhặt được chiếc quần lót của nữ thợ săn đối thủ đánh rơi, bên trong còn vương mùi hương dâm mị nồng nàn.",
    "Trong lúc thám hiểm hang ổ tội phạm, bạn tình cờ thấy nữ sát thủ đang tắm suối với tư thế cực kỳ khiêu gợi.",
    "Tình cờ được phân làm cộng sự với nữ thợ săn tiền thưởng gợi cảm nhất lục địa trong một phi vụ nguy hiểm.",
    "Tình cờ thấy nữ mục tiêu đang loay hoay cởi bỏ y phục bị rách, bạn tiến lại giúp đỡ và vô tình chạm vào vùng nhạy cảm.",
    "Nữ tội phạm bị bạn bắt giữ khỏa thân quỳ dưới chân, nàng dùng miệng bú liếm dương vật bạn để cầu xin được thả tự do.",
    "Lọ thuốc 'Xuân Tình' bị vỡ trong hang ổ, khiến các nữ tội phạm đồng loạt phát tình và lao vào bạn cầu xin được nện.",
    "Cơn gió mạnh thổi bay váy của mọi mỹ nhân trong quán rượu thợ săn, lộ ra vùng kín hồng hào dâm mị trước mắt bạn.",
    "Bạn và nữ đối thủ bị nhốt trong một mật thất bẫy, nơi duy nhất để giải tỏa căng thẳng là giao hợp điên cuồng.",
    "Chiếc gương ma thuật bị vỡ, phản chiếu hình ảnh khỏa thân dâm đãng của mọi nữ thợ săn đang có mặt tại hội quán.",
    "Nữ sát thủ lẻn vào phòng trọ của bạn lúc nửa đêm, lén lút bú liếm dương vật bạn khi bạn đang ngủ say sau phi vụ.",
    "Nữ đối thủ lén lút nhìn trộm bạn tắm qua khe cửa, tay nàng không ngừng xoa nắn hạt le đang rỉ nước vì thèm khát.",
    "Nữ tội phạm lén lút dùng ma pháp tàng hình để vào phòng bạn, lén lút cọ xát vùng kín vào mặt bạn khi bạn đang ngủ.",
    "Các nữ thợ săn lén lút gửi những bức thư tình dâm đãng kèm theo chiếc quần lót ren đẫm dâm thủy cho bạn mỗi ngày.",
    "Nữ sát thủ lén lút thu thập tinh dịch của bạn sau mỗi lần giao chiến để làm kỷ niệm dâm đãng và thỏa mãn bản thân.",
    "Thế giới thợ săn tiền thưởng là nơi công lý và dục vọng luôn đan xen, nơi kẻ mạnh có quyền chiếm hữu mọi mỹ nhân.",
    "Sự nguy hiểm của nghề nghiệp mang lại cho bạn những cảm giác kích thích tột độ khi chinh phục những mỹ nhân tàn bạo nhất.",
    "Các lệnh truy nã không chỉ mang lại tiền bạc mà còn là cơ hội để chiếm hữu thể xác của những nữ tội phạm xinh đẹp.",
    "Danh tiếng của một thợ săn đào hoa là nỗi khiếp sợ của tội phạm nhưng lại là niềm khao khát của các nữ đồng nghiệp.",
    "Thế giới ngầm coi trọng sức mạnh, cả trong chiến đấu lẫn trong việc thỏa mãn những ham muốn xác thịt đen tối nhất.",
    "Luật lệ của thợ săn cho phép bạn có quyền chiếm hữu bất kỳ mục tiêu nào bạn bắt được để thỏa mãn dục vọng cá nhân.",
    "Sự khao khát được bảo vệ khiến các nữ tội phạm luôn sẵn sàng dâng hiến thể xác cho thợ săn mạnh mẽ nhất.",
    "[HỆ THỐNG]: Nhiệm vụ: Bắt giữ và biến 5 nữ tội phạm nguy hiểm nhất thành những nô lệ tình dục trung thành của bạn.",
    "[HỆ THỐNG]: Thông báo: Bạn nhận được danh hiệu 'Kẻ Săn Mỹ Nhân', tăng 100% khả năng quyến rũ các nữ thợ săn và tội phạm.",
    "[HỆ THỐNG]: Cảnh báo: Nữ sát thủ đang âm mưu dùng thân xác dâm mỹ để bẫy bạn và lấy lại số tiền thưởng khổng lồ.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp áo choàng của mọi nữ thợ săn để chiêm ngưỡng vùng kín dâm mị của họ.",
    "Dị năng 'Cường Hóa Sinh Lý' giúp bạn có thể nện liên tục hàng chục nữ tội phạm suốt đêm mà không biết mệt mỏi.",
    "Dùng dị năng 'Thao Túng Cảm Xúc' để biến sự hận thù của nữ tội phạm thành sự thèm khát dương vật tột độ.",
  ],
  "Đấu sư Arena": [
    "Tình cờ va vào nữ đấu sư trong phòng tập, làm nàng ngã và bạn vô tình chạm tay vào bầu ngực săn chắc đầy mồ hôi.",
    "Bạn tình cờ cứu được một nữ nô lệ đấu trường khỏi đám quái vật, nàng nhìn bạn với ánh mắt sùng bái và khao khát dâng hiến.",
    "Sau trận thắng, bạn tình cờ được mời vào phòng nghỉ của nữ chủ nhân đấu trường, vẻ đẹp quyền quý của nàng làm bạn nứng.",
    "Tình cờ nhặt được chiếc quần lót của nữ đấu sư đối thủ đánh rơi trong phòng thay đồ, bên trong còn vương mùi hương dâm mị.",
    "Trong lúc thám hiểm khu vực huấn luyện, bạn tình cờ thấy nữ chiến binh đang tắm suối với tư thế cực kỳ khiêu gợi.",
    "Tình cờ được phân làm cộng sự với nữ đấu sư mạnh nhất Arena trong một trận đấu đôi đầy kịch tính và kích thích.",
    "Tình cờ thấy nữ đấu sư đang loay hoay cởi bỏ giáp trụ bị rách, bạn tiến lại giúp đỡ và vô tình chạm vào vùng nhạy cảm.",
    "Nữ đối thủ bị bạn đánh bại khỏa thân quỳ phục trên sàn đấu, nàng dùng miệng bú liếm dương vật bạn trước sự chứng kiến của vạn người.",
    "Lọ thuốc 'Hưng Phấn Arena' bị vỡ trong phòng thay đồ, khiến các nữ đấu sư đồng loạt phát tình và lao vào bạn cầu xin được nện.",
    "Cơn gió mạnh thổi bay váy của mọi mỹ nhân trên khán đài ngay giữa trận chung kết, lộ ra vùng kín hồng hào dâm mị.",
    "Bạn và nữ đấu sư đối thủ bị nhốt trong một mật thất đấu trường, nơi duy nhất để giải tỏa căng thẳng là giao hợp điên cuồng.",
    "Chiếc gương ma thuật bị vỡ, phản chiếu hình ảnh khỏa thân dâm đãng của mọi nữ chiến binh đang có mặt tại Arena.",
    "Nữ đấu sư lẻn vào phòng nghỉ của bạn lúc nửa đêm, lén lút bú liếm dương vật bạn khi bạn đang ngủ say sau trận đấu.",
    "Nữ chủ nhân đấu trường lén lút nhìn trộm bạn tắm qua khe cửa, tay nàng không ngừng xoa nắn hạt le đang rỉ nước vì thèm khát.",
    "Nữ đối thủ lén lút dùng ma pháp tàng hình để vào phòng bạn, lén lút cọ xát vùng kín vào mặt bạn khi bạn đang ngủ say.",
    "Các nữ đấu sư lén lút gửi những bức thư tình dâm đãng kèm theo chiếc quần lót ren đẫm dâm thủy cho bạn mỗi ngày.",
    "Nữ chiến binh lén lút thu thập tinh dịch của bạn sau mỗi trận thắng để làm thuốc tăng cường sức mạnh và thỏa mãn bản thân.",
    "Thế giới Arena là nơi sức mạnh và sắc dục luôn song hành, nơi kẻ chiến thắng có quyền chiếm hữu mọi mỹ nhân bại trận.",
    "Sự khốc liệt của đấu trường mang lại cho bạn những cảm giác kích thích tột độ khi chinh phục những nữ chiến binh mạnh mẽ nhất.",
    "Các trận đấu không chỉ mang lại vinh quang mà còn là cơ hội để chiếm hữu thể xác của những mỹ nhân tuyệt sắc nhất.",
    "Danh tiếng của một đấu sư đào hoa là chìa khóa mở ra trái tim và thể xác của những nữ chủ nhân quyền lực nhất.",
    "Đấu trường Arena coi trọng sức mạnh, cả trong chiến đấu lẫn trong việc thỏa mãn những ham muốn xác thịt đen tối nhất.",
    "Luật lệ của Arena cho phép đấu sư chiến thắng có quyền chiếm hữu bất kỳ nữ đối thủ nào để thỏa mãn dục vọng cá nhân.",
    "Sự khao khát nam nhân mạnh mẽ khiến các nữ chiến binh Arena luôn sẵn sàng dâng hiến thể xác để được bảo vệ và yêu thương.",
    "[HỆ THỐNG]: Nhiệm vụ: Đánh bại và biến 5 nữ đấu sư mạnh nhất Arena thành những nô lệ tình dục trung thành và dâm đãng.",
    "[HỆ THỐNG]: Thông báo: Bạn nhận được danh hiệu 'Thần Đấu Trường', tăng 100% khả năng quyến rũ các nữ chiến binh và khán giả nữ.",
    "[HỆ THỐNG]: Cảnh báo: Nữ chủ nhân đấu trường đang âm mưu dùng thân xác dâm mỹ để trói buộc bạn lại Arena mãi mãi.",
    "Dị năng 'Thấu Thị' giúp bạn nhìn xuyên qua lớp giáp sắt của mọi nữ đấu sư để chiêm ngưỡng vùng kín dâm mị của họ.",
    "Dị năng 'Cường Hóa Sinh Lý' giúp bạn có thể nện liên tục hàng chục nữ chiến binh suốt đêm mà không biết mệt mỏi.",
    "Dùng dị năng 'Thao Túng Cảm Xúc' để biến sự kiêu ngạo của nữ đấu sư thành sự thèm khát dương vật tột độ.",
  ],
  "Thần linh hạ phàm": [
    "Là thần linh hạ phàm, bạn thản nhiên yêu cầu nữ hoàng phải quỳ xuống bú cu ngay giữa điện thờ thánh thiện.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua mọi lớp y phục thánh của các nữ thần, chiêm ngưỡng vùng kín dâm mị rỉ nước.",
    "Biến nữ tư tế cao quý nhất thành nô lệ tình dục, chuyên phục vụ nhu cầu ban phước xác thịt của bạn mỗi đêm.",
    "Ép buộc các thánh nữ phải dâng hiến trinh tiết để nhận được sự che chở thần thánh từ vị thần dâm dục là bạn.",
    "Dùng 'Thao túng Cảm xúc' để biến sự sùng bái của các nữ thần thành sự thèm khát dương vật vĩ đại của bạn tột độ.",
    "Trong thánh địa trang nghiêm, bạn thản nhiên nện nắc nữ thần sắc đẹp ngay trước mặt hàng vạn tín đồ đang quỳ lạy.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các mỹ nhân ngay giữa buổi lễ tế thần.",
    "Biến điện thờ của bạn thành một thiên đường hoan lạc, nơi bạn là vị thần duy nhất được mọi mỹ nhân dâng hiến thân xác.",
    "Dùng quyền năng thần thánh để ép buộc các nữ hoàng phải qua đêm với bạn để được 'ban phước' gieo giống thần linh.",
    "Khiến nữ thần bảo hộ thế giới phải mang thai giọt máu của bạn để tạo ra một kỷ nguyên mới thống trị bởi sắc dục.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ thiên sứ thành những con điếm dâm đãng chỉ biết phục vụ dương vật bạn.",
    "Lẻn vào phòng ngủ của các nữ thần mỗi đêm, dùng dương vật vĩ đại để chinh phục và khiến họ hoàn toàn lệ thuộc vào bạn.",
    "Dùng 'Cường hóa Sinh lý' để có thể nện liên tục hàng trăm mỹ nhân thiên giới mỗi ngày mà không hề biết mệt mỏi.",
    "Thiết lập luật lệ: Mọi nữ thần khi hạ phàm đều phải qua tay bạn 'kiểm tra linh lực' vùng kín để được ban phước.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y ren và vùng kín của mọi mỹ nhân trong thiên giới nguy nga.",
    "Khiến nữ thần tối cao phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu và vấy bẩn thể xác thần thánh.",
    "Dùng ma pháp 'Kích dục Thiên giới' khiến mọi mỹ nhân xung quanh đều cảm thấy nứng và khao khát được bạn nện nắc.",
    "Trở thành 'Chúa tể Thiên giới Dâm uy', nơi mọi mỹ nhân nhìn thấy bạn đều tự động phát tình và muốn được dâng hiến.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ thần mặt trăng và nện nàng bất ngờ trong sự hoảng loạn.",
    "Khiến nữ thần chiến tranh phải quỳ xuống liếm sạch tinh dịch của bạn trên thanh kiếm thánh đã bị bạn chinh phục."
  ],
  "Chuyển sinh thành NPC": [
    "Tình cờ va phải nữ anh hùng khi nàng đang vội vã đi làm nhiệm vụ cứu thế.",
    "Trong quán trọ, bạn tình cờ được nữ pháp sư nhờ mang nước ấm lên phòng tắm.",
    "Tình cờ nhặt được túi tiền của nữ mạo hiểm giả hạng S đánh rơi giữa chợ.",
    "Va phải nữ tu sĩ ở cổng thành, làm nàng rơi chiếc gậy phép thánh khiết.",
    "Tình cờ bắt gặp nữ sát thủ đang lẩn trốn trong đống rơm sau nhà bạn.",
    "Trong rừng, bạn tình cờ thấy nữ thợ săn đang loay hoay gỡ bẫy bị vướng vào chân.",
    "Tình cờ cứu được tiểu thư quý tộc khi xe ngựa của nàng bị hỏng bánh giữa đường.",
    "Nữ anh hùng bị trúng lời nguyền 'Dâm Đãng', nàng lao vào nhà bạn cầu xin được nện.",
    "Lọ thuốc ma thuật của nữ pháp sư phát nổ, làm quần áo của nàng tan biến ngay tại quán trọ.",
    "Cơn mưa bất chợt làm y phục của nữ tu sĩ trở nên trong suốt, lộ ra cơ thể dâm mỹ.",
    "Bẫy dâm dục trong rừng kích hoạt, trói chặt bạn và nữ thợ săn trong tư thế giao hợp.",
    "Sự cố dịch chuyển đưa nữ sát thủ rơi thẳng vào bồn tắm khi bạn đang khỏa thân.",
    "Nữ anh hùng lén lút lẻn vào phòng bạn mỗi đêm để tìm kiếm sự an ủi xác thịt bình dị.",
    "Nữ pháp sư lén lút dùng ma pháp để khiến bạn ngủ say rồi bò vào giường bú cu cho bạn.",
    "Nữ tu sĩ lén lút thu thập tinh dịch của bạn để làm 'thánh vật' thỏa mãn dục vọng thầm kín.",
    "Tiểu thư quý tộc lén lút nhìn trộm bạn làm việc qua cửa sổ, tay nàng không ngừng xoa lồn.",
    "Nữ sát thủ lén lút gửi những bức thư tình dâm đãng kèm theo quần lót ren cho bạn.",
    "Bạn chỉ là một nhân vật phụ không tên tuổi trong thế giới của những anh hùng và ma vương.",
    "Tuy nhiên, chính sự bình thường của bạn lại là thứ thu hút những mỹ nhân đang mệt mỏi vì chiến đấu.",
    "Thế giới này coi trọng sức mạnh, nhưng dục vọng lại là thứ san bằng mọi khoảng cách giai cấp.",
    "Các nữ anh hùng thường tìm đến những NPC như bạn để giải tỏa áp lực và tìm kiếm khoái lạc.",
    "Sự tồn tại của bạn là một biến số không ngờ tới trong kịch bản của thế giới này.",
    "Những ngôi làng nhỏ thường là nơi ẩn náu của những mỹ nhân đang chạy trốn khỏi định mệnh.",
    "NPC cũng có thể trở thành bá chủ nếu biết cách chinh phục trái tim và thể xác của các nữ chính.",
    "[HỆ THỐNG]: Nhiệm vụ: Biến nữ anh hùng thành người phụ nữ của riêng bạn trước khi nàng tiêu diệt ma vương.",
    "[HỆ THỐNG]: Thông báo: Bạn đã mở khóa kỹ năng 'NPC Nghịch Thiên', tăng 300% khả năng gieo giống.",
    "[HỆ THỐNG]: Cảnh báo: Nữ pháp sư đang có ý định dùng ma pháp để bắt cóc bạn về làm nô lệ tình dục.",
    "Dùng dị năng 'Thấu Thị' để thản nhiên ngắm nhìn vùng kín của các nữ mạo hiểm giả ghé qua quán trọ.",
    "Dị năng 'Cường Hóa Sinh Lực' giúp bạn có thể nện nắc nữ anh hùng suốt đêm mà không mệt mỏi.",
    "Sử dụng dị năng 'Thao Túng Cảm Xúc' để biến sự kiêu ngạo của tiểu thư thành sự sùng bái bạn.",
  ],
  "Chuyển sinh thành Ma vật": [
    "Là ma vật tiến hóa tối cao, bạn thản nhiên yêu cầu nữ anh hùng phải quỳ xuống bú cu ngay giữa hang ổ của mình.",
    "Dùng dị năng 'Thấu thị' để nhìn xuyên qua lớp giáp của các nữ mạo hiểm giả, chiêm ngưỡng vùng kín dâm mị rỉ nước.",
    "Biến nữ pháp sư thiên tài thành một nô lệ tình dục trung thành tuyệt đối, chuyên phục vụ nhu cầu xác thịt của bạn.",
    "Ép buộc các nữ thánh hiệp sĩ phải dâng hiến trinh tiết quý giá để được bạn tha mạng và cho phép rời khỏi hầm ngục.",
    "Dùng 'Thao túng Cảm xúc' để biến sự kinh tởm của các nữ anh hùng thành sự thèm khát dương vật vĩ đại của bạn tột độ.",
    "Trong hang động tối tăm, bạn thản nhiên nện nắc nữ tu sĩ ngay trước mặt các đồng đội của nàng đang bị xiềng xích.",
    "Dùng dị năng 'Ngưng đọng Thời gian' để thản nhiên sờ soạng vùng kín của các mỹ nhân ngay giữa lúc họ đang thám hiểm.",
    "Biến hầm ngục của bạn thành một thiên đường hoan lạc, nơi bạn và các nữ mạo hiểm giả cùng nhau nện nắc suốt đêm.",
    "Dùng sức mạnh ma vật tuyệt đối để ép buộc các mỹ nhân phải qua đêm với bạn để được bảo vệ khỏi các quái vật khác.",
    "Khiến nữ anh hùng mạnh nhất phải mang thai giọt máu của bạn để tạo ra một chủng tộc ma vật mới đầy quyền năng.",
    "Dùng dị năng 'Thôi miên' để biến toàn bộ dàn nữ mạo hiểm giả bị bắt thành những con điếm dâm đãng chỉ biết phục vụ bạn.",
    "Lẻn vào lều trại của các mỹ nhân mỗi đêm, dùng dương vật vĩ đại để chinh phục và khiến họ hoàn toàn lệ thuộc vào bạn.",
    "Dùng 'Cường hóa Sinh lý' để có thể nện liên tục hàng chục nữ mạo hiểm giả mỗi ngày mà không hề biết mệt mỏi.",
    "Thiết lập luật lệ: Mọi nữ chiến binh khi xâm nhập hầm ngục đều phải qua tay bạn 'kiểm tra tư cách' vùng kín.",
    "Dùng dị năng 'Nhìn xuyên Vật thể' để thản nhiên ngắm nhìn nội y ren và vùng kín của mọi mỹ nhân trong thế giới giả tưởng.",
    "Khiến nữ thần bảo hộ thế giới phải quỳ xuống làm nô lệ tình dục nhục nhã sau khi bị bạn chiếm hữu và vấy bẩn thể xác.",
    "Dùng ma pháp 'Kích dục Ma vật' khiến mọi mỹ nhân xung quanh đều cảm thấy nứng và khao khát được bạn nện nắc điên cuồng.",
    "Trở thành 'Chúa tể Ma vật Dâm uy', nơi mọi mỹ nhân nhìn thấy bạn đều tự động phát tình và muốn được dâng hiến thân xác.",
    "Dùng dị năng 'Thao túng Không gian' để lẻn vào bồn tắm của nữ pháp sư và nện nàng bất ngờ trong sự hoảng loạn dâm đãng.",
    "Khiến nữ anh hùng huyền thoại phải quỳ xuống liếm sạch tinh dịch của bạn trên thanh kiếm thánh đã bị bạn chinh phục."
  ],
  "Thợ săn Hầm ngục": [
    "Tình cờ va phải nữ thợ săn hạng S trong sảnh hiệp hội, làm nàng rơi thẻ định danh ma pháp.",
    "Trong lúc thám hiểm hầm ngục, bạn tình cờ đỡ được nữ pháp sư bị quái vật hất văng vào lòng.",
    "Tình cờ bắt gặp nữ trị thương đang thay đồ trong lều dã chiến sau một trận càn quét mệt mỏi.",
    "Va phải nữ sát thủ đang tàng hình trong bóng tối, làm lộ vị trí của nàng và bạn vô tình áp sát cơ thể nàng.",
    "Tình cờ nhặt được chiếc nhẫn ma pháp của nữ thợ săn đối thủ, khi trả lại nàng nhìn bạn đầy ngưỡng mộ.",
    "Trong khu vực an toàn của hầm ngục, bạn tình cờ ngồi cạnh nữ cung thủ đang ngủ gật vì kiệt sức.",
    "Tình cờ cứu được cô phóng viên chiến trường khỏi đám quái vật cấp thấp, nàng nhìn bạn như một vị thần.",
    "Sự cố 'Cửa Đột Biến' khiến y phục của mọi thợ săn nữ trong tổ đội tan biến ngay giữa trận chiến.",
    "Lọ thuốc 'Hồi Phục Cực Hạn' bị lỗi, khiến nữ thợ săn uống nhầm rơi vào trạng thái phát tình cuồng nhiệt.",
    "Bẫy ma thuật trong hầm ngục hạng S kích hoạt, trói chặt bạn và nữ thợ săn hạng A trong tư thế giao hợp.",
    "Cơn gió từ cánh cổng hầm ngục thổi bay váy của nữ nhân viên hiệp hội, lộ ra vùng kín hồng hào dâm mị.",
    "Sự cố dịch chuyển đưa bạn và nữ pháp sư vào một mật thất chật hẹp đầy mùi hương kích thích xác thịt.",
    "Nữ thợ săn hạng S lén lút lẻn vào phòng bạn mỗi đêm để bú cu nhằm tìm kiếm sự 'đột phá' sức mạnh.",
    "Nữ trị thương lén lút nhìn trộm bạn tắm qua khe cửa phòng thay đồ, tay nàng không ngừng xoa nắn hạt le.",
    "Nữ sát thủ lén lút dùng ma pháp tàng hình để vào phòng bạn nện nhau khi bạn đang giả vờ ngủ say.",
    "Nữ cung thủ lén lút gửi những bức thư tình dâm đãng kèm theo quần lót ren đẫm dâm thủy cho bạn.",
    "Nữ nhân viên hiệp hội lén lút thu thập tinh dịch của bạn sau mỗi lần kiểm tra sức mạnh để làm kỷ niệm.",
    "Thế giới hiện đại bỗng xuất hiện các hầm ngục, nơi sức mạnh thợ săn là thước đo của địa vị và sắc dục.",
    "Sự phân cấp hạng thợ săn tạo nên những luật lệ ngầm về việc chiếm hữu các mỹ nhân trong hiệp hội.",
    "Các hầm ngục không chỉ chứa báu vật mà còn là nơi diễn ra những cuộc hoan lạc bí mật của kẻ mạnh.",
    "Thợ săn hạng cao có quyền lực tuyệt đối, cho phép họ chọn bất kỳ mỹ nhân nào làm cộng sự giường chiếu.",
    "Ma pháp hầm ngục có thể biến những nữ thợ săn kiêu ngạo nhất thành những nô lệ tình dục dâm đãng.",
    "Thế giới đang đứng trước cuộc đại chiến hầm ngục, nơi thợ săn mạnh mẽ có quyền chiếm hữu mọi mỹ nhân.",
    "Những lời tiên tri về một 'Thợ Săn Tối Thượng' mang dương vật vĩ đại đang làm chấn động toàn cầu.",
    "[HỆ THỐNG]: Nhiệm vụ: Chinh phục nữ thợ săn hạng S mạnh nhất thế giới bằng kỹ năng giường chiếu của bạn.",
    "[HỆ THỐNG]: Thông báo: Bạn đã mở khóa kỹ năng 'Thợ Săn Dâm Uy', tăng 300% sức hút với các nữ pháp sư.",
    "[HỆ THỐNG]: Cảnh báo: Nữ thợ săn đối diện đang có ý định dùng thân xác để lôi kéo bạn vào bang hội của nàng.",
    "Dùng dị năng 'Thấu Thị' để nhìn xuyên qua lớp giáp ma pháp của mọi nữ thợ săn và chiêm ngưỡng vùng kín.",
    "Dị năng 'Thao Túng Cảm Xúc' giúp bạn biến sự lạnh lùng của nữ pháp sư thành sự thèm khát dương vật tột độ.",
    "Sử dụng dị năng 'Ngưng Đọng Thời Gian' để thoải mái nện nắc các mỹ nhân ngay giữa hầm ngục đang chiến đấu.",
  ],
  "Chúa tể Bóng tối": [
    "Tình cờ va phải nữ thủ lĩnh tổ chức bóng tối trong hẻm nhỏ, làm nàng rơi chiếc mặt nạ bí ẩn.",
    "Trong lúc diễn vai 'nhân vật quần chúng', bạn tình cờ cứu được công chúa khỏi đám sát thủ.",
    "Tình cờ bắt gặp nữ kiếm sĩ thiên tài đang luyện tập bí mật, vẻ đẹp của nàng làm bạn nứng điên.",
    "Tình cờ nhặt được chiếc trâm cài của nữ vương bóng tối, khi trả lại nàng nhìn bạn đầy sùng bái.",
    "Ngồi cạnh nữ pháp sư trong thư viện cấm, hơi thở nàng phả vào tai bạn đầy kích thích xác thịt.",
    "Thấy nữ sát thủ đang lẩn trốn trong bóng tối, nàng bị khí chất 'Chúa Tể' của bạn làm cho phát tình.",
    "Tình cờ đỡ được tiểu thư kiêu ngạo bị ngã, tay bạn vô tình bóp chặt bầu ngực căng tròn của nàng.",
    "Ma pháp 'Bóng Tối' bùng phát làm tan biến y phục của toàn bộ nữ thành viên trong tổ chức của bạn.",
    "Lọ thuốc kích dục hắc ám bị vỡ, khiến nữ thủ lĩnh rơi vào trạng thái dâm đãng và lao vào bạn.",
    "Bẫy dâm dục trong mật thất cổ đại kích hoạt, trói chặt bạn và công chúa trong tư thế giao hợp.",
    "Cơn gió ma thuật thổi bay váy của nữ kiếm sĩ, lộ ra vùng kín hồng hào dâm mị trước mắt bạn.",
    "Sự cố dịch chuyển đưa bạn và nữ vương bóng tối vào một không gian hẹp đầy mùi hương kích thích.",
    "Nữ thủ lĩnh lén lút lẻn vào giường bạn mỗi đêm để bú cu nhằm tìm kiếm sự 'khai sáng' từ Chúa Tể.",
    "Công chúa lén lút nhìn trộm bạn tắm qua khe cửa, tay nàng không ngừng xoa nắn hạt le rỉ nước dâm.",
    "Nữ pháp sư lén lút thu thập tinh dịch của bạn sau mỗi lần 'diễn kịch' để làm thuốc tăng cường ma lực.",
    "Tiểu thư lén lút gửi những bức thư tình dâm đãng kèm theo quần lót ren đẫm dâm thủy cho bạn.",
    "Nữ sát thủ lén lút cọ xát vùng kín vào mặt bạn khi bạn đang ngủ để cảm nhận hơi ấm của Chúa Tể.",
    "Thế giới này vận hành trong bóng tối, nơi bạn là kẻ thao túng mọi âm mưu và dục vọng của mỹ nhân.",
    "Sự bí ẩn của Chúa Tể Bóng Tối khiến mọi mỹ nhân kiêu ngạo nhất đều khao khát được bạn vấy bẩn.",
    "Tổ chức bóng tối của bạn tập trung những mỹ nhân tuyệt sắc nhất, sẵn sàng hiến dâng thân xác cho bạn.",
    "Kịch bản 'nhân vật quần chúng' là lớp vỏ hoàn hảo để bạn chiếm hữu mọi mỹ nhân trong hoàng cung.",
    "Sức mạnh hắc ám trong cơ thể bạn có khả năng kích thích những ham muốn đen tối nhất của phái nữ.",
    "Thế giới đang chờ đợi một vị vua bóng tối có thể thống trị vạn giới bằng sức mạnh và dục vọng.",
    "Những lời tiên tri về một 'Chúa Tể' mang dương vật vĩ đại đang làm chấn động toàn bộ lục địa.",
    "[HỆ THỐNG]: Nhiệm vụ: Xây dựng hậu cung bóng tối gồm 7 mỹ nhân mạnh nhất vương quốc.",
    "[HỆ THỐNG]: Thông báo: Bạn đã mở khóa kỹ năng 'Bóng Tối Dâm Uy', tăng 300% khả năng quyến rũ mỹ nhân.",
    "[HỆ THỐNG]: Cảnh báo: Nữ thủ lĩnh đang cực kỳ thèm khát dương vật của bạn, hãy ra tay chiếm hữu ngay.",
    "Dùng dị năng 'Thấu Thị' để nhìn xuyên qua lớp mặt nạ và y phục của mọi nữ thành viên trong tổ chức.",
    "Dị năng 'Thao Túng Cảm Xúc' giúp bạn biến sự trung thành của nữ sát thủ thành sự thèm khát xác thịt.",
    "Sử dụng dị năng 'Ngưng Đọng Thời Gian' để thoải mái nện nắc các mỹ nhân ngay giữa buổi họp bí mật.",
  ],
  "Sát thủ đệ nhất thế giới": [
    "Tình cờ va phải nữ pháp sư đồng hành trong lúc thực hiện nhiệm vụ ám sát, làm nàng rơi lọ thuốc độc.",
    "Trong lúc ẩn danh, bạn tình cờ cứu được tiểu thư công tước khỏi đám sát thủ đối thủ.",
    "Tình cờ bắt gặp nữ sát thủ địch đang tắm suối, vẻ đẹp khỏa thân của nàng làm bạn nứng điên.",
    "Tình cờ nhặt được chiếc khăn tay của công chúa, khi trả lại nàng nhìn bạn đầy ngưỡng mộ và dục vọng.",
    "Ngồi cạnh nữ hầu gái kiêm cộng sự trong quán trọ, hơi thở nàng phả vào tai bạn đầy kích thích.",
    "Thấy nữ tu sĩ đang cầu nguyện, nàng bị khí chất lạnh lùng của bạn làm cho phát tình cuồng nhiệt.",
    "Tình cờ đỡ được nữ hiệp sĩ bị ngất, tay bạn vô tình bóp chặt bầu ngực săn chắc của nàng.",
    "Ma pháp 'Ám Sát' bị lỗi làm tan biến y phục của toàn bộ nữ giới trong phạm vi nhiệm vụ.",
    "Lọ thuốc kích dục dùng để ám sát bị vỡ, khiến nữ pháp sư đồng hành rơi vào trạng thái dâm đãng.",
    "Bẫy dâm dục trong dinh thự mục tiêu kích hoạt, trói chặt bạn và tiểu thư công tước trong tư thế giao hợp.",
    "Cơn gió ma thuật thổi bay váy của nữ sát thủ địch, lộ ra vùng kín hồng hào dâm mị trước mắt bạn.",
    "Sự cố dịch chuyển đưa bạn và công chúa vào một mật thất chật hẹp đầy mùi hương kích thích xác thịt.",
    "Nữ hầu gái lén lút lẻn vào giường bạn mỗi đêm để bú cu nhằm 'rèn luyện' kỹ năng phục vụ Chúa Tể.",
    "Nữ pháp sư lén lút nhìn trộm bạn tắm qua gương ma thuật, tay nàng không ngừng xoa nắn hạt le rỉ nước.",
    "Tiểu thư lén lút thu thập tinh dịch của bạn sau mỗi lần bạn cứu nàng để làm kỷ niệm dâm đãng.",
    "Công chúa lén lút gửi những bức thư tình dâm đãng kèm theo quần lót ren đẫm dâm thủy cho bạn.",
    "Nữ sát thủ địch lén lút cọ xát vùng kín vào mặt bạn khi bạn đang ngủ để cầu xin một sự khoan hồng.",
    "Bạn là sát thủ đệ nhất được tái sinh để thực hiện nhiệm vụ ám sát anh hùng và chiếm hữu mỹ nhân.",
    "Sự lạnh lùng và kỹ năng ám sát hoàn hảo khiến mọi mỹ nhân đều khao khát được bạn chinh phục.",
    "Thế giới này đầy rẫy những âm mưu chính trị, nơi mỹ nhân là công cụ và cũng là phần thưởng cho bạn.",
    "Kỹ năng ám sát không chỉ dùng để giết người mà còn dùng để chiếm đoạt thể xác nữ giới một cách tinh vi.",
    "Sự kết hợp giữa ma pháp và kỹ năng sát thủ tạo nên những tình huống dâm đãng không thể cưỡng lại.",
    "Thế giới đang chờ đợi một vị vua sát thủ có thể thống trị vạn giới bằng sức mạnh và dục vọng đen tối.",
    "Những lời tiên tri về một 'Sát Thủ Tối Thượng' mang dương vật vĩ đại đang làm chấn động lục địa.",
    "[HỆ THỐNG]: Nhiệm vụ: Ám sát trái tim của 5 mỹ nhân quyền lực nhất vương quốc bằng dương vật của bạn.",
    "[HỆ THỐNG]: Thông báo: Bạn đã mở khóa kỹ năng 'Sát Thủ Dâm Uy', tăng 300% khả năng quyến rũ phái nữ.",
    "[HỆ THỐNG]: Cảnh báo: Nữ hầu gái đang cực kỳ thèm khát dương vật của bạn, hãy ra tay chiếm hữu ngay.",
    "Dùng dị năng 'Thấu Thị' để nhìn xuyên qua lớp y phục của mọi mục tiêu nữ và chiêm ngưỡng vùng kín.",
    "Dị năng 'Thao Túng Cảm Xúc' giúp bạn biến sự sợ hãi của mục tiêu thành sự thèm khát dương vật tột độ.",
    "Sử dụng dị năng 'Ngưng Đọng Thời Gian' để thoải mái nện nắc các mỹ nhân ngay giữa lúc ám sát mục tiêu.",
  ],
  "Chuyển sinh thành Slime": [
    "Tình cờ va phải nữ quỷ nhân trong hang động, cơ thể Slime của bạn bao trọn lấy bầu ngực nàng.",
    "Trong lúc dạo chơi, bạn tình cờ cứu được nữ tinh linh khỏi đám quái vật, nàng ôm lấy bạn đầy âu yếm.",
    "Tình cờ bắt gặp nữ chiến binh tộc rồng đang tắm suối, vẻ đẹp khỏa thân của nàng làm bạn nứng điên.",
    "Tình cờ nhặt được chiếc nhẫn của nữ vương tinh linh, khi trả lại nàng nhìn bạn đầy sùng bái.",
    "Ngồi cạnh nữ thư ký quỷ nhân trong văn phòng, hơi thở nàng phả vào tai bạn đầy kích thích.",
    "Thấy nữ sát thủ đang lẩn trốn, nàng bị khí chất 'Ma Vương' của bạn làm cho phát tình cuồng nhiệt.",
    "Tình cờ đỡ được tiểu thư tộc nhân bị ngã, tay bạn vô tình bóp chặt bầu ngực căng tròn của nàng.",
    "Kỹ năng 'Hấp Thụ' bị lỗi làm tan biến y phục của toàn bộ nữ giới trong vương quốc quái vật.",
    "Lọ thuốc kích dục ma pháp bị vỡ, khiến nữ thư ký rơi vào trạng thái dâm đãng và lao vào bạn.",
    "Bẫy dâm dục trong mê cung kích hoạt, trói chặt bạn và nữ tinh linh trong tư thế giao hợp nhục nhã.",
    "Cơn gió ma thuật thổi bay váy của nữ chiến binh tộc rồng, lộ ra vùng kín hồng hào dâm mị.",
    "Sự cố dịch chuyển đưa bạn và nữ vương tinh linh vào một không gian hẹp đầy mùi hương kích thích.",
    "Nữ thư ký lén lút lẻn vào giường bạn mỗi đêm để bú cu nhằm tìm kiếm sự 'tiến hóa' ma lực.",
    "Nữ tinh linh lén lút nhìn trộm bạn tắm qua khe cửa, tay nàng không ngừng xoa nắn hạt le rỉ nước.",
    "Nữ chiến binh tộc rồng lén lút thu thập tinh dịch của bạn sau mỗi trận chiến để làm thuốc tăng sức mạnh.",
    "Tiểu thư tộc nhân lén lút gửi những bức thư tình dâm đãng kèm theo quần lót ren đẫm dâm thủy cho bạn.",
    "Nữ sát thủ lén lút cọ xát vùng kín vào mặt bạn khi bạn đang ngủ để cảm nhận hơi ấm của Ma Vương.",
    "Bạn chuyển sinh thành Slime và xây dựng một vương quốc quái vật nơi mỹ nhân các tộc đều quy phục.",
    "Sự tiến hóa không ngừng mang lại cho bạn những hình dạng dâm mị khiến mọi mỹ nhân đều mê đắm.",
    "Vương quốc Tempest là nơi tập trung những mỹ nhân tuyệt sắc nhất đang chờ bạn chinh phục và chiếm hữu.",
    "Kỹ năng 'Đại Hiền Giả' không chỉ giúp bạn chiến đấu mà còn là công cụ hoàn hảo để thao túng sắc dục.",
    "Sự kết hợp giữa ma pháp và bản năng Slime tạo nên những tình huống dâm đãng không thể cưỡng lại.",
    "Thế giới đang chờ đợi một vị tân Ma Vương có thể thống trị vạn giới bằng sức mạnh và dục vọng.",
    "Những lời tiên tri về một 'Thần Slime' mang dương vật vĩ đại đang làm chấn động toàn bộ lục địa.",
    "[HỆ THỐNG]: Nhiệm vụ: Khiến toàn bộ nữ thủ lĩnh các tộc phải mang thai giọt máu của bạn để củng cố liên minh.",
    "[HỆ THỐNG]: Thông báo: Bạn đã mở khóa kỹ năng 'Slime Dâm Uy', tăng 300% khả năng quyến rũ phái nữ.",
    "[HỆ THỐNG]: Cảnh báo: Nữ thư ký đang cực kỳ thèm khát dương vật của bạn, hãy ra tay chiếm hữu ngay.",
    "Dùng dị năng 'Thấu Thị' để nhìn xuyên qua lớp giáp của mọi nữ chiến binh và chiêm ngưỡng vùng kín.",
    "Dị năng 'Thao Túng Cảm Xúc' giúp bạn biến sự kiêu ngạo của nữ vương thành sự thèm khát dương vật.",
    "Sử dụng dị năng 'Ngưng Đọng Thời Gian' để thoải mái nện nắc các mỹ nhân ngay giữa buổi họp quốc gia.",
  ],
  "Nông dân chuyển sinh": [
    "Tình cờ va phải nữ hiệp sĩ đang đi tuần qua trang trại, làm nàng ngã vào đống rơm đầy nhạy cảm.",
    "Trong lúc làm vườn, bạn tình cờ cứu được nữ pháp sư bị lạc khỏi đám thú dữ, nàng nhìn bạn đầy biết ơn.",
    "Tình cờ bắt gặp công chúa đang lén lút tắm suối trong khu vườn bí mật của bạn, vẻ đẹp của nàng làm bạn nứng.",
    "Tình cờ nhặt được chiếc khăn tay của nữ thần nông nghiệp, khi trả lại nàng nhìn bạn đầy dục vọng.",
    "Ngồi cạnh nữ hầu gái trong căn nhà gỗ, hơi thở nàng phả vào tai bạn đầy kích thích xác thịt.",
    "Thấy nữ sát thủ đang lẩn trốn trong vườn cây, nàng bị khí chất 'Nông Dân' của bạn làm cho phát tình.",
    "Tình cờ đỡ được tiểu thư bị ngã khi đang tham quan trang trại, tay bạn vô tình bóp chặt ngực nàng.",
    "Ma pháp 'Tăng Trưởng' bùng phát làm tan biến y phục của toàn bộ nữ giới đang có mặt tại trang trại.",
    "Lọ phân bón kích dục ma pháp bị vỡ, khiến nữ hiệp sĩ rơi vào trạng thái dâm đãng và lao vào bạn.",
    "Bẫy dâm dục trong kho nông sản kích hoạt, trói chặt bạn và công chúa trong tư thế giao hợp nhục nhã.",
    "Cơn gió từ cánh đồng thổi bay váy của nữ hầu gái, lộ ra vùng kín hồng hào dâm mị trước mắt bạn.",
    "Sự cố dịch chuyển đưa bạn và nữ thần nông nghiệp vào một hầm chứa lúa mì chật hẹp đầy mùi hương kích thích.",
    "Nữ hiệp sĩ lén lút lẻn vào trang trại của bạn mỗi đêm để bú cu nhằm đổi lấy những nông sản cực phẩm.",
    "Công chúa lén lút nhìn trộm bạn làm vườn qua khe cửa, tay nàng không ngừng xoa nắn hạt le rỉ nước dâm.",
    "Nữ hầu gái lén lút thu thập tinh dịch của bạn sau mỗi lần bạn thu hoạch để làm phân bón đặc biệt.",
    "Tiểu thư lén lút gửi những bức thư tình dâm đãng kèm theo quần lót ren đẫm dâm thủy cho bạn.",
    "Nữ sát thủ lén lút cọ xát vùng kín vào mặt bạn khi bạn đang ngủ để cảm nhận hơi ấm của đất mẹ.",
    "Thế giới nông nghiệp ma pháp nơi nông sản có thể điều khiển cảm xúc và dục vọng của mọi mỹ nhân.",
    "Sự kết hợp giữa canh tác hiện đại và ma pháp mang lại cho bạn khả năng chiếm hữu mọi mỹ nhân qua thực phẩm.",
    "Trang trại của bạn là nơi tập trung những mỹ nhân tuyệt sắc nhất đang khao khát cuộc sống bình yên và dục vọng.",
    "Nông sản của bạn không chỉ ngon mà còn là liều thuốc kích dục mạnh nhất thế giới khiến phái nữ mê đắm.",
    "Sự cạnh tranh giữa các nông dân thường dẫn đến những cuộc thi gieo giống dâm đãng để giành lấy danh hiệu.",
    "Thế giới đang chờ đợi một vị thần nông nghiệp có thể thống trị vạn giới bằng hương vị và dục vọng.",
    "Những lời tiên tri về một 'Thần Nông' mang dương vật vĩ đại đang làm chấn động toàn bộ lục địa.",
    "[HỆ THỐNG]: Nhiệm vụ: Khiến 5 nữ thánh nữ phải mang thai giọt máu của bạn sau khi thưởng thức nông sản của bạn.",
    "[HỆ THỐNG]: Thông báo: Bạn đã mở khóa kỹ năng 'Nông Nghiệp Dâm Uy', tăng 300% khả năng quyến rũ phái nữ.",
    "[HỆ THỐNG]: Cảnh báo: Nữ công chúa đang cực kỳ thèm khát dương vật của bạn, hãy ra tay chiếm hữu ngay.",
    "Dùng dị năng 'Thấu Thị' để nhìn xuyên qua y phục của mọi mỹ nhân đang tham quan trang trại của bạn.",
    "Dị năng 'Thao Túng Cảm Xúc' giúp bạn biến sự mệt mỏi của khách tham quan thành sự thèm khát xác thịt.",
    "Sử dụng dị năng 'Ngưng Đọng Thời Gian' để thoải mái nện nắc các mỹ nhân ngay giữa cánh đồng hoa rực rỡ.",
  ],
  "Thợ săn Goblin": [
    "Tình cờ va phải nữ tu sĩ đang bị đám Goblin bao vây, bạn xuất hiện như một vị thần cứu thế.",
    "Trong lúc săn lùng, bạn tình cờ cứu được nữ hiệp sĩ khỏi hang ổ Goblin, nàng nhìn bạn đầy sùng bái.",
    "Tình cờ bắt gặp nữ pháp sư đang tắm suối sau trận chiến, vẻ đẹp khỏa thân của nàng làm bạn nứng.",
    "Tình cờ nhặt được chiếc nhẫn của công chúa bị Goblin bắt cóc, khi trả lại nàng nhìn bạn đầy dục vọng.",
    "Ngồi cạnh nữ mạo hiểm giả trong quán trọ, hơi thở nàng phả vào tai bạn đầy kích thích xác thịt.",
    "Thấy nữ sát thủ đang bị thương do bẫy Goblin, nàng bị khí chất lạnh lùng của bạn làm cho phát tình.",
    "Tình cờ đỡ được tiểu thư bị ngã khi đang chạy trốn Goblin, tay bạn vô tình bóp chặt ngực nàng.",
    "Ma pháp 'Thanh Tẩy' bị lỗi làm tan biến y phục của toàn bộ nữ giới trong hang ổ Goblin.",
    "Lọ thuốc kích dục của đám Goblin bị vỡ, khiến nữ tu sĩ rơi vào trạng thái dâm đãng và lao vào bạn.",
    "Bẫy dâm dục của Goblin kích hoạt, trói chặt bạn và nữ hiệp sĩ trong tư thế giao hợp nhục nhã.",
    "Cơn gió từ hang động thổi bay váy của nữ pháp sư, lộ ra vùng kín hồng hào dâm mị trước mắt bạn.",
    "Sự cố dịch chuyển đưa bạn và công chúa vào một hầm ngục chật hẹp đầy mùi hương kích thích.",
    "Nữ tu sĩ lén lút lẻn vào phòng bạn mỗi đêm để bú cu nhằm cầu xin sự bảo vệ khỏi đám Goblin.",
    "Nữ hiệp sĩ lén lút nhìn trộm bạn tắm qua khe cửa, tay nàng không ngừng xoa nắn hạt le rỉ nước dâm.",
    "Nữ pháp sư lén lút thu thập tinh dịch của bạn sau mỗi trận chiến để làm thuốc tăng cường ma lực.",
    "Tiểu thư lén lút gửi những bức thư tình dâm đãng kèm theo quần lót ren đẫm dâm thủy cho bạn.",
    "Nữ sát thủ lén lút cọ xát vùng kín vào mặt bạn khi bạn đang ngủ để cảm nhận hơi ấm của thợ săn.",
    "Thế giới tàn khốc nơi Goblin là nỗi khiếp sợ và bạn là kẻ duy nhất có thể bảo vệ và chiếm hữu mỹ nhân.",
    "Sự lạnh lùng và kỹ năng tiêu diệt Goblin hoàn hảo khiến mọi mỹ nhân đều khao khát được bạn chinh phục.",
    "Các hang ổ Goblin là nơi tập trung những mỹ nhân bị bắt cóc xinh đẹp nhất đang chờ bạn giải cứu.",
    "Kỹ năng săn lùng không chỉ dùng để giết Goblin mà còn dùng để chiếm đoạt thể xác nữ giới một cách tinh vi.",
    "Sự kết hợp giữa ma pháp và kỹ năng chiến đấu tạo nên những tình huống dâm đãng không thể cưỡng lại.",
    "Thế giới đang chờ đợi một vị vua thợ săn có thể thống trị vạn giới bằng sức mạnh và dục vọng đen tối.",
    "Những lời tiên tri về một 'Sát Thần Goblin' mang dương vật vĩ đại đang làm chấn động lục địa.",
    "[HỆ THỐNG]: Nhiệm vụ: Giải cứu và chiếm hữu 10 mỹ nhân từ các hang ổ Goblin lớn nhất vương quốc.",
    "[HỆ THỐNG]: Thông báo: Bạn đã mở khóa kỹ năng 'Thợ Săn Dâm Uy', tăng 300% khả năng quyến rũ phái nữ.",
    "[HỆ THỐNG]: Cảnh báo: Nữ tu sĩ đang cực kỳ thèm khát dương vật của bạn, hãy ra tay chiếm hữu ngay.",
    "Dùng dị năng 'Thấu Thị' để nhìn xuyên qua lớp giáp của mọi nữ mạo hiểm giả và chiêm ngưỡng vùng kín.",
    "Dị năng 'Thao Túng Cảm Xúc' giúp bạn biến sự sợ hãi của nạn nhân thành sự thèm khát dương vật tột độ.",
    "Sử dụng dị năng 'Ngưng Đọng Thời Gian' để thoải mái nện nắc các mỹ nhân ngay giữa trận chiến Goblin.",
  ],
  "Xây dựng Vương quốc": [
    "Tình cờ va phải nữ tướng quân đang báo cáo tình hình chiến sự, làm nàng rơi bản đồ chiến lược.",
    "Trong buổi lễ khánh thành, bạn tình cờ cứu được nữ kiến trúc sư khỏi một vụ sập công trình ma pháp.",
    "Tình cờ bắt gặp nữ vương của vương quốc láng giềng đang tắm suối, vẻ đẹp của nàng làm bạn nứng.",
    "Tình cờ nhặt được chiếc trâm cài của công chúa tộc Elf, khi trả lại nàng nhìn bạn đầy sùng bái.",
    "Ngồi cạnh nữ thư ký thiên tài trong văn phòng chính vụ, hơi thở nàng phả vào tai bạn đầy kích thích.",
    "Thấy nữ sát thủ đang lẩn trốn trong hoàng cung, nàng bị khí chất 'Minh Quân' của bạn làm cho phát tình.",
    "Tình cờ đỡ được tiểu thư quý tộc bị ngã, tay bạn vô tình bóp chặt bầu ngực căng tròn của nàng.",
    "Ma pháp 'Thịnh Vượng' bùng phát làm tan biến y phục của toàn bộ nữ quan trong triều đình.",
    "Lọ rượu kích dục dùng trong yến tiệc bị đổ, khiến nữ tướng quân rơi vào trạng thái dâm đãng.",
    "Bẫy dâm dục trong mật thất hoàng cung kích hoạt, trói chặt bạn và công chúa Elf trong tư thế giao hợp.",
    "Cơn gió ma thuật thổi bay váy của nữ vương láng giềng, lộ ra vùng kín hồng hào dâm mị trước mắt bạn.",
    "Sự cố dịch chuyển đưa bạn và nữ thư ký vào một kho lưu trữ chật hẹp đầy mùi hương kích thích.",
    "Nữ tướng quân lén lút lẻn vào phòng bạn mỗi đêm để bú cu nhằm củng cố lòng trung thành tuyệt đối.",
    "Nữ kiến trúc sư lén lút nhìn trộm bạn tắm qua khe cửa, tay nàng không ngừng xoa nắn hạt le rỉ nước.",
    "Công chúa Elf lén lút thu thập tinh dịch của bạn sau mỗi lần bạn ban lệnh để làm thuốc tăng ma lực.",
    "Tiểu thư quý tộc lén lút gửi những bức thư tình dâm đãng kèm theo quần lót ren đẫm dâm thủy cho bạn.",
    "Nữ sát thủ lén lút cọ xát vùng kín vào mặt bạn khi bạn đang ngủ để cảm nhận hơi ấm của nhà vua.",
    "Bạn là một nhà lãnh đạo tài ba chuyển sinh để xây dựng một vương quốc hùng mạnh và hậu cung vĩ đại.",
    "Sự thông thái và quyết đoán của bạn khiến mọi mỹ nhân kiêu ngạo nhất đều muốn được bạn vấy bẩn.",
    "Vương quốc của bạn là nơi tập trung những mỹ nhân đa chủng tộc xinh đẹp nhất đang chờ bạn chinh phục.",
    "Chính sách đối ngoại của bạn không chỉ là ngoại giao mà còn là sự chiếm hữu thể xác các nữ lãnh đạo.",
    "Sự kết hợp giữa kiến thức hiện đại và ma pháp tạo nên những tình huống dâm đãng không thể cưỡng lại.",
    "Thế giới đang chờ đợi một vị hoàng đế tối thượng có thể thống trị vạn giới bằng sức mạnh và dục vọng.",
    "Những lời tiên tri về một 'Vua Của Các Vị Vua' mang dương vật vĩ đại đang làm chấn động lục địa.",
    "[HỆ THỐNG]: Nhiệm vụ: Kết hôn và chiếm hữu 7 nữ vương của các chủng tộc khác nhau để thống nhất lục địa.",
    "[HỆ THỐNG]: Thông báo: Bạn đã mở khóa kỹ năng 'Hoàng Đế Dâm Uy', tăng 300% khả năng quyến rũ phái nữ.",
    "[HỆ THỐNG]: Cảnh báo: Nữ tướng quân đang cực kỳ thèm khát dương vật của bạn, hãy ra tay chiếm hữu ngay.",
    "Dùng dị năng 'Thấu Thị' để nhìn xuyên qua y phục của mọi nữ quan trong triều đình và chiêm ngưỡng vùng kín.",
    "Dị năng 'Thao Túng Cảm Xúc' giúp bạn biến sự phản kháng của nữ vương thành sự thèm khát xác thịt.",
    "Sử dụng dị năng 'Ngưng Đọng Thời Gian' để thoải mái nện nắc các mỹ nhân ngay giữa buổi họp triều đình.",
  ],
  "Lăng mộ tối thượng": [
    "Tình cờ va phải nữ thủ vệ tầng trong hành lang lăng mộ, làm nàng rơi vũ khí ma pháp.",
    "Trong lúc tuần tra, bạn tình cờ cứu được nữ pháp sư loài người khỏi đám quái vật, nàng nhìn bạn đầy sợ hãi.",
    "Tình cờ bắt gặp nữ chiến đấu hầu gái đang tắm trong hồ nước ma thuật, vẻ đẹp của nàng làm bạn nứng.",
    "Tình cờ nhặt được chiếc trâm cài của nữ vương tinh linh, khi trả lại nàng nhìn bạn đầy sùng bái.",
    "Ngồi cạnh nữ giám thủ thủ vệ trong phòng ngai vàng, hơi thở nàng phả vào tai bạn đầy kích thích.",
    "Thấy nữ sát thủ loài người đang lẩn trốn, nàng bị khí chất 'Chúa Tể' của bạn làm cho phát tình.",
    "Tình cờ đỡ được tiểu thư loài người bị ngã, tay bạn vô tình bóp chặt bầu ngực căng tròn của nàng.",
    "Ma pháp 'Siêu Cấp' bùng phát làm tan biến y phục của toàn bộ nữ giới trong lăng mộ Nazarick.",
    "Lọ thuốc kích dục hắc ám bị vỡ, khiến nữ thủ vệ tầng rơi vào trạng thái dâm đãng và lao vào bạn.",
    "Bẫy dâm dục trong hầm ngục tối tăm kích hoạt, trói chặt bạn và nữ pháp sư trong tư thế giao hợp.",
    "Cơn gió ma thuật thổi bay váy của nữ chiến đấu hầu gái, lộ ra vùng kín hồng hào dâm mị trước mắt bạn.",
    "Sự cố dịch chuyển đưa bạn và nữ vương tinh linh vào một không gian hẹp đầy mùi hương kích thích.",
    "Nữ giám thủ lén lút lẻn vào giường bạn mỗi đêm để bú cu nhằm thể hiện lòng trung thành tuyệt đối.",
    "Nữ thủ vệ tầng lén lút nhìn trộm bạn tắm qua gương ma thuật, tay nàng không ngừng xoa nắn hạt le rỉ nước.",
    "Nữ chiến đấu hầu gái lén lút thu thập tinh dịch của bạn sau mỗi lần bạn ban lệnh để làm thuốc tăng ma lực.",
    "Tiểu thư loài người lén lút gửi những bức thư tình dâm đãng kèm theo quần lót ren đẫm dâm thủy cho bạn.",
    "Nữ sát thủ lén lút cọ xát vùng kín vào mặt bạn khi bạn đang ngủ để cầu xin sự khoan hồng của Chúa Tể.",
    "Bạn là Chúa Tể tối thượng của lăng mộ Nazarick, nắm giữ quyền sinh sát và dục vọng của vạn vật.",
    "Sự bá đạo và sức mạnh tuyệt đối của bạn khiến mọi mỹ nhân đều khao khát được bạn vấy bẩn và chiếm hữu.",
    "Lăng mộ Nazarick là nơi tập trung những mỹ nhân quái vật tuyệt sắc nhất đang chờ bạn chinh phục.",
    "Quyền lực của Chúa Tể là vô hạn, cho phép bạn biến mọi nữ giới thành nô lệ tình dục của mình.",
    "Sự kết hợp giữa ma pháp siêu cấp và uy nghiêm của vị vua tạo nên những tình huống dâm đãng tột độ.",
    "Thế giới đang chờ đợi một vị thần bóng tối có thể thống trị vạn giới bằng sức mạnh và dục vọng.",
    "Những lời tiên tri về một 'Chúa Tể Xương' mang dương vật vĩ đại đang làm chấn động toàn bộ lục địa.",
    "[HỆ THỐNG]: Nhiệm vụ: Khiến toàn bộ dàn nữ thủ vệ tầng phải mang thai giọt máu của bạn để tạo ra thế hệ mới.",
    "[HỆ THỐNG]: Thông báo: Bạn đã mở khóa kỹ năng 'Chúa Tể Dâm Uy', tăng 300% khả năng quyến rũ phái nữ.",
    "[HỆ THỐNG]: Cảnh báo: Nữ giám thủ đang cực kỳ thèm khát dương vật của bạn, hãy ra tay chiếm hữu ngay.",
    "Dùng dị năng 'Thấu Thị' để nhìn xuyên qua y phục của mọi nữ giới trong lăng mộ và chiêm ngưỡng vùng kín.",
    "Dị năng 'Thao Túng Cảm Xúc' giúp bạn biến sự trung thành của thuộc hạ thành sự thèm khát xác thịt.",
    "Sử dụng dị năng 'Ngưng Đọng Thời Gian' để thoải mái nện nắc các mỹ nhân ngay giữa buổi họp thủ vệ.",
  ],
  "Học viện Anh hùng": [
    "Tình cờ va phải nữ sinh cùng lớp trong hành lang học viện, làm nàng rơi cuốn sổ tay anh hùng.",
    "Trong buổi huấn luyện, bạn tình cờ cứu được nữ giáo sư khỏi một vụ nổ năng lượng ma pháp.",
    "Tình cờ bắt gặp nữ sinh thiên tài đang tắm suối nước nóng, vẻ đẹp khỏa thân của nàng làm bạn nứng.",
    "Tình cờ nhặt được chiếc trâm cài của công chúa vương quốc, khi trả lại nàng nhìn bạn đầy sùng bái.",
    "Ngồi cạnh nữ sinh có năng lực tàng hình trong lớp, hơi thở nàng phả vào tai bạn đầy kích thích.",
    "Thấy nữ sát thủ đang lẩn trốn trong trường, nàng bị khí chất 'Anh Hùng' của bạn làm cho phát tình.",
    "Tình cờ đỡ được tiểu thư kiêu ngạo bị ngã, tay bạn vô tình bóp chặt bầu ngực căng tròn của nàng.",
    "Năng lực 'Bộc Phát' bị lỗi làm tan biến y phục của toàn bộ nữ sinh trong lớp học anh hùng.",
    "Lọ thuốc tăng cường năng lực kích dục bị vỡ, khiến nữ sinh cùng lớp rơi vào trạng thái dâm đãng.",
    "Bẫy dâm dục trong phòng tập giả lập kích hoạt, trói chặt bạn và nữ giáo sư trong tư thế giao hợp.",
    "Cơn gió từ năng lực điều khiển không khí thổi bay váy của nữ sinh thiên tài, lộ ra vùng kín dâm mị.",
    "Sự cố dịch chuyển đưa bạn và công chúa vào một không gian hẹp đầy mùi hương kích thích xác thịt.",
    "Nữ sinh cùng lớp lén lút lẻn vào phòng bạn mỗi đêm để bú cu nhằm tìm kiếm sự 'hỗ trợ' năng lượng.",
    "Nữ giáo sư lén lút nhìn trộm bạn tắm qua camera giám sát, tay nàng không ngừng xoa nắn hạt le rỉ nước.",
    "Nữ sinh thiên tài lén lút thu thập tinh dịch của bạn sau mỗi lần huấn luyện để nghiên cứu gen anh hùng.",
    "Tiểu thư kiêu ngạo lén lút gửi những bức thư tình dâm đãng kèm theo quần lót ren đẫm dâm thủy cho bạn.",
    "Nữ sát thủ lén lút cọ xát vùng kín vào mặt bạn khi bạn đang ngủ để cảm nhận hơi ấm của anh hùng.",
    "Bạn chuyển sinh vào học viện anh hùng với năng lực tối thượng và khao khát chiếm hữu mọi mỹ nhân.",
    "Sự dũng cảm và sức mạnh của bạn khiến mọi nữ sinh đều khao khát được bạn bảo vệ và vấy bẩn.",
    "Học viện Anh Hùng là nơi tập trung những mỹ nhân ưu tú nhất đang chờ bạn chinh phục và chiếm hữu.",
    "Năng lực anh hùng không chỉ dùng để cứu người mà còn là công cụ hoàn hảo để xây dựng hậu cung.",
    "Sự kết hợp giữa công nghệ và năng lực tạo nên những tình huống dâm đãng không thể cưỡng lại.",
    "Thế giới đang chờ đợi một vị anh hùng tối thượng có thể thống trị vạn giới bằng sức mạnh và dục vọng.",
    "Những lời tiên tri về một 'Anh Hùng Vĩ Đại' mang dương vật vĩ đại đang làm chấn động toàn bộ học viện.",
    "[HỆ THỐNG]: Nhiệm vụ: Khiến toàn bộ dàn nữ sinh trong lớp A phải mang thai giọt máu của bạn.",
    "[HỆ THỐNG]: Thông báo: Bạn đã mở khóa kỹ năng 'Anh Hùng Dâm Uy', tăng 300% khả năng quyến rũ phái nữ.",
    "[HỆ THỐNG]: Cảnh báo: Nữ sinh cùng lớp đang cực kỳ thèm khát dương vật của bạn, hãy ra tay chiếm hữu ngay.",
    "Dùng dị năng 'Thấu Thị' để nhìn xuyên qua trang phục anh hùng của mọi nữ sinh và chiêm ngưỡng vùng kín.",
    "Dị năng 'Thao Túng Cảm Xúc' giúp bạn biến sự ngưỡng mộ của phái nữ thành sự thèm khát xác thịt tột độ.",
    "Sử dụng dị năng 'Ngưng Đọng Thời Gian' để thoải mái nện nắc các mỹ nhân ngay giữa buổi lễ tốt nghiệp.",
  ],
  "Chủ nhân Hầm ngục": [
    "Tình cờ va phải nữ mạo hiểm giả đang xâm nhập hầm ngục của bạn, làm nàng rơi bản đồ kho báu.",
    "Trong lúc đặt bẫy, bạn tình cờ cứu được nữ pháp sư khỏi một con quái vật nổi loạn, nàng nhìn bạn đầy sợ hãi.",
    "Tình cờ bắt gặp nữ thánh nữ đang tắm trong hồ nước thánh của hầm ngục, vẻ đẹp của nàng làm bạn nứng.",
    "Tình cờ nhặt được chiếc trâm cài của công chúa bị lạc trong mê cung, khi trả lại nàng nhìn bạn đầy sùng bái.",
    "Ngồi cạnh nữ sát thủ trong phòng điều khiển hầm ngục, hơi thở nàng phả vào tai bạn đầy kích thích.",
    "Thấy nữ hiệp sĩ đang bị sập bẫy, nàng bị khí chất 'Dungeon Master' của bạn làm cho phát tình cuồng nhiệt.",
    "Tình cờ đỡ được tiểu thư bị ngã trong hầm ngục, tay bạn vô tình bóp chặt bầu ngực căng tròn của nàng.",
    "Ma pháp 'Tái Cấu Trúc Hầm Ngục' bùng phát làm tan biến y phục của toàn bộ nữ mạo hiểm giả.",
    "Lọ thuốc kích dục dùng làm bẫy bị vỡ, khiến nữ thánh nữ rơi vào trạng thái dâm đãng và lao vào bạn.",
    "Bẫy dâm dục trong mật thất hầm ngục kích hoạt, trói chặt bạn và nữ pháp sư trong tư thế giao hợp.",
    "Cơn gió từ hầm sâu thổi bay váy của nữ hiệp sĩ, lộ ra vùng kín hồng hào dâm mị trước mắt bạn.",
    "Sự cố dịch chuyển đưa bạn và công chúa vào một mật thất chật hẹp đầy mùi hương kích thích xác thịt.",
    "Nữ mạo hiểm giả lén lút lẻn vào phòng ngủ của bạn mỗi đêm để bú cu nhằm cầu xin sự tha mạng.",
    "Nữ thánh nữ lén lút nhìn trộm bạn điều khiển hầm ngục qua khe cửa, tay nàng không ngừng xoa nắn hạt le.",
    "Nữ pháp sư lén lút thu thập tinh dịch của bạn sau mỗi lần bạn ban lệnh để làm thuốc tăng ma lực.",
    "Tiểu thư lén lút gửi những bức thư tình dâm đãng kèm theo quần lót ren đẫm dâm thủy cho bạn.",
    "Nữ sát thủ lén lút cọ xát vùng kín vào mặt bạn khi bạn đang ngủ để cảm nhận hơi ấm của chủ nhân.",
    "Bạn là chủ nhân hầm ngục tối thượng, nắm giữ quyền điều khiển và dục vọng của mọi kẻ xâm nhập.",
    "Sự bá đạo và trí tuệ của bạn khiến mọi mỹ nhân mạo hiểm giả đều khao khát được bạn chinh phục.",
    "Hầm ngục của bạn là nơi tập trung những mỹ nhân tuyệt sắc nhất đang chờ bạn giải cứu hoặc chiếm hữu.",
    "Hệ thống hầm ngục không chỉ dùng để phòng thủ mà còn là công cụ hoàn hảo để xây dựng hậu cung.",
    "Sự kết hợp giữa ma pháp và bẫy dâm dục tạo nên những tình huống hoan lạc điên cuồng trong hầm ngục.",
    "Thế giới đang chờ đợi một vị vua hầm ngục tối thượng có thể thống trị vạn giới bằng sức mạnh và dục vọng.",
    "Những lời tiên tri về một 'Dungeon Master' mang dương vật vĩ đại đang làm chấn động toàn bộ lục địa.",
    "[HỆ THỐNG]: Nhiệm vụ: Bắt giữ và chiếm hữu 10 nữ anh hùng mạnh nhất đang cố gắng phá đảo hầm ngục của bạn.",
    "[HỆ THỐNG]: Thông báo: Bạn đã mở khóa kỹ năng 'Hầm Ngục Dâm Uy', tăng 300% khả năng quyến rũ phái nữ.",
    "[HỆ THỐNG]: Cảnh báo: Nữ thánh nữ đang cực kỳ thèm khát dương vật của bạn, hãy ra tay chiếm hữu ngay.",
    "Dùng dị năng 'Thấu Thị' để nhìn xuyên qua y phục của mọi nữ mạo hiểm giả đang di chuyển trong hầm ngục.",
    "Dị năng 'Thao Túng Cảm Xúc' giúp bạn biến sự sợ hãi của nạn nhân thành sự thèm khát xác thịt tột độ.",
    "Sử dụng dị năng 'Ngưng Đọng Thời Gian' để thoải mái nện nắc các mỹ nhân ngay giữa lúc họ đang sập bẫy.",
  ],
  "Chuyển sinh thành Rồng": [
    "Tình cờ va phải nữ mạo hiểm giả trong hang động, làm nàng rơi chiếc vảy rồng quý giá.",
    "Trong lúc bảo vệ lãnh địa, bạn tình cờ cứu được nữ pháp sư khỏi một vụ tấn công của thợ săn rồng.",
    "Tình cờ bắt gặp nữ tinh linh đang tắm suối trong rừng sâu, vẻ đẹp khỏa thân của nàng làm bạn nứng.",
    "Tình cờ nhặt được chiếc trâm cài của công chúa vương quốc, khi trả lại nàng nhìn bạn đầy dục vọng.",
    "Ngồi cạnh nữ sát thủ trong bóng tối của hang rồng, hơi thở nàng phả vào tai bạn đầy kích thích.",
    "Thấy nữ hiệp sĩ đang bị thương, nàng bị khí chất 'Long Vương' của bạn làm cho phát tình cuồng nhiệt.",
    "Tình cờ đỡ được tiểu thư nhà giàu bị ngã, tay bạn vô tình bóp chặt bầu ngực căng tròn của nàng.",
    "Hơi thở rồng 'Dâm Dục' bùng phát làm tan biến y phục của toàn bộ nữ giới trong phạm vi hang động.",
    "Lọ thuốc kích dục dùng cho rồng bị vỡ, khiến nữ mạo hiểm giả rơi vào trạng thái dâm đãng và lao vào bạn.",
    "Bẫy dâm dục trong kho báu rồng kích hoạt, trói chặt bạn và nữ pháp sư trong tư thế giao hợp nhục nhã.",
    "Cơn gió từ cánh rồng thổi bay váy của nữ tinh linh, lộ ra vùng kín hồng hào dâm mị trước mắt bạn.",
    "Sự cố dịch chuyển đưa bạn và công chúa vào một không gian hẹp đầy mùi hương kích thích xác thịt.",
    "Nữ mạo hiểm giả lén lút lẻn vào hang rồng mỗi đêm để bú cu nhằm cầu xin sự ban phước của rồng.",
    "Nữ pháp sư lén lút nhìn trộm bạn tắm (dạng người) qua khe cửa, tay nàng không ngừng xoa nắn hạt le.",
    "Nữ tinh linh lén lút thu thập tinh dịch của bạn sau mỗi lần giúp đỡ để làm thuốc tăng cường linh lực.",
    "Tiểu thư lén lút gửi những bức thư tình dâm đãng kèm theo quần lót ren đẫm dâm thủy cho bạn.",
    "Nữ sát thủ lén lút cọ xát vùng kín vào mặt bạn khi bạn đang ngủ để cảm nhận hơi ấm của rồng.",
    "Bạn là một con rồng chuyển sinh với sức mạnh tối thượng và khao khát chiếm hữu mọi mỹ nhân thế giới.",
    "Sự uy nghiêm và sức mạnh của Long Vương khiến mọi nữ giới đều khao khát được bạn bảo vệ và vấy bẩn.",
    "Thế giới này tôn sùng loài rồng, nơi các mỹ nhân sẵn sàng hiến dâng tất cả để được mang dòng máu rồng.",
    "Sức mạnh rồng không chỉ dùng để chiến đấu mà còn là công cụ hoàn hảo để xây dựng một hậu cung.",
    "Sự kết hợp giữa ma pháp rồng và bản năng tạo nên những tình huống dâm đãng không thể cưỡng lại.",
    "Thế giới đang chờ đợi một vị Long Vương tối thượng có thể thống trị vạn giới bằng sức mạnh và dục vọng.",
    "Những lời tiên tri về một 'Thần Rồng' mang dương vật vĩ đại đang làm chấn động toàn bộ lục địa.",
    "[HỆ THỐNG]: Nhiệm vụ: Chiếm hữu và khiến 5 nữ vương của các chủng tộc khác nhau phải mang thai.",
    "[HỆ THỐNG]: Thông báo: Bạn đã mở khóa kỹ năng 'Long Vương Dâm Uy', tăng 300% khả năng quyến rũ phái nữ.",
    "[HỆ THỐNG]: Cảnh báo: Nữ mạo hiểm giả đang cực kỳ thèm khát dương vật của bạn, hãy ra tay chiếm hữu ngay.",
    "Dùng dị năng 'Thấu Thị' để nhìn xuyên qua trang phục của mọi mỹ nhân và chiêm ngưỡng vùng kín dâm mị.",
    "Dị năng 'Thao Túng Cảm Xúc' giúp bạn biến sự sợ hãi của nạn nhân thành sự thèm khát xác thịt tột độ.",
    "Sử dụng dị năng 'Ngưng Đọng Thời Gian' để thoải mái nện nắc các mỹ nhân ngay giữa kho báu rồng.",
  ],
};

export const IDENTITIES: string[] = Object.entries(RAW_DATA).flatMap(([context, scenarios]) => 
  scenarios.map(s => `Bối cảnh: ${context} - ${s}`)
);

export const SPECIALIZED_DATA: Record<string, { label: string, action: string }[]> = {};
