export const CUSTOM_URBAN_NORMAL = [
  { title: "Thần y ở rể", tag: "Vả mặt", color: "text-emerald-400" },
  { title: "Vua lừa đảo quốc tế", tag: "Trí tuệ", color: "text-cyan-400" },
  { title: "Đứa con rơi của Tài phiệt", tag: "Hào môn", color: "text-yellow-400" },
  { title: "Sát thủ mất trí nhớ", tag: "Bí ẩn", color: "text-red-400" },
  { title: "Thiên tài đầu tư 16 tuổi", tag: "Huyền thoại", color: "text-indigo-400" },
  { title: "Kẻ thu mua tập đoàn", tag: "Quyền lực", color: "text-purple-400" },
  { title: "Bảo vệ trường nữ sinh", tag: "Harem", color: "text-pink-400" },
  { title: "Gia sư của tiểu thư kiêu ngạo", tag: "Chinh phục", color: "text-amber-400" },
  { title: "Huấn luyện viên Gym đào hoa", tag: "Xác thịt", color: "text-orange-400" },
  { title: "Tài xế của nữ chủ tịch", tag: "Cận kề", color: "text-slate-400" },
  { title: "Thám tử tư biến thái", tag: "Điều tra", color: "text-blue-500" },
  { title: "Hacker bóng đêm", tag: "Công nghệ", color: "text-green-500" },
  { title: "Đầu bếp 5 sao phong lưu", tag: "Nghệ thuật", color: "text-rose-400" },
  { title: "Cảnh sát chìm tàn nhẫn", tag: "Chính nghĩa", color: "text-sky-600" },
  { title: "Nhà tâm lý học thao túng", tag: "Tâm lý", color: "text-violet-500" },
  { title: "Trùm thế giới ngầm giải nghệ", tag: "Bá chủ", color: "text-red-600" },
  { title: "Chủ quán bar bí ẩn", tag: "Giao thiệp", color: "text-fuchsia-400" },
  { title: "Nhiếp ảnh gia mỹ nhân đồ", tag: "Sưu tầm", color: "text-pink-500" },
  { title: "Luật sư lách luật", tag: "Mưu lược", color: "text-zinc-400" },
  { title: "Chuyên gia trang điểm lãng tử", tag: "Gần gũi", color: "text-purple-300" },
  { title: "Bác sĩ gia đình dâm dật", tag: "Y thuật", color: "text-teal-400" },
  { title: "Người mẫu nam vạn người mê", tag: "Danh vọng", color: "text-indigo-300" },
  { title: "Ông trùm sòng bạc ngầm", tag: "Tiền bạc", color: "text-yellow-600" },
  { title: "Vệ sĩ riêng của minh tinh", tag: "Bảo vệ", color: "text-blue-400" },
  { title: "Kẻ mạo danh thiếu gia", tag: "Lừa lọc", color: "text-orange-300" },
  { title: "Nhân viên massage cao cấp", tag: "Kỹ năng", color: "text-rose-300" },
  { title: "Kiến trúc sư xây tổ ấm", tag: "Xây dựng", color: "text-lime-400" },
  { title: "Chủ tiệm hoa lãng mạn", tag: "Nhẹ nhàng", color: "text-green-300" },
  { title: "Thiên tài toán học cờ bạc", tag: "May rủi", color: "text-cyan-600" },
  { title: "Người thừa kế nghèo khổ", tag: "Trùng sinh", color: "text-stone-400" },
  { title: "Bố già khu ổ chuột", tag: "Thế lực", color: "text-neutral-500" },
  { title: "Chủ tiệm net thiên tài", tag: "Gamer", color: "text-blue-500" },
  { title: "Kẻ thu gom nợ thuê hào hiệp", tag: "Bạo lực", color: "text-red-500" },
  { title: "Phóng viên săn tin rúng động", tag: "Sự thật", color: "text-sky-400" },
  { title: "Quản gia của biệt phủ ma ám", tag: "Kỳ bí", color: "text-stone-500" },
  { title: "Giám đốc sáng tạo phong lưu", tag: "Nghệ thuật", color: "text-indigo-500" },
  { title: "Vua đầu bếp đường phố", tag: "Ẩm thực", color: "text-yellow-500" },
  { title: "Trai bao cao cấp giải nghệ", tag: "Nhạy cảm", color: "text-pink-600" },
  { title: "Người huấn luyện chó nghiệp vụ", tag: "Trung thành", color: "text-emerald-600" },
  { title: "Thiên tài ngoại giao quốc tế", tag: "Đàm phán", color: "text-cyan-600" },
  { title: "Phi công riêng của nữ tỷ phú", tag: "Bầu trời", color: "text-white" },
  { title: "Kẻ đào mộ đô thị", tag: "Khảo cổ", color: "text-orange-600" },
  { title: "Giáo sư trẻ nhất đại học", tag: "Trí tuệ", color: "text-indigo-300" },
  { title: "Streamer triệu view ẩn danh", tag: "Showbiz", color: "text-red-400" },
  { title: "Thợ săn tiền thưởng hiện đại", tag: "Thực dụng", color: "text-amber-600" },
  { title: "Ông trùm rửa tiền thế giới", tag: "Tội phạm", color: "text-zinc-600" },
  { title: "Người điều phối sự kiện hào môn", tag: "Giao thiệp", color: "text-purple-300" },
  { title: "Cố vấn phong thủy tỷ phú", tag: "Tâm linh", color: "text-emerald-500" },
  { title: "Nhà phê bình nghệ thuật tàn nhẫn", tag: "Sắc sảo", color: "text-rose-500" },
  { title: "Thiên tài chế tạo đồng hồ", tag: "Chính xác", color: "text-amber-400" },
  { title: "Sát thủ kinh tế (Trader)", tag: "Tàn nhẫn", color: "text-green-600" },
  { title: "Người nhặt rác sở hữu cổ phần", tag: "Ẩn danh", color: "text-stone-500" },
  { title: "Chủ quán nướng vỉa hè", tag: "Dân dã", color: "text-orange-300" },
  { title: "Thợ sửa ống nước hào môn", tag: "Cơ hội", color: "text-blue-300" },
  { title: "Nhân viên kho tập đoàn lớn", tag: "Bình thường", color: "text-neutral-400" },
  { title: "Thợ điện của biệt thự", tag: "Quan sát", color: "text-yellow-200" },
  { title: "Nhân viên vệ sinh nặc danh", tag: "Bí ẩn", color: "text-zinc-600" },
  { title: "Người đưa thư cũ", tag: "Hoài cổ", color: "text-amber-700" },
  { title: "Chủ tiệm cầm đồ tinh quái", tag: "Giao dịch", color: "text-emerald-700" },
  { title: "Kẻ bốc vác bến tàu", tag: "Sức mạnh", color: "text-slate-600" },
  { title: "Thợ cắt tóc nghệ nhân", tag: "Tỉ mỉ", color: "text-cyan-300" },
  { title: "Người trông coi nghĩa trang", tag: "Lạnh lẽo", color: "text-gray-700" },
  { title: "Chủ bãi phế liệu giàu ngầm", tag: "Giàu có", color: "text-yellow-600" },
  { title: "Thợ may trang phục quý bà", tag: "Gần gũi", color: "text-pink-300" },
  { title: "Người gác cổng cao ốc", tag: "Lặng lẽ", color: "text-blue-800" },
  { title: "Nhân viên giao Pizza thần tốc", tag: "Tốc độ", color: "text-red-500" },
  { title: "Thợ mộc trang trí biệt phủ", tag: "Kỹ nghệ", color: "text-orange-800" },
  { title: "Người làm vườn cho tiểu thư", tag: "Lãng mạn", color: "text-green-400" },
  { title: "Nhân viên cứu hộ hồ bơi", tag: "Thể hình", color: "text-sky-400" },
  { title: "Thợ đánh giày hào môn", tag: "Hạ cấp", color: "text-stone-600" },
  { title: "Nhân viên soát vé rạp phim", tag: "Quan sát", color: "text-indigo-200" },
  { title: "Chủ sạp báo cũ góc phố", tag: "Tin tức", color: "text-emerald-500" },
  { title: "Kẻ đào nợ thuê liều mạng", tag: "Nguy hiểm", color: "text-red-700" },
  { title: "Người huấn luyện chim cảnh", tag: "Thanh tao", color: "text-teal-300" },
  { title: "Thợ sửa giày da cao cấp", tag: "Kỹ năng", color: "text-amber-600" },
  { title: "Người bán hoa dạo đêm", tag: "U sầu", color: "text-purple-200" },
  { title: "Chủ tiệm trà sữa đông khách", tag: "Giao tiếp", color: "text-pink-200" },
  { title: "Nhân viên photocopy trường học", tag: "Trí thức", color: "text-blue-400" },
  { title: "Người gác kho sân bay", tag: "Thông tin", color: "text-slate-500" },
  { title: "Thợ rèn dao bếp huyền thoại", tag: "Kỹ nghệ", color: "text-orange-600" },
  { title: "Nhân viên diệt côn trùng", tag: "Xâm nhập", color: "text-lime-500" },
  { title: "Người chăn ngựa tại trường đua", tag: "Vương giả", color: "text-yellow-500" },
  { title: "Thợ sơn nhà nghệ thuật", tag: "Màu sắc", color: "text-fuchsia-400" },
  { title: "Nhân viên nhà tang lễ", tag: "U ám", color: "text-stone-800" },
  { title: "Chủ quán cháo đêm", tag: "Ấm áp", color: "text-amber-300" },
  { title: "Người thu mua ve chai công nghệ", tag: "Hacker", color: "text-green-600" },
  { title: "Nhân viên dắt chó đi dạo", tag: "Gần gũi", color: "text-emerald-200" },
  { title: "Thợ sửa ống khói biệt thự", tag: "Cổ điển", color: "text-amber-900" },
  { title: "Người bơm xăng nhiệt tình", tag: "Tiếp xúc", color: "text-blue-500" },
  { title: "Chủ tiệm giặt ủi hào môn", tag: "Bí mật", color: "text-indigo-300" },
  { title: "Người gác đèn hải đăng", tag: "Cô độc", color: "text-sky-700" },
  { title: "Thợ đánh máy nặc danh", tag: "Văn chương", color: "text-neutral-300" },
  { title: "Nhân viên cứu hộ động vật", tag: "Nhân hậu", color: "text-emerald-500" },
  { title: "Người bán kem đường phố", tag: "Vui vẻ", color: "text-yellow-300" },
  { title: "Chủ tiệm sửa khóa vạn năng", tag: "Xâm nhập", color: "text-zinc-500" },
  { title: "Nhân viên thu phí cầu đường", tag: "Quan sát", color: "text-slate-400" },
  { title: "Người gác rừng ngoại ô", tag: "Hoang dã", color: "text-green-700" },
  { title: "Thợ sửa dù lãng tử", tag: "Che chở", color: "text-sky-300" },
  { title: "Nhân viên soát vé tàu hỏa", tag: "Hành trình", color: "text-blue-600" },
  { title: "Chủ tiệm bánh mì truyền thống", tag: "Bình dị", color: "text-orange-200" },
  { title: "Thiên tài ngoại ngữ lang thang", tag: "Giao tiếp", color: "text-cyan-400" },
  { title: "Nhà ngoại giao bóng đêm", tag: "Chính trị", color: "text-indigo-900" },
  { title: "Vua sòng bài Ma Cao", tag: "Cờ bạc", color: "text-red-600" },
  { title: "Tổng tài hắc bang", tag: "Quyền lực", color: "text-zinc-900" },
  { title: "Hoàng tử sa mạc", tag: "Dầu mỏ", color: "text-yellow-600" },
  { title: "Trùm buôn vũ khí", tag: "Nguy hiểm", color: "text-orange-700" },
  { title: "Nam chính phim hành động", tag: "Showbiz", color: "text-blue-500" },
  { title: "Ca sĩ Rock nổi loạn", tag: "Nghệ sĩ", color: "text-purple-600" },
  { title: "Đạo diễn phim Adult", tag: "Dâm mị", color: "text-rose-600" },
  { title: "Giáo chủ tà giáo đô thị", tag: "Tâm linh", color: "text-indigo-700" },
  { title: "Người thừa kế đế chế kim cương", tag: "Hoa lệ", color: "text-cyan-200" },
  { title: "Cỗ máy giết người sinh học", tag: "Thí nghiệm", color: "text-red-900" },
  { title: "Thiên tài lập trình AI", tag: "Số hóa", color: "text-emerald-400" },
  { title: "Nhà sưu tầm cổ vật cấm", tag: "Bí ẩn", color: "text-amber-800" },
  { title: "Vua đường phố giải nghệ", tag: "Dã tính", color: "text-stone-700" },
  { title: "Kẻ thao túng thị trường vàng", tag: "Tài chính", color: "text-yellow-400" },
  { title: "Nam vương thế giới", tag: "Sắc đẹp", color: "text-pink-300" },
  { title: "Người điều khiển mạng lưới gián điệp", tag: "Thông tin", color: "text-sky-900" },
  { title: "Chủ tịch hội đồng tối cao", tag: "Tối thượng", color: "text-white" },
  { title: "Kẻ săn lùng đầu người", tag: "Tàn nhẫn", color: "text-red-800" },
  { title: "Thiên tài vật lý bị trục xuất", tag: "Trí tuệ", color: "text-violet-400" },
  { title: "Người nắm giữ bản đồ hầm ngục phố", tag: "Khám phá", color: "text-orange-500" },
  { title: "Trùm công nghệ thâu tóm dữ liệu", tag: "Kỹ thuật", color: "text-blue-300" },
  { title: "Kẻ thay thế vị vua đã chết", tag: "Giả mạo", color: "text-amber-600" },
  { title: "Người gác cổng địa ngục trần gian", tag: "Tâm linh", color: "text-black" },
  { title: "Nam thần sở hữu trái tim máy", tag: "Cyborg", color: "text-slate-400" },
  { title: "Kẻ buôn bán linh hồn hiện đại", tag: "Kỳ bí", color: "text-indigo-500" },
  { title: "Vua của những mạo hiểm giả phố", tag: "Huyền thoại", color: "text-amber-400" },
  { title: "Người tạo ra các ảo mộng dâm dục", tag: "Ảo giác", color: "text-pink-500" },
  { title: "Thợ săn quái vật đô thị SSS", tag: "Dị thường", color: "text-red-500" },
  { title: "Kẻ nắm giữ mật mã hạt nhân", tag: "Hủy diệt", color: "text-orange-900" },
  { title: "Nam hoàng hậu của đế chế ngầm", tag: "Vương giả", color: "text-fuchsia-600" },
  { title: "Thần chết thực tập tại phố đêm", tag: "Diệt vong", color: "text-gray-900" },
  { title: "Kẻ mở cổng không gian trái phép", tag: "Vượt biên", color: "text-sky-400" },
  { title: "Người điều khiển trọng lực phố", tag: "Vật lý", color: "text-indigo-600" },
  { title: "Thực thể ánh sáng chữa lành", tag: "Thần y", color: "text-emerald-300" },
  { title: "Kẻ săn tìm huyết mạch thần", tag: "Tham vọng", color: "text-red-600" },
  { title: "Vua tốc độ đường đua ngầm", tag: "Đua xe", color: "text-blue-700" },
  { title: "Chủ nhân tòa tháp 100 tầng", tag: "Thống trị", color: "text-zinc-500" },
  { title: "Kẻ nắm giữ bí mật vương triều cũ", tag: "Lịch sử", color: "text-stone-900" },
  { title: "Nam thần mang hơi thở băng giá", tag: "Hàn băng", color: "text-cyan-100" },
  { title: "Kẻ điều khiển bầy nhện ma pháp", tag: "Giam cầm", color: "text-purple-800" },
  { title: "Vua của các loài thú phố", tag: "Triệu hồi", color: "text-green-700" },
  { title: "Người sở hữu đôi mắt nhìn thấu", tag: "Thấu thị", color: "text-cyan-500" },
  { title: "Kẻ tạo ra các vụ nổ tinh thần", tag: "Cuồng bạo", color: "text-red-400" },
  { title: "Nam hoàng của thế giới ảo", tag: "Metaverse", color: "text-blue-200" },
  { title: "Kẻ nắm giữ chìa khóa vạn giới", tag: "Tối thượng", color: "text-yellow-700" },
  { title: "Người kể chuyện trong bar đêm", tag: "Bards", color: "text-indigo-400" },
  { title: "Kẻ thu thập ký ức hào môn", tag: "Tâm lý", color: "text-violet-600" },
  { title: "Thợ rèn phù văn hiện đại S", tag: "Kỹ nghệ", color: "text-amber-500" },
  { title: "Người bay lượn trên các tòa tháp", tag: "Tự do", color: "text-sky-300" },
  { title: "Kẻ điều phối các trận đấu ngầm", tag: "Cá cược", color: "text-orange-600" },
  { title: "Nam thần sở hữu giọng hát ma mị", tag: "Âm thanh", color: "text-teal-400" },
  { title: "Kẻ săn lùng các dị vật cổ", tag: "Sưu tầm", color: "text-amber-700" },
  { title: "Người điều khiển các chất độc đô thị", tag: "Ám sát", color: "text-lime-600" },
  { title: "Nam hoàng của bộ tộc rồng phố", tag: "Huyết thống", color: "text-rose-700" },
  { title: "Kẻ nắm giữ quy luật cái chết", tag: "Tử thần", color: "text-gray-800" },
  { title: "Người tạo ra các vùng không gian ảo", tag: "Ảo ảnh", color: "text-violet-300" },
  { title: "Nam thần mang năng lượng mặt trời", tag: "Rực rỡ", color: "text-yellow-500" },
  { title: "Kẻ điều khiển bầy ong linh năng", tag: "Dịch bệnh", color: "text-yellow-600" },
  { title: "Người sở hữu đôi cánh thiên sứ đen", tag: "Sa ngã", color: "text-slate-800" },
  { title: "Kẻ nắm giữ bản đồ vạn giới ngầm", tag: "Mạo hiểm", color: "text-orange-400" },
  { title: "Nam thần sở hữu trái tim rồng", tag: "Long huyết", color: "text-red-300" },
  { title: "Kẻ điều khiển các mảng thực tại", tag: "Vạn năng", color: "text-fuchsia-500" },
  { title: "Người gác cổng vương quốc đá phố", tag: "Trấn giữ", color: "text-stone-600" },
  { title: "Nam thần sở hữu đôi mắt âm dương", tag: "Tâm linh", color: "text-indigo-300" },
  { title: "Kẻ săn lùng các mỹ nhân hào môn", tag: "Harem", color: "text-pink-500" },
  { title: "Người tạo ra các vụ nổ ánh sáng", tag: "Chói lòa", color: "text-yellow-100" },
  { title: "Nam hoàng của đế chế ma mạng", tag: "Digital", color: "text-cyan-700" },
  { title: "Kẻ nắm giữ chìa khóa thiên đình phố", tag: "Tối thượng", color: "text-yellow-900" },
  { title: "Người sở hữu tiếng nói của rồng", tag: "Long ngữ", color: "text-orange-300" },
  { title: "Nam thần mang năng lượng sao băng", tag: "Rực rỡ", color: "text-blue-100" },
  { title: "Kẻ điều khiển bầy chim ma pháp", tag: "Thông tin", color: "text-cyan-400" },
  { title: "Người sở hữu làn da ngọc thạch", tag: "Phòng thủ", color: "text-emerald-100" },
  { title: "Nam thần mang linh hồn của rừng", tag: "Sự sống", color: "text-green-500" },
  { title: "Kẻ nắm giữ bí mật rồng thần phố", tag: "Sứ mệnh", color: "text-red-500" },
  { title: "Người sở hữu đôi tai Elf nhọn phố", tag: "Thanh cao", color: "text-green-200" },
  { title: "Nam thần mang năng lượng tinh tú", tag: "Hoa lệ", color: "text-white" },
  { title: "Kẻ điều khiển các mảng bóng tối phố", tag: "Hắc ám", color: "text-black" },
  { title: "Người sở hữu đôi cánh dơi phố", tag: "Bóng tối", color: "text-slate-900" },
  { title: "Nam thần mang sức mạnh khởi nguyên", tag: "Sáng thế", color: "text-emerald-900" },
  { title: "Kẻ nắm giữ bản đồ vạn giới vĩ đại", tag: "Tối thượng", color: "text-indigo-800" },
  { title: "Vị vua cuối cùng của Đô Thị", tag: "Vĩnh hằng", color: "text-yellow-500" }
];