export const CUSTOM_FANTASY_HUMAN = [
  { title: "Vương tử lưu vong", tag: "Vương quyền", color: "text-yellow-500" },
  { title: "Pháp sư bị trục xuất", tag: "Cấm thuật", color: "text-purple-400" },
  { title: "Kẻ diệt rồng thuê", tag: "Chiến binh", color: "text-orange-400" },
  { title: "Gián điệp nhị diện", tag: "Mưu lược", color: "text-blue-400" },
  { title: "Kỵ sĩ thánh điện kiêu ngạo", tag: "Đức tin", color: "text-white" },
  { title: "Thợ săn quái vật máu lạnh", tag: "Kỹ năng", color: "text-zinc-600" },
  { title: "Học giả ma pháp cổ đại", tag: "Tri thức", color: "text-cyan-400" },
  { title: "Nô lệ hầm mỏ thức tỉnh", tag: "Nghịch tập", color: "text-red-600" },
  { title: "Đạo tặc thành phố ngầm", tag: "Tốc độ", color: "text-neutral-500" },
  { title: "Lính đánh thuê máu sắt", tag: "Thực dụng", color: "text-slate-500" },
  { title: "Thợ rèn rồng thiêng", tag: "Chế tác", color: "text-amber-600" },
  { title: "Nhà giả kim điên cuồng", tag: "Thí nghiệm", color: "text-lime-500" },
  { title: "Kẻ canh giữ cổng thành", tag: "Trấn thủ", color: "text-sky-600" },
  { title: "Thương nhân lữ hành đào hoa", tag: "Tiền bạc", color: "text-yellow-400" },
  { title: "Tu sĩ bóng đêm", tag: "Hắc ám", color: "text-indigo-900" },
  { title: "Anh hùng dự ngôn thất bại", tag: "Bi kịch", color: "text-gray-400" },
  { title: "Lãnh chúa biên thùy tàn nhẫn", tag: "Quyền lực", color: "text-red-500" },
  { title: "Nhạc công lôi cuốn vạn vật", tag: "Âm thanh", color: "text-teal-400" },
  { title: "Kẻ thuần hóa quái thú", tag: "Triệu hồi", color: "text-green-600" },
  { title: "Giáo hoàng của tôn giáo mới", tag: "Thần quyền", color: "text-amber-300" },
  { title: "Kẻ xuyên không mang súng", tag: "Công nghệ", color: "text-blue-300" },
  { title: "Đao phủ của vương triều", tag: "Sát khí", color: "text-rose-800" },
  { title: "Kẻ buôn bán linh hồn", tag: "Tà thuật", color: "text-purple-700" },
  { title: "Thợ săn phù thủy", tag: "Trừng phạt", color: "text-red-700" },
  { title: "Người điều khiển giấc mơ", tag: "Tâm trí", color: "text-violet-300" },
  { title: "Kỵ sĩ rồng cuối cùng", tag: "Huyền thoại", color: "text-orange-500" },
  { title: "Pháp sư nguyên tố cuồng bạo", tag: "Hủy diệt", color: "text-red-400" },
  { title: "Kẻ lãng du tìm kiếm thánh di vật", tag: "Khám phá", color: "text-cyan-200" },
  { title: "Người giữ khóa hầm ngục", tag: "Bí ẩn", color: "text-stone-700" },
  { title: "Thái tử giả danh lính gác", tag: "Giả mạo", color: "text-yellow-700" },
  { title: "Kẻ mang lời nguyền bất tử", tag: "Cực hạn", color: "text-emerald-300" },
  { title: "Người chăn cừu sở hữu thánh lực", tag: "Ẩn tàng", color: "text-green-200" },
  { title: "Kẻ đào ngũ của đoàn kỵ binh", tag: "Hèn nhát", color: "text-slate-400" },
  { title: "Thợ săn kho báu phế tích", tag: "Mạo hiểm", color: "text-amber-400" },
  { title: "Người kể chuyện trong quán rượu", tag: "Bards", color: "text-indigo-300" },
  { title: "Kẻ sưu tầm mảnh vỡ ma thuật", tag: "Sưu tầm", color: "text-violet-500" },
  { title: "Chiến binh mang mặt nạ sắt", tag: "Bí ẩn", color: "text-zinc-600" },
  { title: "Người có khả năng giao tiếp rồng", tag: "Long ngữ", color: "text-rose-600" },
  { title: "Kẻ trộm trái tim nữ hoàng", tag: "Lãng tử", color: "text-pink-400" },
  { title: "Giáo sư học viện ma pháp", tag: "Hàn lâm", color: "text-blue-500" },
  { title: "Người gác hải đăng ven biển quỷ", tag: "Cô độc", color: "text-sky-300" },
  { title: "Kẻ buôn lậu dược liệu cấm", tag: "Gian xảo", color: "text-emerald-700" },
  { title: "Thợ săn linh hồn sa đọa", tag: "Trục xuất", color: "text-neutral-800" },
  { title: "Kỵ sĩ mù của vương quốc", tag: "Ý chí", color: "text-white" },
  { title: "Người hầu riêng của công chúa", tag: "Cận kề", color: "text-pink-300" },
  { title: "Kẻ nắm giữ bí mật vương triều", tag: "Nguy hiểm", color: "text-red-900" },
  { title: "Pháp sư thời không lưu lạc", tag: "Thời gian", color: "text-cyan-600" },
  { title: "Người bảo vệ khu rừng cấm", tag: "Hoang dã", color: "text-green-700" },
  { title: "Thiên tài chế tạo vũ khí hơi nước", tag: "Steampunk", color: "text-orange-700" },
  { title: "Đứa trẻ của dự ngôn", tag: "Định mệnh", color: "text-yellow-200" },
  { title: "Kẻ tiêu diệt quỷ vương tiền nhiệm", tag: "Vinh quang", color: "text-amber-500" },
  { title: "Thợ săn báu vật hầm ngục", tag: "Khám phá", color: "text-emerald-600" },
  { title: "Pháp sư tu luyện cấm thuật cổ", tag: "Bí mật", color: "text-purple-800" },
  { title: "Kỵ sĩ mang theo linh hồn chiến", tag: "Sứ mệnh", color: "text-slate-200" },
  { title: "Tiểu thư bá tước bị lưu lạc", tag: "Trùng sinh", color: "text-rose-400" },
  { title: "Thợ rèn vũ khí thánh", tag: "Kỹ nghệ", color: "text-amber-700" },
  { title: "Linh mục sa đọa bóng tối", tag: "Tà ác", color: "text-indigo-900" },
  { title: "Kẻ điều khiển bầy sói rừng", tag: "Dã tính", color: "text-green-800" },
  { title: "Người gác tháp canh biên thùy", tag: "Trấn thủ", color: "text-stone-500" },
  { title: "Pháp sư điều khiển các linh hồn", tag: "Tâm linh", color: "text-violet-600" },
  { title: "Kỵ sĩ mù mang thanh kiếm gãy", tag: "Huyền thoại", color: "text-neutral-400" },
  { title: "Nữ thợ săn mang theo cung thần", tag: "Tuyệt thế", color: "text-sky-500" },
  { title: "Kẻ nhặt xác trên chiến trường ma", tag: "Bần hàn", color: "text-zinc-700" },
  { title: "Người sở hữu đôi mắt thấu thị", tag: "Nhìn thấu", color: "text-cyan-300" },
  { title: "Pháp sư tu luyện đạo của lửa", tag: "Hủy diệt", color: "text-red-500" },
  { title: "Kỵ sĩ bảo vệ di tích cổ", tag: "Thanh cao", color: "text-white" },
  { title: "Kẻ buôn bán nô lệ vương quốc", tag: "Tàn nhẫn", color: "text-neutral-900" },
  { title: "Nữ phù thủy sống trong đầm lầy", tag: "Bí mật", color: "text-lime-700" },
  { title: "Người tạo ra các vụ nổ ma pháp", tag: "Cuồng bạo", color: "text-orange-600" },
  { title: "Kẻ điều khiển các mảng thực tại", tag: "Tối thượng", color: "text-purple-900" },
  { title: "Pháp sư hệ thủy dịu dàng", tag: "Sự sống", color: "text-blue-300" },
  { title: "Kỵ sĩ mang theo gánh nặng vua", tag: "Trung thành", color: "text-amber-800" },
  { title: "Người sở hữu tiếng nói của rồng", tag: "Long ngữ", color: "text-orange-500" },
  { title: "Kẻ săn lùng các mảnh vỡ thánh", tag: "Sưu tầm", color: "text-yellow-600" },
  { title: "Nữ kỵ sĩ mang theo vết sẹo hận", tag: "Báo thù", color: "text-red-700" },
  { title: "Pháp sư điều khiển trọng lực", tag: "Vật lý", color: "text-slate-600" },
  { title: "Người gác cổng địa ngục trần gian", tag: "Trấn thủ", color: "text-black" },
  { title: "Kẻ tạo ra các ảo ảnh mê hoặc", tag: "Dâm mị", color: "text-pink-500" },
  { title: "Pháp sư hệ mộc xanh tươi", tag: "Thiên nhiên", color: "text-green-500" },
  { title: "Kỵ sĩ sở hữu bộ giáp bạc", tag: "Vinh quang", color: "text-blue-200" },
  { title: "Người điều khiển các tia sét", tag: "Năng lượng", color: "text-yellow-400" },
  { title: "Kẻ nắm giữ bản đồ kho báu cổ", tag: "Mạo hiểm", color: "text-emerald-500" },
  { title: "Nữ pháp sư mang linh hồn quỷ", tag: "Mâu thuẫn", color: "text-purple-400" },
  { title: "Pháp sư hệ thổ kiên cố", tag: "Phòng thủ", color: "text-stone-600" },
  { title: "Kỵ sĩ mang theo lời nguyền băng", tag: "Lạnh lẽo", color: "text-cyan-100" },
  { title: "Người sở hữu đôi cánh thiên sứ", tag: "Thánh khiết", color: "text-amber-100" },
  { title: "Kẻ điều khiển bầy dơi đêm", tag: "Hắc ám", color: "text-neutral-800" },
  { title: "Pháp sư sở hữu kỹ năng thôi miên", tag: "Thao túng", color: "text-violet-500" },
  { title: "Kỵ sĩ bảo vệ biên giới phía bắc", tag: "Ý chí", color: "text-blue-900" },
  { title: "Người tạo ra các sợi tơ ma pháp", tag: "Trói buộc", color: "text-indigo-400" },
  { title: "Kẻ săn lùng huyết mạch thần", tag: "Tham vọng", color: "text-red-800" },
  { title: "Nữ pháp sư mang theo đóa hoa đen", tag: "Tử vong", color: "text-rose-900" },
  { title: "Pháp sư tu luyện đạo của gió", tag: "Tự do", color: "text-sky-200" },
  { title: "Kỵ sĩ sở hữu thanh kiếm thánh", tag: "Quân vương", color: "text-yellow-400" },
  { title: "Người điều khiển các vùng ảo mộng", tag: "Ảo giác", color: "text-fuchsia-400" },
  { title: "Kẻ nắm giữ chìa khóa vạn giới", tag: "Chúa tể", color: "text-emerald-900" },
  { title: "Linh mục bị nguyền rủa", tag: "Đức tin", color: "text-gray-500" },
  { title: "Thợ săn bóng ma kinh thành", tag: "Bí mật", color: "text-zinc-800" },
  { title: "Pháp sư chuyên gọi hồn kỵ sĩ", tag: "Cổ xưa", color: "text-indigo-700" },
  { title: "Người kể chuyện trong nghĩa trang", tag: "Kỳ bí", color: "text-stone-800" },
  { title: "Kỵ sĩ bảo vệ di thể vương phi", tag: "Tình thâm", color: "text-white" },
  { title: "Pháp sư tu luyện đạo của sao", tag: "Vũ trụ", color: "text-blue-200" },
  { title: "Thợ rèn chế tạo bẫy ma pháp", tag: "Gian xảo", color: "text-orange-500" },
  { title: "Người gác kho báu lăng mộ", tag: "Bí ẩn", color: "text-amber-900" },
  { title: "Pháp sư chuyên dùng thảo dược", tag: "Y thuật", color: "text-green-300" },
  { title: "Kỵ sĩ mù sở hữu thính nhạy", tag: "Bí ẩn", color: "text-stone-400" },
  { title: "Người tạo ra các vụ nổ tâm linh", tag: "Cuồng bạo", color: "text-red-400" },
  { title: "Pháp sư tu luyện đạo của nước", tag: "Mềm mại", color: "text-sky-400" },
  { title: "Kỵ sĩ mang theo lời nguyền lửa", tag: "Nóng bỏng", color: "text-red-500" },
  { title: "Người sở hữu tiếng nói thiên sứ", tag: "Âm thanh", color: "text-teal-200" },
  { title: "Pháp sư tu luyện đạo của đất S", tag: "Kiên cố", color: "text-stone-900" },
  { title: "Kỵ sĩ sở hữu đôi cánh dơi S", tag: "Bóng tối", color: "text-slate-900" },
  { title: "Người tạo ra các sợi tơ ma S", tag: "Trói buộc", color: "text-indigo-600" },
  { title: "Pháp sư tu luyện đạo của gió S", tag: "Tự do", color: "text-sky-100" },
  { title: "Kỵ sĩ sở hữu thanh kiếm thánh S", tag: "Vinh quang", color: "text-yellow-300" },
  { title: "Người gác cổng vương quốc đá S", tag: "Trấn giữ", color: "text-stone-700" },
  { title: "Pháp sư tu luyện đạo của lửa S", tag: "Hủy diệt", color: "text-red-400" },
  { title: "Kỵ sĩ sở hữu bộ giáp bạc S", tag: "Vương giả", color: "text-blue-100" },
  { title: "Người điều khiển các tia sét S", tag: "Năng lượng", color: "text-yellow-200" },
  { title: "Pháp sư tu luyện đạo của nước S", tag: "Sự sống", color: "text-blue-100" },
  { title: "Kỵ sĩ mang theo gánh nặng vua S", tag: "Trung thành", color: "text-amber-700" },
  { title: "Người sở hữu đôi mắt nhìn thấu S", tag: "Trí tuệ", color: "text-cyan-200" },
  { title: "Pháp sư hệ mộc xanh tươi S", tag: "Thiên nhiên", color: "text-green-400" },
  { title: "Kỵ sĩ bảo vệ biên giới bắc S", tag: "Ý chí", color: "text-blue-800" },
  { title: "Người tạo ra các ảo ảnh mê S", tag: "Dâm mị", color: "text-pink-400" },
  { title: "Pháp sư điều khiển trọng lực S", tag: "Vật lý", color: "text-slate-500" },
  { title: "Kỵ sĩ mù mang kiếm gãy S", tag: "Huyền thoại", color: "text-neutral-300" },
  { title: "Người sở hữu đôi cánh thiên sứ S", tag: "Thánh khiết", color: "text-amber-50" },
  { title: "Pháp sư tu luyện đạo của gió SS", tag: "Tự do", color: "text-sky-50" },
  { title: "Kỵ sĩ sở hữu thanh kiếm thánh SS", tag: "Quân vương", color: "text-yellow-200" },
  { title: "Vị vua cuối cùng của Nhân Loại", tag: "Vĩnh hằng", color: "text-yellow-500" }
];