export const CUSTOM_WUXIA = [
  { title: "Truyền nhân duy nhất của Kiếm Thánh", tag: "Tuyệt thế", color: "text-white" },
  { title: "Ma giáo giáo chủ phế vị", tag: "Báo thù", color: "text-red-600" },
  { title: "Lãng tử vô danh", tag: "Tự do", color: "text-emerald-400" },
  { title: "Kẻ giữ kho tàng Tiền Triều", tag: "Mật tạng", color: "text-amber-500" },
  { title: "Y thánh quái kiệt", tag: "Y thuật", color: "text-cyan-400" },
  { title: "Công tử mù của Vạn Gia", tag: "Bí ẩn", color: "text-indigo-400" },
  { title: "Đao khách say xỉn", tag: "Cuồng phóng", color: "text-orange-400" },
  { title: "Bổ đầu liêm khiết", tag: "Công lý", color: "text-sky-500" },
  { title: "Bang chủ Cái Bang trẻ tuổi", tag: "Hào hiệp", color: "text-yellow-700" },
  { title: "Sát thủ của Ảnh Các", tag: "Ám sát", color: "text-neutral-700" },
  { title: "Thiếu chủ của danh môn chính phái", tag: "Gia thế", color: "text-blue-400" },
  { title: "Kẻ trộm trái tim mỹ nhân", tag: "Đào hoa", color: "text-rose-400" },
  { title: "Võ sư mãi võ sơn đông", tag: "Bình dân", color: "text-stone-400" },
  { title: "Nhạc công của tửu lầu", tag: "Lãng mạn", color: "text-pink-300" },
  { title: "Kẻ đào mộ tìm bí tịch", tag: "Tà đạo", color: "text-zinc-600" },
  { title: "Quân sư của sơn tặc", tag: "Trí tuệ", color: "text-green-600" },
  { title: "Đệ tử tục gia thiếu lâm", tag: "Nội công", color: "text-yellow-500" },
  { title: "Ma giáo sứ giả phong lưu", tag: "Harem", color: "text-fuchsia-500" },
  { title: "Kiếm hầu hầu hạ tiên tử", tag: "Phục tùng", color: "text-slate-300" },
  { title: "Đại tặc giang hồ giải nghệ", tag: "Ẩn dật", color: "text-neutral-500" },
  { title: "Thợ rèn binh khí huyền thoại", tag: "Luyện khí", color: "text-orange-600" },
  { title: "Kẻ canh giữ nha môn", tag: "Trật tự", color: "text-blue-700" },
  { title: "Lãng tử hào hoa lừa tình", tag: "Xảo quyệt", color: "text-pink-500" },
  { title: "Đao phủ tàn nhẫn", tag: "Sát khí", color: "text-red-900" },
  { title: "Vương gia thích du ngoạn", tag: "Quyền quý", color: "text-yellow-600" },
  { title: "Kẻ đào ngũ của triều đình", tag: "Lưu vong", color: "text-teal-400" },
  { title: "Tu sĩ dâm dật nhập ma", tag: "Cấm kỵ", color: "text-purple-600" },
  { title: "Thợ săn tiền thưởng giang hồ", tag: "Thực dụng", color: "text-amber-400" },
  { title: "Kẻ mang theo huyết thư hoàng gia", tag: "Sứ mệnh", color: "text-red-500" },
  { title: "Đệ tử cái bang mang hệ thống", tag: "Nghịch tập", color: "text-cyan-300" },
  { title: "Chủ quán trọ sát nhân", tag: "Nguy hiểm", color: "text-stone-800" },
  { title: "Võ lâm minh chủ thất thế", tag: "Sa sút", color: "text-neutral-400" },
  { title: "Kẻ sưu tầm mỹ nhân kiếm", tag: "Đào hoa", color: "text-pink-400" },
  { title: "Tiểu sư đệ bị trục xuất", tag: "Oan ức", color: "text-sky-300" },
  { title: "Thợ may trang phục nữ hiệp", tag: "Gần gũi", color: "text-rose-300" },
  { title: "Võ sĩ giác đấu chợ đen", tag: "Máu me", color: "text-red-700" },
  { title: "Kẻ giữ chìa khóa tàng thư", tag: "Uyên bác", color: "text-indigo-400" },
  { title: "Tên cướp hoa khét tiếng", tag: "Tà ác", color: "text-purple-800" },
  { title: "Người chèo thuyền bến cô liêu", tag: "Ẩn dật", color: "text-blue-200" },
  { title: "Công tử ăn chơi phố đèn đỏ", tag: "Trác táng", color: "text-amber-300" },
  { title: "Kẻ đào ngũ của mật thám", tag: "Bí mật", color: "text-emerald-700" },
  { title: "Người thổi sáo gọi hồn", tag: "Tâm linh", color: "text-teal-600" },
  { title: "Đao khách mang sẹo lớn", tag: "Hung bạo", color: "text-zinc-700" },
  { title: "Thiên tài kỳ môn độn giáp", tag: "Trí tuệ", color: "text-green-400" },
  { title: "Kẻ buôn bán tin tức mật", tag: "Gián điệp", color: "text-cyan-600" },
  { title: "Sát thủ mù của triều đình", tag: "Sát khí", color: "text-black" },
  { title: "Thợ săn yêu quái giang hồ", tag: "Huyền bí", color: "text-orange-500" },
  { title: "Lãng tử si tình Nga Mi", tag: "Lụy tình", color: "text-pink-200" },
  { title: "Người gác miếu hoang", tag: "Ẩn nhẫn", color: "text-stone-300" },
  { title: "Đệ tử Võ Đang phá giới", tag: "Nổi loạn", color: "text-blue-500" },
  { title: "Kẻ nắm giữ bản đồ rồng", tag: "Vương giả", color: "text-yellow-400" },
  { title: "Đao khách uống rượu bằng vò", tag: "Cuồng hào", color: "text-orange-500" },
  { title: "Nữ hiệp sĩ cải trang nam", tag: "Giả dạng", color: "text-cyan-200" },
  { title: "Kẻ săn lùng tàn hồn kiếm", tag: "Bí mật", color: "text-indigo-700" },
  { title: "Tiểu thư môn phái bỏ trốn", tag: "Tự do", color: "text-pink-400" },
  { title: "Thợ rèn đao mang tâm ma", tag: "Hắc ám", color: "text-red-800" },
  { title: "Lãng tử gảy đàn gỗ mục", tag: "Nghệ sĩ", color: "text-emerald-500" },
  { title: "Kẻ giữ chìa khóa địa ngục", tag: "Cấm kỵ", color: "text-purple-900" },
  { title: "Đao khách mù vượt ải", tag: "Kiên định", color: "text-stone-400" },
  { title: "Tiểu đồ đệ thiên tài y", tag: "Y thuật", color: "text-green-300" },
  { title: "Kẻ buôn bán ngựa giang hồ", tag: "Thương nhân", color: "text-yellow-500" },
  { title: "Nữ ma đầu hối lỗi", tag: "Chuộc tội", color: "text-rose-500" },
  { title: "Kiếm khách mang theo hũ cốt", tag: "Tình thâm", color: "text-neutral-500" },
  { title: "Kẻ săn tiền thưởng vùng biên", tag: "Thực dụng", color: "text-amber-600" },
  { title: "Công tử ăn xin nát bấy", tag: "Trùng sinh", color: "text-orange-300" },
  { title: "Đao phủ có trái tim nhân", tag: "Mâu thuẫn", color: "text-red-500" },
  { title: "Nữ kiếm sĩ lạnh lùng như băng", tag: "Lãnh khốc", color: "text-blue-100" },
  { title: "Kẻ điều phối các trận đấu ngầm", tag: "Thống trị", color: "text-zinc-700" },
  { title: "Lãng tử uống máu thay rượu", tag: "Tà ma", color: "text-red-900" },
  { title: "Thợ săn sâm núi nghìn năm", tag: "Cơ duyên", color: "text-emerald-600" },
  { title: "Nữ bộ đầu tàn nhẫn nhất", tag: "Công lý", color: "text-sky-700" },
  { title: "Kẻ canh giữ tháp tử vong", tag: "Trấn thủ", color: "text-stone-900" },
  { title: "Kiếm khách sở hữu kiếm gỗ", tag: "Thoát tục", color: "text-white" },
  { title: "Tiểu sư muội mang theo độc", tag: "Nguy hiểm", color: "text-lime-500" },
  { title: "Kẻ nhặt xác trên chiến trường", tag: "Bần hàn", color: "text-neutral-600" },
  { title: "Đao khách tu luyện võ công", tag: "Cuồng bạo", color: "text-red-600" },
  { title: "Lãng tử mang theo ô lụa", tag: "Thanh lịch", color: "text-pink-100" },
  { title: "Kẻ đánh cắp bí kíp tà môn", tag: "Gian xảo", color: "text-purple-500" },
  { title: "Nữ pháp sư dùng bùa chú võ", tag: "Huyền ảo", color: "text-indigo-400" },
  { title: "Kiếm khách mù mang theo sáo", tag: "Tâm linh", color: "text-cyan-400" },
  { title: "Kẻ canh cổng môn phái cũ", tag: "Trung thành", color: "text-blue-900" },
  { title: "Đao khách mang theo con nhỏ", tag: "Trách nhiệm", color: "text-amber-700" },
  { title: "Tiểu thư hào môn thích học võ", tag: "Nổi loạn", color: "text-rose-300" },
  { title: "Kẻ trộm ngựa của minh chủ", tag: "Gan dạ", color: "text-yellow-600" },
  { title: "Lãng tử mang theo vết sẹo hận", tag: "Báo thù", color: "text-red-700" },
  { title: "Thợ rèn rèn nên thanh kiếm gãy", tag: "Kỳ lạ", color: "text-zinc-500" },
  { title: "Nữ ma nữ tu luyện đạo của gió", tag: "Tự do", color: "text-sky-500" },
  { title: "Kiếm khách mang theo bầu rượu", tag: "Phóng khoáng", color: "text-orange-400" },
  { title: "Kẻ nắm giữ bản đồ vạn kiếm", tag: "Sứ mệnh", color: "text-emerald-700" },
  { title: "Đao khách tu luyện đạo của đất", tag: "Kiên cố", color: "text-stone-600" },
  { title: "Tiểu đồ đệ nhặt được thần thông", tag: "May mắn", color: "text-yellow-200" },
  { title: "Lãng tử mang theo đóa hoa đào", tag: "Tình si", color: "text-rose-200" },
  { title: "Kẻ canh giữ cổng biên giới", tag: "Trấn thủ", color: "text-blue-800" },
  { title: "Nữ kiếm sĩ mang theo linh hồn", tag: "Bí ẩn", color: "text-indigo-300" },
  { title: "Kiếm khách tu luyện đạo của lửa", tag: "Rực rỡ", color: "text-red-400" },
  { title: "Kẻ nắm giữ chìa khóa giang hồ", tag: "Tối thượng", color: "text-amber-900" },
  { title: "Vị vua cuối cùng của Võ Lâm", tag: "Vĩnh hằng", color: "text-yellow-500" },
  { title: "Kiếm khách lội nước đi như bay", tag: "Khinh công", color: "text-cyan-300" },
  { title: "Đao khách dùng cành liễu trảm địch", tag: "Thoát tục", color: "text-green-200" },
  { title: "Nữ hiệp sĩ sở hữu đôi mắt lệ", tag: "U sầu", color: "text-blue-200" },
  { title: "Kẻ săn lùng báu vật Tiền Triều", tag: "Khám phá", color: "text-yellow-600" },
  { title: "Thợ rèn đúc nên thanh ma kiếm", tag: "Nguy hiểm", color: "text-red-800" },
  { title: "Lãng tử thổi sáo gọi mưa", tag: "Kỳ bí", color: "text-teal-400" },
  { title: "Nữ ma đầu chuyên dùng tơ nhện", tag: "Trói buộc", color: "text-purple-700" },
  { title: "Kiếm khách mù sở hữu thính nhạy", tag: "Bí ẩn", color: "text-stone-500" },
  { title: "Kẻ trộm lấy trái tim tiểu thư", tag: "Đào hoa", color: "text-pink-400" },
  { title: "Võ sư dạy võ cho trẻ mồ côi", tag: "Nhân hậu", color: "text-emerald-500" },
  { title: "Đao khách uống rượu máu", tag: "Tà ác", color: "text-red-900" },
  { title: "Nữ hiệp sĩ mang lời nguyền băng", tag: "Hàn băng", color: "text-cyan-100" },
  { title: "Kẻ nắm giữ mật lục giang hồ", tag: "Thông tin", color: "text-sky-900" },
  { title: "Thợ may y phục tàng hình", tag: "Ám sát", color: "text-zinc-400" },
  { title: "Lãng tử cưỡi ngựa trắng đêm", tag: "Anh hùng", color: "text-white" },
  { title: "Nữ ma đầu sở hữu đôi cánh đen", tag: "Sa ngã", color: "text-slate-900" },
  { title: "Kiếm khách tu luyện đạo của mây", tag: "Vô định", color: "text-blue-100" },
  { title: "Kẻ săn tiền thưởng vùng tuyết", tag: "Lạnh lùng", color: "text-sky-200" },
  { title: "Thợ rèn rèn nên thanh kiếm rồng", tag: "Huyền thoại", color: "text-orange-500" },
  { title: "Lãng tử mang theo linh hồn quỷ", tag: "Nghịch lý", color: "text-indigo-800" },
  { title: "Nữ hiệp sĩ sở hữu nụ cười tỏa nắng", tag: "Ấm áp", color: "text-yellow-200" },
  { title: "Kiếm khách tu luyện đạo của sấm", tag: "Cuồng bạo", color: "text-yellow-400" },
  { title: "Kẻ nắm giữ bản đồ vạn dặm", tag: "Sứ mệnh", color: "text-emerald-800" },
  { title: "Thợ rèn đúc nên thanh kiếm thánh", tag: "Chính nghĩa", color: "text-yellow-100" },
  { title: "Lãng tử uống rượu cùng trăng", tag: "Thanh cao", color: "text-white" },
  { title: "Nữ ma đầu sở hữu đôi mắt tím", tag: "Mê hoặc", color: "text-purple-600" },
  { title: "Kiếm khách tu luyện đạo của đá", tag: "Kiên cố", color: "text-stone-600" },
  { title: "Kẻ săn lùng huyết mạch Kiếm Vương", tag: "Tham vọng", color: "text-red-700" },
  { title: "Thợ rèn đúc nên thanh kiếm gãy S", tag: "Kỳ lạ", color: "text-zinc-600" },
  { title: "Lãng tử thổi sáo giữa rừng trúc", tag: "Yên tĩnh", color: "text-green-500" },
  { title: "Nữ hiệp sĩ sở hữu mái tóc bạc", tag: "Lão luyện", color: "text-slate-300" },
  { title: "Kiếm khách tu luyện đạo của nước", tag: "Mềm mại", color: "text-sky-400" },
  { title: "Kẻ nắm giữ chìa khóa vạn môn", tag: "Tối thượng", color: "text-purple-900" },
  { title: "Thợ rèn đúc nên thanh đao lửa", tag: "Hủy diệt", color: "text-red-500" },
  { title: "Lãng tử mang theo đóa hoa trắng", tag: "Thanh khiết", color: "text-white" },
  { title: "Nữ ma đầu chuyên dùng chất độc", tag: "Nguy hiểm", color: "text-lime-700" },
  { title: "Kiếm khách tu luyện đạo của trời", tag: "Cao quý", color: "text-blue-500" },
  { title: "Kẻ săn tiền thưởng vùng sa mạc", tag: "Khắc nghiệt", color: "text-amber-700" },
  { title: "Thợ rèn rèn nên thanh kiếm tiên", tag: "Huyền diệu", color: "text-cyan-200" },
  { title: "Lãng tử uống rượu dưới gốc đào", tag: "Lãng mạn", color: "text-pink-300" },
  { title: "Nữ hiệp sĩ sở hữu trái tim vàng", tag: "Nhân hậu", color: "text-yellow-500" },
  { title: "Kiếm khách tu luyện đạo của đất S", tag: "Kiên cố", color: "text-stone-800" },
  { title: "Kẻ nắm giữ bản đồ kho tàng cổ", tag: "Mạo hiểm", color: "text-orange-400" },
  { title: "Thợ rèn đúc nên thanh kiếm bóng", tag: "Hắc ám", color: "text-neutral-900" },
  { title: "Lãng tử thổi sáo bên bờ suối S", tag: "Thanh tịnh", color: "text-teal-300" },
  { title: "Nữ ma đầu sở hữu đôi tai thú", tag: "Dị chủng", color: "text-orange-400" },
  { title: "Kiếm khách tu luyện đạo của lôi", tag: "Tốc độ", color: "text-yellow-300" },
  { title: "Kẻ săn lùng các mảnh linh hồn S", tag: "Bí mật", color: "text-indigo-600" },
  { title: "Thợ rèn đúc nên thanh kiếm thánh S", tag: "Vinh quang", color: "text-yellow-400" },
  { title: "Lãng tử mang theo đóa hoa đỏ", tag: "Đam mê", color: "text-red-400" },
  { title: "Nữ ma đầu chuyên dùng tơ hồng", tag: "Mê mị", color: "text-pink-600" },
  { title: "Kiếm khách tu luyện đạo của gió S", tag: "Tự do", color: "text-sky-500" },
  { title: "Kẻ nắm giữ chìa khóa giang hồ S", tag: "Chúa tể", color: "text-emerald-900" }
];